# Generated by Django 5.2.14 on 2026-06-01 19:54

import backend.apps.accounts_auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('natural_person_lender', 'Natural-person lender'), ('legal_entity_lender_representative', 'Legal-entity lender representative'), ('admin', 'Admin'), ('superadmin', 'Superadmin')], max_length=64)),
                ('status', models.CharField(choices=[('pending_kyc', 'Pending KYC'), ('active', 'Active'), ('restricted', 'Restricted'), ('locked', 'Locked'), ('closed', 'Closed')], default='pending_kyc', max_length=32)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['email'],
            },
            managers=[
                ('objects', backend.apps.accounts_auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailLoginToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('requested_user_agent', models.TextField(blank=True)),
                ('consumed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consumed_user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_login_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationTermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terms_version', models.CharField(max_length=64)),
                ('terms_hash', models.CharField(max_length=128)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SensitiveActionCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('admin_login', 'Admin login'), ('withdrawal', 'Withdrawal'), ('bank_account_change', 'Bank account change'), ('fx', 'Currency exchange'), ('primary_investment', 'Primary investment'), ('secondary_market_listing', 'Secondary-market listing'), ('secondary_market_purchase', 'Secondary-market purchase')], max_length=64)),
                ('code_digest', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('requested_user_agent', models.TextField(blank=True)),
                ('consumed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consumed_user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitive_action_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_type', 'status'], name='accounts_au_account_849864_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_au_email_764d79_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillogintoken',
            index=models.Index(fields=['user', 'used_at', 'expires_at'], name='accounts_au_user_id_5df148_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillogintoken',
            index=models.Index(fields=['expires_at'], name='accounts_au_expires_235d53_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationtermsacceptance',
            index=models.Index(fields=['user', 'accepted_at'], name='accounts_au_user_id_bdffb0_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationtermsacceptance',
            index=models.Index(fields=['terms_version'], name='accounts_au_terms_v_09ff84_idx'),
        ),
        migrations.AddIndex(
            model_name='sensitiveactioncode',
            index=models.Index(fields=['user', 'action', 'consumed_at', 'expires_at'], name='accounts_au_user_id_e2f51c_idx'),
        ),
        migrations.AddIndex(
            model_name='sensitiveactioncode',
            index=models.Index(fields=['expires_at'], name='accounts_au_expires_09922d_idx'),
        ),
    ]
