# Generated by Django 5.2.14 on 2026-06-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillogintoken',
            name='encrypted_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sensitiveactioncode',
            name='encrypted_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sensitiveactioncode',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
