# Generated by Django 5.2.14 on 2026-06-01 20:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_auth', '0002_emaillogintoken_encrypted_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerificationChallenge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=32)),
                ('provider', models.CharField(max_length=32)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('superseded', 'Superseded'), ('expired', 'Expired')], default='pending', max_length=32)),
                ('code_digest', models.CharField(blank=True, max_length=64)),
                ('encrypted_code', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('requested_user_agent', models.TextField(blank=True)),
                ('confirmed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('confirmed_user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verification_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'status', 'expires_at'], name='accounts_au_user_id_3e60fa_idx'), models.Index(fields=['expires_at'], name='accounts_au_expires_f92706_idx')],
            },
        ),
    ]
