# Generated by Django 5.2.14 on 2026-06-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_auth', '0003_phoneverificationchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_env_managed_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
