# Generated by Django 5.2.14 on 2026-06-02 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_auth', '0004_user_is_env_managed_superadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAccessEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_user_id', models.UUIDField()),
                ('actor_account_type', models.CharField(max_length=64)),
                ('previous_status', models.CharField(choices=[('pending_kyc', 'Pending KYC'), ('active', 'Active'), ('restricted', 'Restricted'), ('locked', 'Locked'), ('closed', 'Closed')], max_length=32)),
                ('new_status', models.CharField(choices=[('pending_kyc', 'Pending KYC'), ('active', 'Active'), ('restricted', 'Restricted'), ('locked', 'Locked'), ('closed', 'Closed')], max_length=32)),
                ('previous_is_active', models.BooleanField()),
                ('new_is_active', models.BooleanField()),
                ('reason_code', models.CharField(choices=[('kyc_aml_review', 'KYC/AML review'), ('compliance_hold', 'Compliance hold'), ('email_recovery', 'Email recovery'), ('support_request', 'Support request'), ('account_closure', 'Account closure'), ('admin_correction', 'Admin correction'), ('other', 'Other')], default='other', max_length=64)),
                ('note', models.TextField(blank=True)),
                ('evidence_summary', models.TextField(blank=True)),
                ('clean_account_confirmed', models.BooleanField(default=False)),
                ('changed_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
                'indexes': [models.Index(fields=['user', 'changed_at'], name='accounts_au_user_id_05586e_idx'), models.Index(fields=['actor_user_id', 'changed_at'], name='accounts_au_actor_u_aef5cf_idx'), models.Index(fields=['new_status'], name='accounts_au_new_sta_08345c_idx'), models.Index(fields=['reason_code'], name='accounts_au_reason__5b6d25_idx')],
            },
        ),
    ]
