# Generated by Codex on 2026-06-15

from __future__ import annotations

from uuid import UUID

from django.db import migrations, models
from django.db.models import Q


LENDER_ACCOUNT_TYPES = {
    "natural_person_lender",
    "legal_entity_lender_representative",
}
REFERENCE_ALPHABET = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ"


def _reference_from_uuid(value: str) -> str:
    number = UUID(str(value)).int
    chars: list[str] = []
    for _ in range(8):
        number, remainder = divmod(number, len(REFERENCE_ALPHABET))
        chars.append(REFERENCE_ALPHABET[remainder])
    return "L" + "".join(reversed(chars))


def _candidate(base_reference: str, attempt: int) -> str:
    if attempt == 0:
        return base_reference
    suffix = REFERENCE_ALPHABET[(attempt - 1) % len(REFERENCE_ALPHABET)]
    return f"{base_reference[:-1]}{suffix}"


def populate_investor_references(apps, schema_editor) -> None:
    user_model = apps.get_model("accounts_auth", "User")
    used = set(
        user_model.objects.exclude(investor_reference="").values_list(
            "investor_reference", flat=True
        )
    )
    for user in user_model.objects.filter(
        account_type__in=LENDER_ACCOUNT_TYPES,
        investor_reference="",
    ).order_by("date_joined", "id"):
        base_reference = _reference_from_uuid(str(user.id))
        reference = ""
        for attempt in range(64):
            candidate = _candidate(base_reference, attempt)
            if candidate not in used:
                reference = candidate
                break
        if not reference:
            raise RuntimeError(f"Could not allocate investor reference for user {user.id}.")
        user.investor_reference = reference
        user.save(update_fields=["investor_reference"])
        used.add(reference)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts_auth", "0006_account_access_event_append_only_guard"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="investor_reference",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.RunPython(populate_investor_references, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["investor_reference"], name="accounts_au_investo_20c9c5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=~Q(investor_reference=""),
                fields=("investor_reference",),
                name="unique_user_investor_reference",
            ),
        ),
    ]
