# Generated by Django 5.2.16 on 2026-10-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_auth", "0007_user_investor_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillogintoken",
            name="superseded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
