# Generated by Django 5.2.14 on 2026-06-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_reporting_append_only_guards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrun',
            name='output_format',
            field=models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('zip', 'ZIP evidence package')], max_length=16),
        ),
        migrations.AlterField(
            model_name='reportrun',
            name='report_type',
            field=models.CharField(choices=[('operational_subledger', 'Operational subledger'), ('trial_balance', 'Trial balance'), ('garanta_accrued_revenue', 'Garanta accrued revenue'), ('bexio_accounting_export', 'Bexio accounting export'), ('bank_operations', 'Bank operations'), ('reconciliation', 'Reconciliation'), ('investor_balances', 'Investor balances'), ('balance_ageing', 'Balance ageing'), ('withdrawals', 'Withdrawals'), ('loan_funding', 'Loan funding'), ('repayment_status', 'Repayment status'), ('default_exposure', 'Default exposure'), ('recovery_write_off', 'Recovery/write-off'), ('fx_activity', 'FX activity'), ('kyc_status', 'KYC status'), ('audit_log', 'Audit log'), ('failed_outbox', 'Failed outbox'), ('participant_account_statement', 'Participant account statement'), ('annual_tax_information', 'Annual tax information')], max_length=64),
        ),
    ]
