# Generated by Django 5.2.14 on 2026-06-02 20:50

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('holdings', '0002_holding_event_append_only_guard'),
        ('ledger', '0006_investorpayoutinstruction'),
        ('loans', '0004_alter_loan_status_alter_loanevent_event_type'),
        ('platform_core', '0002_append_only_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerRepaymentEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('regular_installment', 'Regular installment'), ('partial_installment', 'Partial installment')], max_length=64)),
                ('amount_minor', models.BigIntegerField()),
                ('booking_date', models.DateField()),
                ('value_date', models.DateField()),
                ('received_at', models.DateTimeField()),
                ('expected_due_minor', models.BigIntegerField()),
                ('interest_applied_minor', models.BigIntegerField(default=0)),
                ('principal_applied_minor', models.BigIntegerField(default=0)),
                ('fees_applied_minor', models.BigIntegerField(default=0)),
                ('penalties_applied_minor', models.BigIntegerField(default=0)),
                ('remaining_installment_interest_minor', models.BigIntegerField(default=0)),
                ('remaining_installment_principal_minor', models.BigIntegerField(default=0)),
                ('warning_acknowledged', models.BooleanField(default=False)),
                ('created_by_admin_id', models.UUIDField()),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('bank_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrower_repayment_events', to='ledger.bankoperation')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrower_repayment_events', to='platform_core.currency')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrower_repayment_events', to='loans.loaninstallment')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrower_repayment_events', to='ledger.ledgerjournalentry')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrower_repayment_events', to='loans.loan')),
            ],
            options={
                'ordering': ['-value_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvestorRepaymentDistributionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investor_user_id', models.UUIDField()),
                ('amount_minor', models.BigIntegerField()),
                ('principal_minor', models.BigIntegerField(default=0)),
                ('interest_minor', models.BigIntegerField(default=0)),
                ('fee_minor', models.BigIntegerField(default=0)),
                ('current_principal_before_minor', models.BigIntegerField()),
                ('current_principal_after_minor', models.BigIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('balance_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_distribution_lines', to='ledger.investorbalancelot')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_distribution_lines', to='platform_core.currency')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_distribution_lines', to='holdings.investorloanholding')),
                ('repayment_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_lines', to='servicing.borrowerrepaymentevent')),
            ],
            options={
                'ordering': ['repayment_event', 'occurred_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='borrowerrepaymentevent',
            index=models.Index(fields=['loan', 'value_date'], name='servicing_b_loan_id_d5e0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowerrepaymentevent',
            index=models.Index(fields=['installment', 'value_date'], name='servicing_b_install_8968de_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowerrepaymentevent',
            index=models.Index(fields=['currency', 'value_date'], name='servicing_b_currenc_9addca_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowerrepaymentevent',
            index=models.Index(fields=['bank_operation'], name='servicing_b_bank_op_98e20f_idx'),
        ),
        migrations.AddConstraint(
            model_name='borrowerrepaymentevent',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='servicing_repayment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='borrowerrepaymentevent',
            constraint=models.CheckConstraint(condition=models.Q(('expected_due_minor__gte', 0), ('interest_applied_minor__gte', 0), ('principal_applied_minor__gte', 0), ('fees_applied_minor__gte', 0), ('penalties_applied_minor__gte', 0), ('remaining_installment_interest_minor__gte', 0), ('remaining_installment_principal_minor__gte', 0)), name='servicing_repayment_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='borrowerrepaymentevent',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('interest_applied_minor'), '+', models.F('principal_applied_minor')), '+', models.F('fees_applied_minor')), '+', models.F('penalties_applied_minor')))), name='servicing_repayment_amount_allocated'),
        ),
        migrations.AddIndex(
            model_name='investorrepaymentdistributionline',
            index=models.Index(fields=['repayment_event', 'investor_user_id'], name='servicing_i_repayme_9c55ce_idx'),
        ),
        migrations.AddIndex(
            model_name='investorrepaymentdistributionline',
            index=models.Index(fields=['holding', 'occurred_at'], name='servicing_i_holding_13466a_idx'),
        ),
        migrations.AddIndex(
            model_name='investorrepaymentdistributionline',
            index=models.Index(fields=['investor_user_id', 'occurred_at'], name='servicing_i_investo_362013_idx'),
        ),
        migrations.AddIndex(
            model_name='investorrepaymentdistributionline',
            index=models.Index(fields=['balance_lot'], name='servicing_i_balance_5be9c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='investorrepaymentdistributionline',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='servicing_distribution_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='investorrepaymentdistributionline',
            constraint=models.CheckConstraint(condition=models.Q(('principal_minor__gte', 0), ('interest_minor__gte', 0), ('fee_minor__gte', 0), ('current_principal_before_minor__gte', 0), ('current_principal_after_minor__gte', 0)), name='servicing_distribution_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='investorrepaymentdistributionline',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('principal_minor'), '+', models.F('interest_minor')), '-', models.F('fee_minor')))), name='servicing_distribution_amount_reconciles'),
        ),
    ]
