# Generated by Django 5.2.14 on 2026-06-02 22:00

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_investorpayoutinstruction'),
        ('loans', '0005_alter_loan_status_alter_loanevent_event_type'),
        ('platform_core', '0002_append_only_guards'),
        ('servicing', '0002_servicing_append_only_guards'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='borrowerrepaymentevent',
            name='servicing_repayment_amounts_nonnegative',
        ),
        migrations.RemoveConstraint(
            model_name='borrowerrepaymentevent',
            name='servicing_repayment_amount_allocated',
        ),
        migrations.AddField(
            model_name='borrowerrepaymentevent',
            name='future_principal_applied_minor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='borrowerrepaymentevent',
            name='event_type',
            field=models.CharField(choices=[('regular_installment', 'Regular installment'), ('partial_installment', 'Partial installment'), ('early_repayment', 'Early repayment')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='borrowerrepaymentevent',
            constraint=models.CheckConstraint(condition=models.Q(('expected_due_minor__gte', 0), ('interest_applied_minor__gte', 0), ('principal_applied_minor__gte', 0), ('future_principal_applied_minor__gte', 0), ('fees_applied_minor__gte', 0), ('penalties_applied_minor__gte', 0), ('remaining_installment_interest_minor__gte', 0), ('remaining_installment_principal_minor__gte', 0)), name='servicing_repayment_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='borrowerrepaymentevent',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('interest_applied_minor'), '+', models.F('principal_applied_minor')), '+', models.F('future_principal_applied_minor')), '+', models.F('fees_applied_minor')), '+', models.F('penalties_applied_minor')))), name='servicing_repayment_amount_allocated'),
        ),
    ]
