# Generated by Django 5.2.14 on 2026-06-04 08:17

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loan_status_alter_loanevent_event_type'),
        ('platform_core', '0002_append_only_guards'),
        ('servicing', '0004_reinstall_append_only_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRiskNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrower_id', models.UUIDField()),
                ('visibility', models.CharField(choices=[('internal', 'Internal'), ('public', 'Public')], max_length=16)),
                ('note_type', models.CharField(choices=[('internal_note', 'Internal note'), ('public_update', 'Public update'), ('default_update', 'Default update'), ('recovery_update', 'Recovery update'), ('document_note', 'Document note')], max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('created_by_admin_id', models.UUIDField()),
                ('occurred_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_notes', to='loans.loan')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['loan', 'visibility', 'occurred_at'], name='servicing_l_loan_id_0986a6_idx'), models.Index(fields=['borrower_id', 'occurred_at'], name='servicing_l_borrowe_14f790_idx'), models.Index(fields=['created_by_admin_id', 'occurred_at'], name='servicing_l_created_cffec5_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoanWriteOffEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrower_id', models.UUIDField()),
                ('written_off_principal_minor', models.BigIntegerField(default=0)),
                ('written_off_contractual_interest_minor', models.BigIntegerField(default=0)),
                ('written_off_default_interest_minor', models.BigIntegerField(default=0)),
                ('written_off_fees_minor', models.BigIntegerField(default=0)),
                ('written_off_penalties_minor', models.BigIntegerField(default=0)),
                ('total_written_off_minor', models.BigIntegerField()),
                ('previous_loan_status', models.CharField(max_length=32)),
                ('new_loan_status', models.CharField(max_length=32)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('written_off_at', models.DateTimeField()),
                ('created_by_admin_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_write_off_events', to='platform_core.currency')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_off_events', to='loans.loan')),
            ],
            options={
                'ordering': ['-written_off_at', '-id'],
                'indexes': [models.Index(fields=['loan', 'written_off_at'], name='servicing_l_loan_id_0d51de_idx'), models.Index(fields=['borrower_id', 'written_off_at'], name='servicing_l_borrowe_65a1b0_idx'), models.Index(fields=['currency', 'written_off_at'], name='servicing_l_currenc_fdba9e_idx'), models.Index(fields=['created_by_admin_id', 'written_off_at'], name='servicing_l_created_d44b6e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('written_off_principal_minor__gte', 0), ('written_off_contractual_interest_minor__gte', 0), ('written_off_default_interest_minor__gte', 0), ('written_off_fees_minor__gte', 0), ('written_off_penalties_minor__gte', 0)), name='servicing_write_off_amounts_nonnegative'), models.CheckConstraint(condition=models.Q(('total_written_off_minor', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('written_off_principal_minor'), '+', models.F('written_off_contractual_interest_minor')), '+', models.F('written_off_default_interest_minor')), '+', models.F('written_off_fees_minor')), '+', models.F('written_off_penalties_minor')))), name='servicing_write_off_total_reconciles'), models.CheckConstraint(condition=models.Q(('total_written_off_minor__gt', 0)), name='servicing_write_off_total_positive')],
            },
        ),
    ]
