# Generated by Django 5.2.14 on 2026-06-04 08:55

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0002_holding_event_append_only_guard'),
        ('ledger', '0008_alter_investorbalancelot_source_type'),
        ('loans', '0007_alter_loanevent_event_type'),
        ('platform_core', '0002_append_only_guards'),
        ('servicing', '0006_risk_writeoff_append_only_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRecoveryEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrower_id', models.UUIDField()),
                ('gross_recovered_minor', models.BigIntegerField()),
                ('externally_deducted_costs_minor', models.BigIntegerField(default=0)),
                ('net_received_minor', models.BigIntegerField()),
                ('third_party_costs_from_received_minor', models.BigIntegerField(default=0)),
                ('recovery_fee_applied', models.BooleanField(default=False)),
                ('recovery_fee_bps', models.PositiveIntegerField(default=0)),
                ('recovery_fee_base_minor', models.BigIntegerField(default=0)),
                ('recovery_fee_minor', models.BigIntegerField(default=0)),
                ('net_available_for_distribution_minor', models.BigIntegerField()),
                ('principal_recovered_minor', models.BigIntegerField(default=0)),
                ('contractual_interest_recovered_minor', models.BigIntegerField(default=0)),
                ('default_interest_recovered_minor', models.BigIntegerField(default=0)),
                ('penalties_recovered_minor', models.BigIntegerField(default=0)),
                ('other_costs_recovered_minor', models.BigIntegerField(default=0)),
                ('rounding_difference_minor', models.BigIntegerField(default=0)),
                ('booking_date', models.DateField()),
                ('value_date', models.DateField()),
                ('received_at', models.DateTimeField()),
                ('recovery_waterfall_config', models.JSONField(blank=True, default=dict)),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_by_admin_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('bank_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_recovery_events', to='ledger.bankoperation')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_recovery_events', to='platform_core.currency')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_recovery_events', to='ledger.ledgerjournalentry')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_events', to='loans.loan')),
            ],
            options={
                'ordering': ['-value_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvestorRecoveryDistributionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investor_user_id', models.UUIDField()),
                ('amount_minor', models.BigIntegerField()),
                ('principal_minor', models.BigIntegerField(default=0)),
                ('contractual_interest_minor', models.BigIntegerField(default=0)),
                ('default_interest_minor', models.BigIntegerField(default=0)),
                ('penalties_minor', models.BigIntegerField(default=0)),
                ('other_costs_minor', models.BigIntegerField(default=0)),
                ('current_principal_before_minor', models.BigIntegerField()),
                ('current_principal_after_minor', models.BigIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('balance_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_distribution_lines', to='ledger.investorbalancelot')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_distribution_lines', to='platform_core.currency')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_distribution_lines', to='holdings.investorloanholding')),
                ('recovery_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_lines', to='servicing.loanrecoveryevent')),
            ],
            options={
                'ordering': ['recovery_event', 'occurred_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='loanrecoveryevent',
            index=models.Index(fields=['loan', 'value_date'], name='servicing_l_loan_id_82c949_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrecoveryevent',
            index=models.Index(fields=['borrower_id', 'value_date'], name='servicing_l_borrowe_5f01e1_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrecoveryevent',
            index=models.Index(fields=['currency', 'value_date'], name='servicing_l_currenc_cf82ad_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrecoveryevent',
            index=models.Index(fields=['bank_operation'], name='servicing_l_bank_op_765da5_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrecoveryevent',
            index=models.Index(fields=['journal_entry'], name='servicing_l_journal_0fc4b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='loanrecoveryevent',
            constraint=models.CheckConstraint(condition=models.Q(('gross_recovered_minor__gt', 0), ('externally_deducted_costs_minor__gte', 0), ('net_received_minor__gt', 0), ('third_party_costs_from_received_minor__gte', 0), ('recovery_fee_bps__gte', 0), ('recovery_fee_base_minor__gte', 0), ('recovery_fee_minor__gte', 0), ('net_available_for_distribution_minor__gte', 0), ('principal_recovered_minor__gte', 0), ('contractual_interest_recovered_minor__gte', 0), ('default_interest_recovered_minor__gte', 0), ('penalties_recovered_minor__gte', 0), ('other_costs_recovered_minor__gte', 0), ('rounding_difference_minor__gte', 0)), name='servicing_recovery_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='loanrecoveryevent',
            constraint=models.CheckConstraint(condition=models.Q(('net_received_minor', django.db.models.expressions.CombinedExpression(models.F('gross_recovered_minor'), '-', models.F('externally_deducted_costs_minor')))), name='servicing_recovery_net_received_reconciles'),
        ),
        migrations.AddConstraint(
            model_name='loanrecoveryevent',
            constraint=models.CheckConstraint(condition=models.Q(('net_available_for_distribution_minor', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('net_received_minor'), '-', models.F('third_party_costs_from_received_minor')), '-', models.F('recovery_fee_minor')))), name='servicing_recovery_net_available_reconciles'),
        ),
        migrations.AddConstraint(
            model_name='loanrecoveryevent',
            constraint=models.CheckConstraint(condition=models.Q(('net_available_for_distribution_minor', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('principal_recovered_minor'), '+', models.F('contractual_interest_recovered_minor')), '+', models.F('default_interest_recovered_minor')), '+', models.F('penalties_recovered_minor')), '+', models.F('other_costs_recovered_minor')), '+', models.F('rounding_difference_minor')))), name='servicing_recovery_distribution_reconciles'),
        ),
        migrations.AddIndex(
            model_name='investorrecoverydistributionline',
            index=models.Index(fields=['recovery_event', 'investor_user_id'], name='servicing_i_recover_d5e2b3_idx'),
        ),
        migrations.AddIndex(
            model_name='investorrecoverydistributionline',
            index=models.Index(fields=['holding', 'occurred_at'], name='servicing_i_holding_339b42_idx'),
        ),
        migrations.AddIndex(
            model_name='investorrecoverydistributionline',
            index=models.Index(fields=['investor_user_id', 'occurred_at'], name='servicing_i_investo_3305f2_idx'),
        ),
        migrations.AddIndex(
            model_name='investorrecoverydistributionline',
            index=models.Index(fields=['balance_lot'], name='servicing_i_balance_a28702_idx'),
        ),
        migrations.AddConstraint(
            model_name='investorrecoverydistributionline',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='servicing_recovery_line_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='investorrecoverydistributionline',
            constraint=models.CheckConstraint(condition=models.Q(('principal_minor__gte', 0), ('contractual_interest_minor__gte', 0), ('default_interest_minor__gte', 0), ('penalties_minor__gte', 0), ('other_costs_minor__gte', 0), ('current_principal_before_minor__gte', 0), ('current_principal_after_minor__gte', 0)), name='servicing_recovery_line_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='investorrecoverydistributionline',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('principal_minor'), '+', models.F('contractual_interest_minor')), '+', models.F('default_interest_minor')), '+', models.F('penalties_minor')), '+', models.F('other_costs_minor')))), name='servicing_recovery_line_amount_reconciles'),
        ),
    ]
