# Generated by Django 5.2.14 on 2026-06-06 14:23

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0002_holding_event_append_only_guard'),
        ('platform_core', '0003_scheduledjobrun'),
        ('servicing', '0008_recovery_append_only_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorLossRecognitionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investor_user_id', models.UUIDField()),
                ('principal_loss_minor', models.BigIntegerField(default=0)),
                ('contractual_interest_loss_minor', models.BigIntegerField(default=0)),
                ('default_interest_loss_minor', models.BigIntegerField(default=0)),
                ('fees_loss_minor', models.BigIntegerField(default=0)),
                ('penalties_loss_minor', models.BigIntegerField(default=0)),
                ('total_loss_minor', models.BigIntegerField()),
                ('current_principal_before_minor', models.BigIntegerField()),
                ('current_principal_after_minor', models.BigIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loss_recognition_lines', to='platform_core.currency')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loss_recognition_lines', to='holdings.investorloanholding')),
                ('write_off_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loss_recognition_lines', to='servicing.loanwriteoffevent')),
            ],
            options={
                'ordering': ['write_off_event', 'occurred_at', 'id'],
                'indexes': [models.Index(fields=['write_off_event', 'investor_user_id'], name='servicing_i_write_o_c006fe_idx'), models.Index(fields=['holding', 'occurred_at'], name='servicing_i_holding_13edfc_idx'), models.Index(fields=['investor_user_id', 'occurred_at'], name='servicing_i_investo_02b557_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('principal_loss_minor__gte', 0), ('contractual_interest_loss_minor__gte', 0), ('default_interest_loss_minor__gte', 0), ('fees_loss_minor__gte', 0), ('penalties_loss_minor__gte', 0), ('current_principal_before_minor__gte', 0), ('current_principal_after_minor__gte', 0)), name='servicing_loss_line_amounts_nonnegative'), models.CheckConstraint(condition=models.Q(('total_loss_minor__gt', 0)), name='servicing_loss_line_total_positive'), models.CheckConstraint(condition=models.Q(('total_loss_minor', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('principal_loss_minor'), '+', models.F('contractual_interest_loss_minor')), '+', models.F('default_interest_loss_minor')), '+', models.F('fees_loss_minor')), '+', models.F('penalties_loss_minor')))), name='servicing_loss_line_total_reconciles')],
            },
        ),
    ]
