# Generated by Django 5.2.14 on 2026-06-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_alter_loanevent_event_type'),
        ('platform_core', '0003_scheduledjobrun'),
        ('servicing', '0010_loss_recognition_append_only_guards'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loanwriteoffevent',
            constraint=models.UniqueConstraint(fields=('loan',), name='unique_loan_write_off_event'),
        ),
    ]
