# Generated by Django 5.2.14 on 2026-06-02 18:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_document_append_only_guards'),
        ('ledger', '0006_investorpayoutinstruction'),
        ('loans', '0002_loan_event_append_only_guard'),
        ('platform_core', '0002_append_only_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryInvestmentOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investor_user_id', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('balance_allocated', 'Balance allocated'), ('partially_allocated', 'Partially allocated'), ('balance_released', 'Balance released'), ('closed_not_invested', 'Closed not invested')], default='pending', max_length=64)),
                ('requested_amount_minor', models.BigIntegerField()),
                ('allocated_amount_minor', models.BigIntegerField(default=0)),
                ('lot_allocations', models.JSONField(blank=True, default=list)),
                ('created_by_user_id', models.UUIDField()),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by_admin_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_investment_orders', to='platform_core.currency')),
                ('document_acceptance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_investment_orders', to='documents.documentacceptanceevidence')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_investment_orders', to='loans.loan')),
                ('release_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_investment_orders_released', to='ledger.ledgerjournalentry')),
                ('reservation_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_investment_orders_reserved', to='ledger.ledgerjournalentry')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PrimaryInvestmentOrderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_id', models.UUIDField()),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('balance_allocated', 'Balance allocated'), ('balance_released', 'Balance released'), ('closed_not_invested', 'Closed not invested')], max_length=64)),
                ('actor_user_id', models.UUIDField()),
                ('actor_account_type', models.CharField(max_length=64)),
                ('previous_status', models.CharField(blank=True, max_length=64)),
                ('new_status', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='marketplace_primary.primaryinvestmentorder')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='primaryinvestmentorder',
            index=models.Index(fields=['loan', 'status', 'created_at'], name='marketplace_loan_id_26cbdb_idx'),
        ),
        migrations.AddIndex(
            model_name='primaryinvestmentorder',
            index=models.Index(fields=['investor_user_id', 'status', 'created_at'], name='marketplace_investo_ca8dab_idx'),
        ),
        migrations.AddIndex(
            model_name='primaryinvestmentorder',
            index=models.Index(fields=['currency', 'status'], name='marketplace_currenc_6a5fe8_idx'),
        ),
        migrations.AddConstraint(
            model_name='primaryinvestmentorder',
            constraint=models.CheckConstraint(condition=models.Q(('requested_amount_minor__gt', 0)), name='primary_order_requested_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='primaryinvestmentorder',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount_minor__gte', 0)), name='primary_order_allocated_amount_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='primaryinvestmentorderevent',
            index=models.Index(fields=['order', 'occurred_at'], name='marketplace_order_i_55186b_idx'),
        ),
        migrations.AddIndex(
            model_name='primaryinvestmentorderevent',
            index=models.Index(fields=['loan_id', 'event_type'], name='marketplace_loan_id_e2f51d_idx'),
        ),
        migrations.AddIndex(
            model_name='primaryinvestmentorderevent',
            index=models.Index(fields=['actor_user_id', 'occurred_at'], name='marketplace_actor_u_7b7c3f_idx'),
        ),
    ]
