# Generated by Django 5.2.14 on 2026-06-02 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_investorpayoutinstruction'),
        ('loans', '0004_alter_loan_status_alter_loanevent_event_type'),
        ('marketplace_primary', '0002_primary_order_event_append_only_guard'),
        ('platform_core', '0002_append_only_guards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryinvestmentorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('balance_allocated', 'Balance allocated'), ('partially_allocated', 'Partially allocated'), ('balance_released', 'Balance released'), ('closed_invested', 'Closed invested'), ('closed_not_invested', 'Closed not invested')], default='pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='primaryinvestmentorderevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('balance_allocated', 'Balance allocated'), ('balance_released', 'Balance released'), ('closed_invested', 'Closed invested'), ('closed_not_invested', 'Closed not invested'), ('loan_closed', 'Loan closed')], max_length=64),
        ),
        migrations.CreateModel(
            name='PrimaryLoanClose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('close_type', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial')], max_length=32)),
                ('accepted_principal_minor', models.BigIntegerField()),
                ('allocated_order_count', models.PositiveIntegerField()),
                ('closed_not_invested_order_count', models.PositiveIntegerField(default=0)),
                ('borrower_success_fee_bps', models.PositiveIntegerField()),
                ('borrower_success_fee_minor', models.BigIntegerField()),
                ('borrower_disbursement_payable_minor', models.BigIntegerField()),
                ('created_by_admin_id', models.UUIDField()),
                ('closed_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True)),
                ('investor_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_market_closes', to='platform_core.currency')),
                ('funding_close_journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_market_closes', to='ledger.ledgerjournalentry')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_market_closes', to='loans.loan')),
            ],
            options={
                'ordering': ['-closed_at', '-id'],
                'indexes': [models.Index(fields=['loan', 'closed_at'], name='marketplace_loan_id_442bc5_idx'), models.Index(fields=['currency', 'closed_at'], name='marketplace_currenc_884c8a_idx'), models.Index(fields=['created_by_admin_id', 'closed_at'], name='marketplace_created_b5edad_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('accepted_principal_minor__gt', 0)), name='primary_close_accepted_principal_positive'), models.CheckConstraint(condition=models.Q(('borrower_success_fee_minor__gte', 0)), name='primary_close_success_fee_nonnegative'), models.CheckConstraint(condition=models.Q(('borrower_disbursement_payable_minor__gte', 0)), name='primary_close_disbursement_payable_nonnegative'), models.UniqueConstraint(fields=('loan',), name='unique_primary_close_per_loan')],
            },
        ),
    ]
