# Generated by Django 5.2.16 on 2026-08-07 21:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


APPEND_ONLY_TABLE = "marketplace_primary_primaryinvestmentorderbatch"


def install_batch_append_only_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == "postgresql":
            cursor.execute(
                f"""
                DROP TRIGGER IF EXISTS {APPEND_ONLY_TABLE}_append_only_guard
                ON {APPEND_ONLY_TABLE};
                CREATE TRIGGER {APPEND_ONLY_TABLE}_append_only_guard
                BEFORE UPDATE OR DELETE ON {APPEND_ONLY_TABLE}
                FOR EACH ROW
                EXECUTE FUNCTION platform_core_prevent_append_only_mutation();
                """
            )
        elif vendor == "sqlite":
            cursor.execute(f"DROP TRIGGER IF EXISTS {APPEND_ONLY_TABLE}_append_only_update_guard;")
            cursor.execute(f"DROP TRIGGER IF EXISTS {APPEND_ONLY_TABLE}_append_only_delete_guard;")
            cursor.execute(
                f"""
                CREATE TRIGGER {APPEND_ONLY_TABLE}_append_only_update_guard
                BEFORE UPDATE ON {APPEND_ONLY_TABLE}
                BEGIN
                    SELECT RAISE(ABORT, 'append-only table cannot be updated');
                END;
                """
            )
            cursor.execute(
                f"""
                CREATE TRIGGER {APPEND_ONLY_TABLE}_append_only_delete_guard
                BEFORE DELETE ON {APPEND_ONLY_TABLE}
                BEGIN
                    SELECT RAISE(ABORT, 'append-only table cannot be deleted');
                END;
                """
            )


def uninstall_batch_append_only_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == "postgresql":
            cursor.execute(
                f"""
                DROP TRIGGER IF EXISTS {APPEND_ONLY_TABLE}_append_only_guard
                ON {APPEND_ONLY_TABLE};
                """
            )
        elif vendor == "sqlite":
            cursor.execute(f"DROP TRIGGER IF EXISTS {APPEND_ONLY_TABLE}_append_only_update_guard;")
            cursor.execute(f"DROP TRIGGER IF EXISTS {APPEND_ONLY_TABLE}_append_only_delete_guard;")


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_alter_documentacceptanceevidence_category_and_more"),
        ("marketplace_primary", "0005_primaryloancancellation"),
        ("platform_core", "0004_qa_dev_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrimaryInvestmentOrderBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("investor_user_id", models.UUIDField()),
                ("item_snapshot", models.JSONField(default=list)),
                ("order_ids", models.JSONField(default=list)),
                ("order_count", models.PositiveIntegerField()),
                ("total_amount_minor", models.BigIntegerField()),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_investment_order_batches",
                        to="platform_core.currency",
                    ),
                ),
                (
                    "document_acceptance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_investment_order_batches",
                        to="documents.documentacceptanceevidence",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["investor_user_id", "created_at"],
                        name="marketplace_investo_f99457_idx",
                    ),
                    models.Index(
                        fields=["currency", "created_at"], name="marketplace_currenc_bec76f_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("order_count__gt", 0)),
                        name="primary_order_batch_count_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("total_amount_minor__gt", 0)),
                        name="primary_order_batch_total_positive",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            install_batch_append_only_guards,
            uninstall_batch_append_only_guards,
        ),
    ]
