# Generated by Django 5.2.16 on 2026-08-08 06:20

import django.db.models.deletion
from django.db import migrations, models

APPEND_ONLY_TABLE = "marketplace_primary_primaryinvestmentorderbatch"


def install_batch_append_only_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == "postgresql":
            cursor.execute(
                f"""
                DROP TRIGGER IF EXISTS {APPEND_ONLY_TABLE}_append_only_guard
                ON {APPEND_ONLY_TABLE};
                CREATE TRIGGER {APPEND_ONLY_TABLE}_append_only_guard
                BEFORE UPDATE OR DELETE ON {APPEND_ONLY_TABLE}
                FOR EACH ROW
                EXECUTE FUNCTION platform_core_prevent_append_only_mutation();
                """
            )
        elif vendor == "sqlite":
            cursor.execute(f"DROP TRIGGER IF EXISTS {APPEND_ONLY_TABLE}_append_only_update_guard;")
            cursor.execute(f"DROP TRIGGER IF EXISTS {APPEND_ONLY_TABLE}_append_only_delete_guard;")
            cursor.execute(
                f"""
                CREATE TRIGGER {APPEND_ONLY_TABLE}_append_only_update_guard
                BEFORE UPDATE ON {APPEND_ONLY_TABLE}
                BEGIN
                    SELECT RAISE(ABORT, 'append-only table cannot be updated');
                END;
                """
            )
            cursor.execute(
                f"""
                CREATE TRIGGER {APPEND_ONLY_TABLE}_append_only_delete_guard
                BEFORE DELETE ON {APPEND_ONLY_TABLE}
                BEGIN
                    SELECT RAISE(ABORT, 'append-only table cannot be deleted');
                END;
                """
            )


def uninstall_batch_append_only_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == "postgresql":
            cursor.execute(
                f"""
                DROP TRIGGER IF EXISTS {APPEND_ONLY_TABLE}_append_only_guard
                ON {APPEND_ONLY_TABLE};
                """
            )
        elif vendor == "sqlite":
            cursor.execute(f"DROP TRIGGER IF EXISTS {APPEND_ONLY_TABLE}_append_only_update_guard;")
            cursor.execute(f"DROP TRIGGER IF EXISTS {APPEND_ONLY_TABLE}_append_only_delete_guard;")


def backfill_currency_totals(apps, schema_editor):
    batch_model = apps.get_model("marketplace_primary", "PrimaryInvestmentOrderBatch")
    for batch in batch_model.objects.all().iterator():
        batch.currency_totals = [
            {
                "currency": str(batch.currency_id),
                "amount_minor": int(batch.total_amount_minor),
            }
        ]
        batch.save(update_fields=["currency_totals"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_alter_documentacceptanceevidence_category_and_more"),
        ("marketplace_primary", "0006_primaryinvestmentorderbatch"),
        ("platform_core", "0004_qa_dev_mode"),
    ]

    operations = [
        migrations.RunPython(
            uninstall_batch_append_only_guards,
            install_batch_append_only_guards,
        ),
        migrations.RemoveConstraint(
            model_name="primaryinvestmentorderbatch",
            name="primary_order_batch_total_positive",
        ),
        migrations.AddField(
            model_name="primaryinvestmentorderbatch",
            name="currency_totals",
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(backfill_currency_totals, noop_reverse),
        migrations.AlterField(
            model_name="primaryinvestmentorderbatch",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_investment_order_batches",
                to="platform_core.currency",
            ),
        ),
        migrations.AlterField(
            model_name="primaryinvestmentorderbatch",
            name="total_amount_minor",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="primaryinvestmentorderbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("currency__isnull", True), ("total_amount_minor__isnull", True)),
                    models.Q(("currency__isnull", False), ("total_amount_minor__gt", 0)),
                    _connector="OR",
                ),
                name="primary_order_batch_legacy_total_consistent",
            ),
        ),
        migrations.RunPython(
            install_batch_append_only_guards,
            uninstall_batch_append_only_guards,
        ),
    ]
