import type {
  AdminDashboardQueueItem,
  AdminDashboardQueues,
  AdminOperationsDashboard,
  AdminTask,
  AdminTaskEvent,
  AuditEvent,
  BorrowerEntity,
  DocumentTemplateVersion,
  KycAdminCase,
  Loan,
  AdminSecondaryMarketListingRow
} from "../api/generated/banxumApi";

function queueItem(
  overrides: Partial<AdminDashboardQueueItem> & Pick<AdminDashboardQueueItem, "kind" | "id" | "title" | "status">
): AdminDashboardQueueItem {
  return {
    priority: "normal",
    due_at: null,
    due_date: null,
    currency: "CHF",
    amount_minor: null,
    object_type: overrides.kind,
    object_id: overrides.id,
    metadata: {},
    ...overrides
  };
}

const emptyQueues: AdminDashboardQueues = {
  admin_tasks: [],
  kyc_reviews: [],
  bank_operations_pending: [],
  withdrawals_requested: [],
  forced_withdrawals_requested: [],
  balance_ageing_actions: [],
  funding_loans: [],
  servicing_due: [],
  loan_risk: [],
  secondary_listing_approvals: [],
  fx_settlement_deltas: [],
  failed_emails: [],
  reconciliation_breaks: []
};

export const adminDashboardFixture: AdminOperationsDashboard = {
  as_of: "2026-06-05T09:45:00+02:00",
  as_of_date: "2026-06-05",
  due_window_days: 7,
  queue_limit: 12,
  summary: {
    open_items: 34,
    high_priority_items: 7,
    failed_email_count: 2,
    reconciliation_break_count: 3,
    pending_withdrawal_count: 5,
    kyc_manual_review_count: 4
  },
  currency_summaries: [
    {
      currency: "CHF",
      available_balance_minor: 98422000,
      investable_available_minor: 51450000,
      withdraw_only_available_minor: 23900000,
      overdue_available_minor: 8710000,
      frozen_available_minor: 3150000,
      penalty_mode_available_minor: 2700000,
      pending_withdrawal_minor: 12150000,
      forced_withdrawal_minor: 3150000,
      pending_bank_operation_minor: 50600000,
      fx_unsettled_sold_minor: 44000000,
      fx_unsettled_bought_minor: 0,
      fx_unsettled_fee_minor: 61000
    },
    {
      currency: "EUR",
      available_balance_minor: 64180000,
      investable_available_minor: 38940000,
      withdraw_only_available_minor: 14500000,
      overdue_available_minor: 4700000,
      frozen_available_minor: 2040000,
      penalty_mode_available_minor: 0,
      pending_withdrawal_minor: 6400000,
      forced_withdrawal_minor: 2040000,
      pending_bank_operation_minor: 27800000,
      fx_unsettled_sold_minor: 0,
      fx_unsettled_bought_minor: 46190000,
      fx_unsettled_fee_minor: 47500
    }
  ],
  queues: {
    ...emptyQueues,
    admin_tasks: [
      queueItem({
        kind: "admin_task",
        id: "task-kyc-refresh-001",
        title: "Review updated KYC evidence retention checklist",
        status: "open",
        priority: "high",
        due_at: "2026-06-05T13:00:00+02:00",
        object_type: "kyc_case",
        object_id: "kyc-case-483",
        metadata: { owner: "Compliance", sla_hours_remaining: 3 }
      }),
      queueItem({
        kind: "admin_task",
        id: "task-bank-ref-002",
        title: "Resolve unmatched CHF lender deposit reference",
        status: "open",
        priority: "urgent",
        due_at: "2026-06-05T11:30:00+02:00",
        amount_minor: 2500000,
        object_type: "bank_operation",
        object_id: "bank-op-774",
        metadata: { sender_name: "A. Keller", reference_seen: "BX-81??" }
      })
    ],
    kyc_reviews: [
      queueItem({
        kind: "kyc_review",
        id: "kyc-case-483",
        title: "PEP flag requires Garanta AML officer decision",
        status: "manual_review",
        priority: "urgent",
        due_at: "2026-06-05T12:00:00+02:00",
        object_type: "kyc_case",
        object_id: "kyc-case-483",
        metadata: { provider: "Didit", flags: ["pep_hit"], country: "CH" }
      }),
      queueItem({
        kind: "kyc_review",
        id: "kyc-case-501",
        title: "Adverse media flag awaiting compliance note",
        status: "manual_review",
        priority: "high",
        due_at: "2026-06-06T10:00:00+02:00",
        object_type: "kyc_case",
        object_id: "kyc-case-501",
        metadata: { provider: "Didit", flags: ["adverse_media_hit"], country: "DE" }
      })
    ],
    bank_operations_pending: [
      queueItem({
        kind: "bank_operation",
        id: "bank-op-774",
        title: "Unmatched lender deposit needs reference review",
        status: "pending_review",
        priority: "urgent",
        due_at: "2026-06-05T10:30:00+02:00",
        currency: "CHF",
        amount_minor: 2500000,
        object_type: "bank_operation",
        object_id: "bank-op-774",
        metadata: { value_date: "2026-06-05", sender_iban: "CH93 **** 0173" }
      })
    ],
    // Withdrawal queue items mirror the dashboard API exactly:
    // kind="withdrawal_request", object_type="InvestorWithdrawalRequest".
    withdrawals_requested: [
      queueItem({
        kind: "withdrawal_request",
        id: "wd-1002",
        title: "Investor withdrawal awaiting bank execution",
        status: "requested",
        priority: "normal",
        due_date: "2026-06-06",
        currency: "EUR",
        amount_minor: 6400000,
        object_type: "InvestorWithdrawalRequest",
        object_id: "wd-1002",
        metadata: { investor_user_id: "inv-3021", is_forced: false }
      })
    ],
    forced_withdrawals_requested: [
      queueItem({
        kind: "withdrawal_request",
        id: "wd-forced-301",
        title: "Investor withdrawal awaiting bank execution",
        status: "requested",
        priority: "high",
        due_date: "2026-06-05",
        currency: "CHF",
        amount_minor: 3150000,
        object_type: "InvestorWithdrawalRequest",
        object_id: "wd-forced-301",
        metadata: { investor_user_id: "inv-2210", is_forced: true }
      })
    ],
    balance_ageing_actions: [
      queueItem({
        kind: "balance_ageing",
        id: "lot-883",
        title: "Lot enters withdraw-only window today",
        status: "withdraw_only",
        priority: "normal",
        due_date: "2026-06-05",
        currency: "CHF",
        amount_minor: 9800000,
        object_type: "investor_balance_lot",
        object_id: "lot-883",
        metadata: { investor_reference: "INV-2204", investment_deadline: "2026-06-05" }
      }),
      queueItem({
        kind: "balance_ageing",
        id: "lot-884",
        title: "No verified IBAN for day-60 lot",
        status: "penalty_mode",
        priority: "urgent",
        due_date: "2026-06-05",
        currency: "CHF",
        amount_minor: 2700000,
        object_type: "investor_balance_lot",
        object_id: "lot-884",
        metadata: { investor_reference: "INV-1458", action: "freeze_until_iban" }
      })
    ],
    funding_loans: [
      queueItem({
        kind: "funding_loan",
        id: "loan-zug-park-ii",
        title: "Zug Park II closes in 2 days with committed funds",
        status: "published",
        priority: "high",
        due_date: "2026-06-07",
        currency: "CHF",
        amount_minor: 84000000,
        object_type: "loan",
        object_id: "loan-zug-park-ii",
        metadata: { committed_percent: 92, pending_orders: 6 }
      })
    ],
    servicing_due: [
      queueItem({
        kind: "servicing_due",
        id: "installment-771",
        title: "Borrower repayment due in servicing window",
        status: "due",
        priority: "normal",
        due_date: "2026-06-08",
        currency: "CHF",
        amount_minor: 1845000,
        object_type: "loan_installment",
        object_id: "installment-771",
        metadata: { loan_reference: "L-2026-018", borrower: "Helvetic Wohnbau AG" }
      })
    ],
    loan_risk: [
      queueItem({
        kind: "loan_risk",
        id: "loan-basel-riverside",
        title: "Loan moved to late status, public note recommended",
        status: "late",
        priority: "high",
        due_date: "2026-06-05",
        currency: "CHF",
        amount_minor: 42000000,
        object_type: "loan",
        object_id: "loan-basel-riverside",
        metadata: { days_past_due: 7, last_payment_date: "2026-05-12" }
      }),
      queueItem({
        kind: "loan_risk",
        id: "loan-ticino-recovery",
        title: "Defaulted loan recovery note is stale",
        status: "defaulted",
        priority: "urgent",
        due_date: "2026-06-05",
        currency: "EUR",
        amount_minor: 12900000,
        object_type: "loan",
        object_id: "loan-ticino-recovery",
        metadata: { days_past_due: 24, public_note_age_days: 12 }
      })
    ],
    secondary_listing_approvals: [
      queueItem({
        kind: "secondary_listing",
        id: "sm-listing-711",
        title: "Non-standard secondary listing awaiting risk disclosure approval",
        status: "approval_requested",
        priority: "high",
        due_at: "2026-06-05T15:00:00+02:00",
        currency: "CHF",
        amount_minor: 1120000,
        object_type: "secondary_listing",
        object_id: "sm-listing-711",
        metadata: { loan_status: "late", days_past_due: 7 }
      })
    ],
    fx_settlement_deltas: [
      queueItem({
        kind: "fx_settlement",
        id: "fx-delta-2026-06-05",
        title: "CHF/EUR external FX settlement delta to declare",
        status: "unsettled",
        priority: "high",
        due_date: "2026-06-05",
        currency: "CHF",
        amount_minor: 44000000,
        object_type: "fx_settlement_window",
        object_id: "2026-06-05:CHF-EUR",
        metadata: { pair: "CHF/EUR", expected_sold: "CHF 440,000.00", expected_bought: "EUR 461,900.00" }
      })
    ],
    failed_emails: [
      queueItem({
        kind: "failed_email",
        id: "outbox-771",
        title: "Installment notification email dead-lettered",
        status: "dead_letter",
        priority: "normal",
        due_at: "2026-06-05T09:20:00+02:00",
        object_type: "outbox_message",
        object_id: "outbox-771",
        metadata: { topic: "email.installment_received", attempts: 8 }
      })
    ],
    reconciliation_breaks: [
      queueItem({
        kind: "reconciliation_break",
        id: "recon-chf-2026-06-05",
        title: "CHF reconciliation difference and sign anomaly",
        status: "break",
        priority: "urgent",
        due_date: "2026-06-05",
        currency: "CHF",
        amount_minor: 72000,
        object_type: "reconciliation_snapshot",
        object_id: "recon-chf-2026-06-05",
        metadata: {
          reconciliation_difference_minor: 72000,
          account_sign_anomalies: 1,
          investor_balance_integrity_breaks: 0
        }
      }),
      queueItem({
        kind: "reconciliation_break",
        id: "recon-eur-2026-06-05",
        title: "EUR investor liability mismatch in one account",
        status: "integrity_break",
        priority: "urgent",
        due_date: "2026-06-05",
        currency: "EUR",
        amount_minor: 0,
        object_type: "reconciliation_snapshot",
        object_id: "recon-eur-2026-06-05",
        metadata: {
          reconciliation_difference_minor: 0,
          account_sign_anomalies: 0,
          investor_balance_integrity_breaks: 1
        }
      })
    ]
  }
};

export const adminTasksFixture: AdminTask[] = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    task_type: "payment_reconciliation",
    title: "Resolve unmatched CHF lender deposit reference",
    priority: "urgent",
    status: "open",
    assigned_admin_id: null,
    created_by_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    due_at: "2026-06-05T11:30:00+02:00",
    notes:
      "Incoming CHF 25,000.00 deposit contains an incomplete lender reference. Check sender name, sender IBAN and bank description before crediting any investor balance.",
    related_object_type: "bank_operation",
    related_object_id: "bank-op-774",
    completed_at: null,
    completion_note: "",
    is_terminal: false,
    created_at: "2026-06-05T09:15:00+02:00",
    updated_at: "2026-06-05T09:15:00+02:00"
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    task_type: "kyc_manual_review",
    title: "PEP flag requires Garanta AML officer decision",
    priority: "urgent",
    status: "in_progress",
    assigned_admin_id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    created_by_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    due_at: "2026-06-05T12:00:00+02:00",
    notes:
      "Didit routed this person to manual review. Review provider report, local evidence metadata and AML officer note before approving or declining.",
    related_object_type: "kyc_case",
    related_object_id: "kyc-case-483",
    completed_at: null,
    completion_note: "",
    is_terminal: false,
    created_at: "2026-06-05T08:42:00+02:00",
    updated_at: "2026-06-05T09:05:00+02:00"
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    task_type: "fx_settlement",
    title: "Declare CHF/EUR external FX settlement",
    priority: "high",
    status: "waiting",
    assigned_admin_id: null,
    created_by_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    due_at: "2026-06-05T17:00:00+02:00",
    notes:
      "Use the end-of-day bank report to declare the actual CHF sold and EUR bought. The platform will leave any realized surplus/deficit in FX clearing for reporting.",
    related_object_type: "fx_settlement_window",
    related_object_id: "2026-06-05:CHF-EUR",
    completed_at: null,
    completion_note: "",
    is_terminal: false,
    created_at: "2026-06-05T10:00:00+02:00",
    updated_at: "2026-06-05T10:00:00+02:00"
  },
  {
    id: "44444444-4444-4444-8444-444444444444",
    task_type: "document_review",
    title: "Review revised primary-market risk acknowledgement template",
    priority: "normal",
    status: "open",
    assigned_admin_id: null,
    created_by_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    due_at: "2026-06-07T15:00:00+02:00",
    notes:
      "Compare template variables and checkbox labels with the latest advisor text before publication.",
    related_object_type: "document_template",
    related_object_id: "primary-market-investment:v3",
    completed_at: null,
    completion_note: "",
    is_terminal: false,
    created_at: "2026-06-05T10:30:00+02:00",
    updated_at: "2026-06-05T10:30:00+02:00"
  },
  {
    id: "55555555-5555-4555-8555-555555555555",
    task_type: "email_delivery_failure",
    title: "Dead-lettered installment notification",
    priority: "normal",
    status: "resolved",
    assigned_admin_id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    created_by_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    due_at: "2026-06-05T10:00:00+02:00",
    notes: "SendGrid rejected an installment email after retry exhaustion.",
    related_object_type: "outbox_message",
    related_object_id: "outbox-771",
    completed_at: "2026-06-05T10:21:00+02:00",
    completion_note: "Delivery issue recorded. Investor notification queued for manual support follow-up.",
    is_terminal: true,
    created_at: "2026-06-05T09:20:00+02:00",
    updated_at: "2026-06-05T10:21:00+02:00"
  }
];

export const adminTaskEventsFixture: Record<string, AdminTaskEvent[]> = {
  "11111111-1111-4111-8111-111111111111": [
    {
      id: "task-event-111-created",
      task_id: "11111111-1111-4111-8111-111111111111",
      event_type: "created",
      actor_user_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      actor_account_type: "admin",
      previous_status: "",
      new_status: "open",
      note: "Task created from pending bank operation queue.",
      metadata: { source: "dashboard", related_object_type: "bank_operation" },
      occurred_at: "2026-06-05T09:15:00+02:00"
    }
  ],
  "22222222-2222-4222-8222-222222222222": [
    {
      id: "task-event-222-created",
      task_id: "22222222-2222-4222-8222-222222222222",
      event_type: "created",
      actor_user_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      actor_account_type: "admin",
      previous_status: "",
      new_status: "open",
      note: "Manual review task opened from Didit webhook status mapping.",
      metadata: { provider: "Didit", flags: ["pep_hit"] },
      occurred_at: "2026-06-05T08:42:00+02:00"
    },
    {
      id: "task-event-222-status",
      task_id: "22222222-2222-4222-8222-222222222222",
      event_type: "status_changed",
      actor_user_id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
      actor_account_type: "admin",
      previous_status: "open",
      new_status: "in_progress",
      note: "Compliance review started.",
      metadata: {},
      occurred_at: "2026-06-05T09:05:00+02:00"
    }
  ],
  "33333333-3333-4333-8333-333333333333": [
    {
      id: "task-event-333-created",
      task_id: "33333333-3333-4333-8333-333333333333",
      event_type: "created",
      actor_user_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      actor_account_type: "admin",
      previous_status: "",
      new_status: "waiting",
      note: "Waiting for end-of-day bank FX execution report.",
      metadata: { pair: "CHF/EUR" },
      occurred_at: "2026-06-05T10:00:00+02:00"
    }
  ],
  "44444444-4444-4444-8444-444444444444": [
    {
      id: "task-event-444-created",
      task_id: "44444444-4444-4444-8444-444444444444",
      event_type: "created",
      actor_user_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      actor_account_type: "superadmin",
      previous_status: "",
      new_status: "open",
      note: "Document review requested before publication.",
      metadata: { template_category: "primary_market_investment" },
      occurred_at: "2026-06-05T10:30:00+02:00"
    }
  ],
  "55555555-5555-4555-8555-555555555555": [
    {
      id: "task-event-555-created",
      task_id: "55555555-5555-4555-8555-555555555555",
      event_type: "created",
      actor_user_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      actor_account_type: "admin",
      previous_status: "",
      new_status: "open",
      note: "Task created from dead-lettered email outbox message.",
      metadata: { topic: "email.installment_received", attempts: 8 },
      occurred_at: "2026-06-05T09:20:00+02:00"
    },
    {
      id: "task-event-555-resolved",
      task_id: "55555555-5555-4555-8555-555555555555",
      event_type: "status_changed",
      actor_user_id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
      actor_account_type: "admin",
      previous_status: "open",
      new_status: "resolved",
      note: "Delivery issue recorded. Investor notification queued for manual support follow-up.",
      metadata: {},
      occurred_at: "2026-06-05T10:21:00+02:00"
    }
  ]
};

export const kycManualReviewFixture: KycAdminCase[] = [
  {
    id: "kyc-case-483",
    subject_type: "natural_person",
    subject_reference: "INV-2048",
    user_id: "00000000-0000-4000-8000-000000002048",
    user_full_name: "Lukas Brunner",
    user_email: "lukas.brunner@example.ch",
    investor_reference: "L7K3M9P2Q",
    provider: "Didit",
    provider_environment: "sandbox",
    workflow_id: "didit-workflow-ch-person",
    status: "pep_hit",
    manual_review_required: true,
    blocking_reason: "PEP match requires AML officer decision before account activation.",
    risk_classification: "high",
    detected_flags: ["pep_hit", "high_risk"],
    provider_session_id: "didit-sess-483",
    provider_verification_id: "didit-ver-483",
    provider_report_id: "didit-report-483",
    aml_screening_id: "didit-aml-483",
    provider_subject_id: "didit-subject-483",
    decision_at: null,
    created_at: "2026-06-05T08:42:00+02:00",
    updated_at: "2026-06-05T09:05:00+02:00"
  },
  {
    id: "kyc-case-501",
    subject_type: "natural_person",
    subject_reference: "INV-2177",
    user_id: "00000000-0000-4000-8000-000000002177",
    user_full_name: "Sofia Meier",
    user_email: "sofia.meier@example.eu",
    investor_reference: "L4N8RQ5T2",
    provider: "Didit",
    provider_environment: "sandbox",
    workflow_id: "didit-workflow-eu-person",
    status: "adverse_media_hit",
    manual_review_required: true,
    blocking_reason: "Adverse media match routed to manual review.",
    risk_classification: "medium",
    detected_flags: ["adverse_media_hit"],
    provider_session_id: "didit-sess-501",
    provider_verification_id: "didit-ver-501",
    provider_report_id: "didit-report-501",
    aml_screening_id: "didit-aml-501",
    provider_subject_id: "didit-subject-501",
    decision_at: null,
    created_at: "2026-06-05T09:20:00+02:00",
    updated_at: "2026-06-05T09:55:00+02:00"
  },
  ...(
    [
      ["Amélie Roth", "amelie.roth@example.ch", "LQ2W9K7M4", "manual_review", "medium", ["document_review"]],
      ["Marco Bianchi", "marco.bianchi@example.it", "L8H3J5N1P", "high_risk", "high", ["high_risk"]],
      ["Élodie Dubois", "elodie.dubois@example.fr", "LT6R2V9X3", "pep_hit", "high", ["pep_hit"]],
      ["Jonas Keller", "jonas.keller@example.ch", "LK9M4P7Q2", "manual_review", "low", ["document_review"]],
      ["Petra Novák", "petra.novak@example.cz", "LB3N8K5R1", "adverse_media_hit", "medium", ["adverse_media_hit"]],
      ["Andreas Huber", "andreas.huber@example.at", "LW7T2M9K4", "high_risk", "high", ["high_risk", "pep_hit"]],
      ["Clara Lefevre", "clara.lefevre@example.fr", "LP5Q8R3N7", "manual_review", "medium", ["document_review"]],
      ["Tomáš Horák", "tomas.horak@example.cz", "LM2K9P4T6", "manual_review", "low", ["address_review"]],
      ["Giulia Conti", "giulia.conti@example.it", "LR8N3K7M2", "pep_hit", "high", ["pep_hit"]],
      ["Niklas Vogel", "niklas.vogel@example.de", "LH4T7Q2N9", "adverse_media_hit", "medium", ["adverse_media_hit"]]
    ] as const
  ).map(([name, email, reference, status, risk, flags], index) => ({
    id: `kyc-case-${600 + index}`,
    subject_type: "natural_person",
    subject_reference: `INV-${3000 + index}`,
    user_id: `00000000-0000-4000-8000-0000000030${(index + 10).toString()}`,
    user_full_name: name,
    user_email: email,
    investor_reference: reference,
    provider: "Didit",
    provider_environment: "sandbox",
    workflow_id: "didit-workflow-eu-person",
    status,
    manual_review_required: true,
    blocking_reason: "Routed to Garanta manual review for an AML officer decision.",
    risk_classification: risk,
    detected_flags: [...flags],
    provider_session_id: `didit-sess-${600 + index}`,
    provider_verification_id: `didit-ver-${600 + index}`,
    provider_report_id: `didit-report-${600 + index}`,
    aml_screening_id: `didit-aml-${600 + index}`,
    provider_subject_id: `didit-subject-${600 + index}`,
    decision_at: null,
    created_at: "2026-06-05T08:00:00+02:00",
    updated_at: `2026-06-04T0${index % 9}:30:00+02:00`
  }))
];

export const borrowersFixture: BorrowerEntity[] = [
  {
    id: "borrower-helvetic-wohnbau",
    legal_name: "Helvetic Wohnbau AG",
    year_founded: 2011,
    entity_type: "swiss_company",
    kyb_status: "approved",
    compliance_hold: false,
    can_transact: true,
    country: "CH",
    registration_number: "CHE-123.456.789",
    business_classification: "Residential real-estate development",
    business_classification_public: true,
    registered_address: "Zugerstrasse 18, 6300 Zug",
    registered_address_public: true,
    operating_address: "Zugerstrasse 18, 6300 Zug",
    contact_info: "Investor contact through Garanta investor relations.",
    contact_info_public: true,
    industry_activity: "Residential real-estate development",
    ownership_structure: "Privately held Swiss company",
    beneficial_owners: [{ name: "Redacted in preview", share_percent: 100 }],
    directors_officers: [{ name: "Preview Director", role: "Director" }],
    authorized_signatories: [{ name: "Preview Signatory", authority: "single signature" }],
    bank_account_details: { iban_status: "verified_off_platform" },
    kyb_aml_observations: "No sanctions or PEP indicators in preview evidence.",
    financial_risk: "Medium leverage; collateral-backed exposure.",
    financials_currency: "CHF",
    assets_minor: 1820000000,
    liabilities_minor: 960000000,
    revenue_last_year_minor: 440000000,
    profit_last_year_minor: 31000000,
    created_by_admin_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    updated_by_admin_id: null,
    created_at: "2026-06-01T10:00:00+02:00",
    updated_at: "2026-06-04T16:20:00+02:00"
  },
  {
    id: "borrower-ticino-projects",
    legal_name: "Ticino Projects SA",
    year_founded: 2018,
    entity_type: "special_purpose_vehicle",
    kyb_status: "manual_review",
    compliance_hold: true,
    can_transact: false,
    country: "CH",
    registration_number: "CHE-987.654.321",
    business_classification: "Real-estate backed project finance",
    business_classification_public: false,
    registered_address: "Via Cantonale 7, 6900 Lugano",
    registered_address_public: false,
    operating_address: "",
    contact_info: "",
    contact_info_public: false,
    industry_activity: "Real-estate backed project finance",
    ownership_structure: "",
    beneficial_owners: [],
    directors_officers: [],
    authorized_signatories: [],
    bank_account_details: {},
    kyb_aml_observations: "Manual-review preview borrower.",
    financial_risk: "Financials pending; compliance hold active.",
    financials_currency: "CHF",
    assets_minor: null,
    liabilities_minor: null,
    revenue_last_year_minor: null,
    profit_last_year_minor: null,
    created_by_admin_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    updated_by_admin_id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    created_at: "2026-06-02T11:40:00+02:00",
    updated_at: "2026-06-05T08:30:00+02:00"
  }
];

const directAdminLoanFields = (yieldBps: number, principalMinor: number) => ({
  product_type: "direct",
  originator_id: null,
  originator_name: null,
  yield_bps: yieldBps,
  opportunity_status: null,
  minimum_investment_minor: null,
  current_outstanding_principal_minor: principalMinor,
  unsold_principal_minor: null,
  maturity_date: null,
  originator_schedule_revision: null
});

export const loansFixture: Loan[] = [
  {
    ...directAdminLoanFields(950, 120000000),
    id: "loan-zug-park-ii",
    borrower_id: "borrower-helvetic-wohnbau",
    borrower_name: "Helvetic Wohnbau AG",
    status: "published",
    title: "Zug Park II bridge facility",
    investor_summary: "Real-estate backed bridge facility secured by a first-ranking pledge over the Zug Park II project.",
    purpose: "bridge_financing",
    purpose_description: "Bridge financing while the borrower completes senior bank refinancing.",
    is_refinancing: false,
    original_principal_minor: 120000000,
    original_interest_rate_bps: null,
    original_term_months: null,
    original_repayment_type: null,
    original_interest_only_months: null,
    original_loan_start_date: null,
    principal_minor: 120000000,
    currency: "CHF",
    interest_rate_bps: 950,
    term_months: 12,
    repayment_type: "equal_installments",
    interest_only_months: 0,
    loan_start_date: "2026-06-30",
    funding_deadline: "2026-06-30",
    first_payment_date: "2026-07-31",
    pre_publication_paid_installments: [],
    collateral_type: "real_estate",
    collateral_value_minor: 184000000,
    collateral_description: "Independent valuation of the pledged real-estate collateral.",
    risk_rating: "BBB",
    borrower_success_fee_bps: 250,
    lender_payment_fee_minor: 0,
    default_penalty_interest_bps: 0,
    recovery_fee_bps: 0,
    recovery_waterfall_version: "v1",
    schedule_version: 1,
    total_scheduled_principal_minor: 120000000,
    total_scheduled_interest_minor: 6264000,
    committed_principal_minor: 84000000,
    ltv_bps: 6522,
    ltv_warnings: [],
    published_at: "2026-06-03T10:30:00+02:00",
    created_by_admin_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    updated_by_admin_id: null,
    created_at: "2026-06-01T15:00:00+02:00",
    updated_at: "2026-06-03T10:30:00+02:00"
  },
  {
    ...directAdminLoanFields(1025, 42000000),
    id: "loan-basel-riverside",
    borrower_id: "borrower-helvetic-wohnbau",
    borrower_name: "Helvetic Wohnbau AG",
    status: "late",
    title: "Basel Riverside refurbishment",
    investor_summary: "Refurbishment facility backed by mixed real-estate collateral.",
    purpose: "development",
    purpose_description: "Refurbishment and working-capital bridge for a residential development.",
    is_refinancing: false,
    original_principal_minor: 42000000,
    original_interest_rate_bps: null,
    original_term_months: null,
    original_repayment_type: null,
    original_interest_only_months: null,
    original_loan_start_date: null,
    principal_minor: 42000000,
    currency: "CHF",
    interest_rate_bps: 1025,
    term_months: 10,
    repayment_type: "bullet_periodic_interest",
    interest_only_months: 0,
    loan_start_date: "2026-04-15",
    funding_deadline: "2026-04-15",
    first_payment_date: "2026-05-15",
    pre_publication_paid_installments: [],
    collateral_type: "mixed_collateral",
    collateral_value_minor: 69000000,
    collateral_description: "Real-estate pledge plus corporate guarantee.",
    risk_rating: "BB+",
    borrower_success_fee_bps: 300,
    lender_payment_fee_minor: 0,
    default_penalty_interest_bps: 0,
    recovery_fee_bps: 0,
    recovery_waterfall_version: "v1",
    schedule_version: 1,
    total_scheduled_principal_minor: 42000000,
    total_scheduled_interest_minor: 3587500,
    committed_principal_minor: 42000000,
    ltv_bps: 6087,
    ltv_warnings: [],
    published_at: "2026-03-20T09:00:00+01:00",
    created_by_admin_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    updated_by_admin_id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    created_at: "2026-03-18T12:00:00+01:00",
    updated_at: "2026-06-05T09:00:00+02:00"
  }
  ,{
    ...directAdminLoanFields(1150, 35000000),
    id: "loan-luzern-quartier",
    borrower_id: "borrower-ticino-immobilien",
    borrower_name: "Ticino Immobilien AG",
    status: "defaulted",
    title: "Luzern Quartier renovation",
    investor_summary: "Renovation loan for a mixed-use property in Luzern; currently in recovery.",
    purpose: "development",
    purpose_description: "Renovation of a mixed-use building.",
    is_refinancing: false,
    original_principal_minor: 35000000,
    original_interest_rate_bps: null,
    original_term_months: null,
    original_repayment_type: null,
    original_interest_only_months: null,
    original_loan_start_date: null,
    principal_minor: 35000000,
    currency: "CHF",
    interest_rate_bps: 1150,
    term_months: 18,
    repayment_type: "equal_installments",
    interest_only_months: 0,
    loan_start_date: "2026-02-28",
    funding_deadline: "2026-02-28",
    first_payment_date: "2026-03-31",
    pre_publication_paid_installments: [],
    collateral_type: "real_estate",
    collateral_value_minor: 52000000,
    collateral_description: "Second-ranking pledge over the renovated property.",
    risk_rating: "B",
    borrower_success_fee_bps: 300,
    lender_payment_fee_minor: 0,
    default_penalty_interest_bps: 600,
    recovery_fee_bps: 500,
    recovery_waterfall_version: "v1",
    schedule_version: 1,
    total_scheduled_principal_minor: 35000000,
    total_scheduled_interest_minor: 4200000,
    committed_principal_minor: 35000000,
    ltv_bps: 6731,
    ltv_warnings: [],
    published_at: "2026-02-01T09:00:00+01:00",
    created_by_admin_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    updated_by_admin_id: null,
    created_at: "2026-01-28T15:00:00+01:00",
    updated_at: "2026-06-20T10:00:00+02:00"
  },
  {
    ...directAdminLoanFields(950, 34000000),
    id: "loan-seefeld-refi",
    borrower_id: "borrower-helvetic-wohnbau",
    borrower_name: "Helvetic Wohnbau AG",
    status: "draft",
    title: "Seefeld refinancing takeover",
    investor_summary:
      "Refinancing of an ongoing amortizing facility. BANXUM lenders fund part of the remaining outstanding principal of the original contract.",
    purpose: "refinancing",
    purpose_description: "Takeover of an ongoing bank facility with the original amortization contract continuing.",
    is_refinancing: true,
    original_principal_minor: 50000000,
    original_interest_rate_bps: 900,
    original_term_months: 24,
    original_repayment_type: "amortizing_principal_interest",
    original_interest_only_months: 0,
    original_loan_start_date: "2025-10-31",
    principal_minor: 34000000,
    currency: "CHF",
    interest_rate_bps: 950,
    term_months: 16,
    repayment_type: "equal_installments",
    interest_only_months: 0,
    loan_start_date: "2026-07-31",
    funding_deadline: "2026-07-25",
    first_payment_date: "2026-08-31",
    pre_publication_paid_installments: [1, 2, 3, 4, 5, 6, 7, 8],
    collateral_type: "real_estate",
    collateral_value_minor: 78000000,
    collateral_description: "First-ranking pledge over the Seefeld property.",
    risk_rating: "BBB",
    borrower_success_fee_bps: 250,
    lender_payment_fee_minor: 0,
    default_penalty_interest_bps: 0,
    recovery_fee_bps: 0,
    recovery_waterfall_version: "v1",
    schedule_version: 1,
    total_scheduled_principal_minor: 34000000,
    total_scheduled_interest_minor: 2427000,
    committed_principal_minor: 0,
    ltv_bps: 4359,
    ltv_warnings: [],
    published_at: null,
    created_by_admin_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    updated_by_admin_id: null,
    created_at: "2026-07-01T09:00:00+02:00",
    updated_at: "2026-07-06T09:00:00+02:00"
  }
];

export const documentVersionsFixture: DocumentTemplateVersion[] = [
  {
    id: "doc-version-registration-v1",
    template: {
      id: "doc-template-registration",
      category: "registration",
      template_key: "registration-default",
      language: "en",
      name: "Registration terms",
      description: "Registration-time platform terms and privacy acknowledgement.",
      current_published_version_id: "doc-version-registration-v1",
      created_by_superadmin_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      updated_by_superadmin_id: null,
      created_at: "2026-06-01T09:30:00+02:00",
      updated_at: "2026-06-01T10:00:00+02:00"
    },
    version_number: 1,
    status: "published",
    title: "BANXUM Registration Terms",
    body: "Placeholder registration terms for preview. Advisor-approved text will be uploaded before launch.",
    checkbox_labels: ["I accept the BANXUM registration terms.", "I confirm the information I provide is accurate."],
    variable_schema: { variables: ["platform_name", "operator_name", "support_email"] },
    content_hash: "sha256-preview-registration",
    created_by_superadmin_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    source_version_id: null,
    published_at: "2026-06-01T10:00:00+02:00",
    legal_review_reference: "preview-legal-ref",
    metadata: { preview: true },
    created_at: "2026-06-01T09:30:00+02:00",
    updated_at: "2026-06-01T10:00:00+02:00"
  },
  {
    id: "doc-version-primary-v3",
    template: {
      id: "doc-template-primary",
      category: "primary_market_investment",
      template_key: "primary-market-default",
      language: "en",
      name: "Primary-market investment acknowledgement",
      description: "Clickwrap text for primary investment order submission.",
      current_published_version_id: "doc-version-primary-v2",
      created_by_superadmin_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      updated_by_superadmin_id: null,
      created_at: "2026-05-01T10:00:00+02:00",
      updated_at: "2026-06-05T10:30:00+02:00"
    },
    version_number: 3,
    status: "draft",
    title: "Primary-Market Investment Acknowledgement",
    body: "Draft placeholder risk acknowledgement for primary-market investments.",
    checkbox_labels: ["I understand this is not a bank deposit.", "I accept the loan assignment terms."],
    variable_schema: { variables: ["loan.title", "loan.currency", "loan.principal_minor"] },
    content_hash: "sha256-preview-primary-v3",
    created_by_superadmin_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    source_version_id: "doc-version-primary-v2",
    published_at: null,
    legal_review_reference: "",
    metadata: { preview: true },
    created_at: "2026-06-05T10:30:00+02:00",
    updated_at: "2026-06-05T10:30:00+02:00"
  }
];

export const auditEventsFixture: AuditEvent[] = [
  {
    id: "audit-001",
    occurred_at: "2026-06-05T10:21:00+02:00",
    actor_type: "admin",
    actor_id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    action: "admin_task.status_changed",
    target_type: "admin_task",
    target_id: "55555555-5555-4555-8555-555555555555",
    request_id: "req-preview-001",
    metadata: { previous_status: "open", new_status: "resolved" }
  },
  {
    id: "audit-002",
    occurred_at: "2026-06-05T09:05:00+02:00",
    actor_type: "admin",
    actor_id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    action: "kyc.manual_review_started",
    target_type: "kyc_case",
    target_id: "kyc-case-483",
    request_id: "req-preview-002",
    metadata: { provider: "Didit", flags: ["pep_hit"] }
  }
];

export const adminSecondaryListingsFixture: AdminSecondaryMarketListingRow[] = [
  {
    "holding_id": "holding-sm-1",
    "seller_user_id": "0d9f2a71-1111-4a52-9d10-visitor00001",
    "publication_type": "admin_approved",
    "currency": "CHF",
    "accrued_interest_minor": 15130,
    "accrued_interest_from_date": "2026-06-01",
    "accrued_interest_to_date": "2026-07-04",
    "maker_fee_bps": 25,
    "taker_fee_bps": 75,
    "minimum_maker_fee_minor": 0,
    "minimum_taker_fee_minor": 0,
    "risk_acknowledgement_required": true,
    "document_acceptance_id": "acc-sm-1",
    "public_disclosure_note": "",
    "listed_at": null,
    "approved_by_admin_id": null,
    "approved_at": null,
    "approval_reason": "",
    "rejected_by_admin_id": null,
    "rejected_at": null,
    "rejection_reason": "",
    "removed_by_admin_id": null,
    "removed_at": null,
    "removal_reason": "",
    "cancelled_at": null,
    "cancellation_reason": "",
    "cancelled_by_user_id": null,
    "created_by_user_id": "0d9f2a71-1111-4a52-9d10-visitor00001",
    "updated_at": "2026-07-03T09:12:00+02:00",
    "last_payment_date": "2026-05-31",
    "id": "sm-listing-711",
    "loan_id": "loan-basel-riverside",
    "loan_title": "Basel Riverside refurbishment",
    "loan_status": "late",
    "loan_status_at_listing": "late",
    "status": "approval_requested",
    "seller_email": "lukas.brunner@example.ch",
    "seller_full_name": "Lukas Brunner",
    "current_principal_minor": 1800000,
    "price_bps": 9000,
    "transfer_price_minor": 1620000,
    "discount_premium_bps": -1000,
    "days_past_due": 9,
    "maker_fee_minor": 4050,
    "taker_fee_minor": 12150,
    "seller_net_proceeds_minor": 1631080,
    "buyer_total_cost_minor": 1647280,
    "created_at": "2026-07-03T09:12:00+02:00"
  },
  {
    "holding_id": "holding-sm-1",
    "seller_user_id": "0d9f2a71-1111-4a52-9d10-visitor00001",
    "publication_type": "automatic",
    "currency": "CHF",
    "accrued_interest_minor": 15130,
    "accrued_interest_from_date": "2026-06-01",
    "accrued_interest_to_date": "2026-07-04",
    "maker_fee_bps": 25,
    "taker_fee_bps": 75,
    "minimum_maker_fee_minor": 0,
    "minimum_taker_fee_minor": 0,
    "risk_acknowledgement_required": false,
    "document_acceptance_id": "acc-sm-1",
    "public_disclosure_note": "",
    "listed_at": "2026-07-01T11:20:00+02:00",
    "approved_by_admin_id": null,
    "approved_at": null,
    "approval_reason": "",
    "rejected_by_admin_id": null,
    "rejected_at": null,
    "rejection_reason": "",
    "removed_by_admin_id": null,
    "removed_at": null,
    "removal_reason": "",
    "cancelled_at": null,
    "cancellation_reason": "",
    "cancelled_by_user_id": null,
    "created_by_user_id": "0d9f2a71-1111-4a52-9d10-visitor00001",
    "updated_at": "2026-07-03T09:12:00+02:00",
    "last_payment_date": "2026-05-31",
    "id": "sm-listing-698",
    "loan_id": "loan-zug-park-ii",
    "loan_title": "Zug Park II bridge facility",
    "loan_status": "active",
    "loan_status_at_listing": "active",
    "status": "active",
    "seller_email": "marie.dupont@example.fr",
    "seller_full_name": "Marie Dupont",
    "current_principal_minor": 4602088,
    "price_bps": 10200,
    "transfer_price_minor": 4694130,
    "discount_premium_bps": 200,
    "days_past_due": 0,
    "maker_fee_minor": 11735,
    "taker_fee_minor": 35206,
    "seller_net_proceeds_minor": 4697525,
    "buyer_total_cost_minor": 4744466,
    "created_at": "2026-07-01T11:20:00+02:00"
  },
  {
    "holding_id": "holding-sm-1",
    "seller_user_id": "0d9f2a71-1111-4a52-9d10-visitor00001",
    "publication_type": "automatic",
    "currency": "CHF",
    "accrued_interest_minor": 15130,
    "accrued_interest_from_date": "2026-06-01",
    "accrued_interest_to_date": "2026-07-04",
    "maker_fee_bps": 25,
    "taker_fee_bps": 75,
    "minimum_maker_fee_minor": 0,
    "minimum_taker_fee_minor": 0,
    "risk_acknowledgement_required": false,
    "document_acceptance_id": "acc-sm-1",
    "public_disclosure_note": "",
    "listed_at": "2026-06-24T16:05:00+02:00",
    "approved_by_admin_id": null,
    "approved_at": null,
    "approval_reason": "",
    "rejected_by_admin_id": null,
    "rejected_at": null,
    "rejection_reason": "",
    "removed_by_admin_id": null,
    "removed_at": null,
    "removal_reason": "",
    "cancelled_at": null,
    "cancellation_reason": "",
    "cancelled_by_user_id": null,
    "created_by_user_id": "0d9f2a71-1111-4a52-9d10-visitor00001",
    "updated_at": "2026-07-03T09:12:00+02:00",
    "last_payment_date": "2026-05-31",
    "id": "sm-listing-684",
    "loan_id": "loan-zug-park-ii",
    "loan_title": "Zug Park II bridge facility",
    "loan_status": "active",
    "loan_status_at_listing": "active",
    "status": "sold",
    "seller_email": "jonas.keller@example.ch",
    "seller_full_name": "Jonas Keller",
    "current_principal_minor": 2000000,
    "price_bps": 9800,
    "transfer_price_minor": 1960000,
    "discount_premium_bps": -200,
    "days_past_due": 0,
    "maker_fee_minor": 4900,
    "taker_fee_minor": 14700,
    "seller_net_proceeds_minor": 1962300,
    "buyer_total_cost_minor": 1981900,
    "created_at": "2026-06-24T16:05:00+02:00"
  }
];

export const adminUserDirectoryFixture = {
  count: 6,
  limit: 25,
  offset: 0,
  results: [
    { id: "0d9f2a71-1111-4a52-9d10-visitor00001", email: "lukas.brunner@example.ch", full_name: "Lukas Brunner", investor_reference: "L4F8K2Q9R", account_type: "natural_person_lender", status: "active", phone_verified: true, is_staff: false, is_active: true, date_joined: "2026-03-02T09:14:00Z", can_impersonate_readonly: true },
    { id: "1b7c3e82-2222-4b63-8e21-visitor00002", email: "marie.dupont@example.fr", full_name: "Marie Dupont", investor_reference: "L7MPX3TDA", account_type: "natural_person_lender", status: "active", phone_verified: true, is_staff: false, is_active: true, date_joined: "2026-03-18T14:41:00Z", can_impersonate_readonly: true },
    { id: "2c8d4f93-3333-4c74-9f32-visitor00003", email: "jonas.keller@example.ch", full_name: "Jonas Keller", investor_reference: "L9QWB5HNE", account_type: "natural_person_lender", status: "pending_kyc", phone_verified: false, is_staff: false, is_active: true, date_joined: "2026-06-21T08:03:00Z", can_impersonate_readonly: true },
    { id: "3d9e5fa4-4444-4d85-af43-visitor00004", email: "treasury@alpenfonds.example", full_name: "Alpen Fonds AG (representative)", investor_reference: "L2ZRC8VKM", account_type: "legal_entity_lender_representative", status: "restricted", phone_verified: true, is_staff: false, is_active: true, date_joined: "2026-04-09T11:26:00Z", can_impersonate_readonly: true },
    { id: "4eaf60b5-5555-4e96-b054-visitor00005", email: "ops.admin@banxum.example", full_name: "Petra Steiner", investor_reference: "", account_type: "admin", status: "active", phone_verified: false, is_staff: true, is_active: true, date_joined: "2026-02-12T10:00:00Z", can_impersonate_readonly: false },
    { id: "5fb071c6-6666-4fa7-c165-visitor00006", email: "hq@banxum.example", full_name: "BANXUM HQ Superadmin", investor_reference: "", account_type: "superadmin", status: "active", phone_verified: false, is_staff: true, is_active: true, date_joined: "2026-01-05T08:00:00Z", can_impersonate_readonly: false }
  ]
};

export const adminFormDefaults = {
  investorUserId: "00000000-0000-4000-8000-000000002048",
  borrowerId: "borrower-helvetic-wohnbau",
  loanId: "loan-zug-park-ii",
  kycCaseId: "kyc-case-483",
  withdrawalId: "wd-1002",
  secondaryListingId: "sm-listing-711",
  collectionAccount: "BANXUM-CHF-COLLECTION",
  payoutIban: "CH9300762011623852957",
  payoutAccountName: "Preview Investor",
  borrowerName: "Helvetic Wohnbau AG",
  borrowerPayeeAccount: "CH3900762011623852957",
  borrowerLegalName: "Preview Borrower AG",
  adminEmail: "ops-admin@banxum.local",
  adminFullName: "Operations Admin"
};
