import { useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import type {
  AdminDashboardQueueItem,
  AdminDashboardQueues
} from "../api/generated/banxumApi";
import {
  useV1AuthMeRetrieve,
  useV1AuthAdminLoginConfirmCreate,
  useV1AuthAdminLoginStartCreate,
  useV1AuthLogoutCreate,
  useV1AdminOpsReconciliationBreakTasksSyncCreate
} from "../api/generated/banxumApi";
import { clearReadonlyImpersonation } from "../api/client/impersonation";
import { isFixturePreview } from "../investorPortal/data";
import { formatDate, formatDateTime } from "../investorPortal/format";
import {
  Banner,
  Button,
  Card,
  Chip,
  Empty,
  Field,
  Icon,
  Modal,
  Money,
  Stat,
  type Tone
} from "../investorPortal/ui";
import {
  CompliancePanel,
  FinanceOpsPanel,
  LoansPanel,
  ReportsPanel,
  SettingsPanel,
  UserAccountsPanel
} from "./AdminModulePanels";
import { AdminTasksPanel } from "./AdminTasksPanel";
import { useAdminOperationsDashboardData } from "./data";

const platformName = import.meta.env.VITE_PLATFORM_BRAND_NAME ?? "BANXUM";
const operatorName = import.meta.env.VITE_LEGAL_OPERATOR_NAME ?? "Garanta Finanzgruppe AG";
const adminLoginFlowStorageKey = "banxum:admin-login-flow:v1";

type AdminLoginStep = "credentials" | "code";

type AdminLoginFlowState = {
  step: AdminLoginStep;
  email: string;
  codeId: string | null;
  expiresAt: string | null;
};

function defaultAdminLoginFlowState(): AdminLoginFlowState {
  return { step: "credentials", email: "", codeId: null, expiresAt: null };
}

function adminCodeStillValid(expiresAt: string | null) {
  if (!expiresAt) return false;
  return new Date(expiresAt).getTime() > Date.now();
}

function readAdminLoginFlowState(): AdminLoginFlowState {
  if (typeof window === "undefined") return defaultAdminLoginFlowState();
  try {
    const raw = window.localStorage.getItem(adminLoginFlowStorageKey);
    if (!raw) return defaultAdminLoginFlowState();
    const parsed = JSON.parse(raw) as Partial<AdminLoginFlowState>;
    if (parsed.step === "code" && parsed.codeId && adminCodeStillValid(parsed.expiresAt ?? null)) {
      return {
        step: "code",
        email: typeof parsed.email === "string" ? parsed.email : "",
        codeId: parsed.codeId,
        expiresAt: parsed.expiresAt ?? null
      };
    }
    return {
      ...defaultAdminLoginFlowState(),
      email: typeof parsed.email === "string" ? parsed.email : ""
    };
  } catch {
    return defaultAdminLoginFlowState();
  }
}

function writeAdminLoginFlowState(state: AdminLoginFlowState) {
  if (typeof window === "undefined") return;
  if (state.step === "credentials" && !state.email) {
    window.localStorage.removeItem(adminLoginFlowStorageKey);
    return;
  }
  window.localStorage.setItem(adminLoginFlowStorageKey, JSON.stringify(state));
}

function clearAdminLoginFlowState() {
  if (typeof window === "undefined") return;
  window.localStorage.removeItem(adminLoginFlowStorageKey);
}

type QueueKey = keyof AdminDashboardQueues;

const queueDefinitions: Array<{
  key: QueueKey;
  label: string;
  shortLabel: string;
  group: string;
  description: string;
}> = [
  {
    key: "admin_tasks",
    label: "Admin tasks",
    shortLabel: "Tasks",
    group: "General",
    description: "Open internal tasks, SLA follow-ups and operational notes."
  },
  {
    key: "kyc_reviews",
    label: "KYC reviews",
    shortLabel: "KYC",
    group: "Compliance",
    description: "Didit-routed manual review cases requiring Garanta decisions."
  },
  {
    key: "bank_operations_pending",
    label: "Bank exceptions",
    shortLabel: "Bank",
    group: "Finance",
    description: "Unmatched or pending bank/PSP operations that block ledger allocation."
  },
  {
    key: "withdrawals_requested",
    label: "Withdrawals",
    shortLabel: "Withdrawals",
    group: "Finance",
    description: "Investor withdrawals waiting for external execution and finalization."
  },
  {
    key: "forced_withdrawals_requested",
    label: "Forced withdrawals",
    shortLabel: "Forced",
    group: "Finance",
    description: "Day-60 return-of-funds withdrawals generated by balance ageing."
  },
  {
    key: "balance_ageing_actions",
    label: "Balance ageing",
    shortLabel: "Ageing",
    group: "Finance",
    description: "Balance lots near or past the 30/60-day regulatory windows."
  },
  {
    key: "funding_loans",
    label: "Funding loans",
    shortLabel: "Funding",
    group: "Marketplace",
    description: "Published loans approaching deadline or close review."
  },
  {
    key: "servicing_due",
    label: "Servicing due",
    shortLabel: "Servicing",
    group: "Servicing",
    description: "Installments and borrower repayment actions inside the due window."
  },
  {
    key: "loan_risk",
    label: "Loan risk",
    shortLabel: "Risk",
    group: "Servicing",
    description: "Late/default/recovery loans needing notes, status review or recovery work."
  },
  {
    key: "secondary_listing_approvals",
    label: "Secondary approvals",
    shortLabel: "Secondary",
    group: "Marketplace",
    description: "Non-performing or non-standard secondary-market listings pending approval."
  },
  {
    key: "fx_settlement_deltas",
    label: "FX settlement",
    shortLabel: "FX",
    group: "Finance",
    description: "Internal FX activity that needs external settlement declaration."
  },
  {
    key: "failed_emails",
    label: "Failed emails",
    shortLabel: "Emails",
    group: "Comms",
    description: "Dead-lettered transactional emails requiring operational review."
  },
  {
    key: "reconciliation_breaks",
    label: "Reconciliation breaks",
    shortLabel: "Recon",
    group: "Finance",
    description: "Ledger/bank, sign anomaly, or investor-balance integrity breaks."
  }
];

const navItems: Array<{ id: string; label: string; icon: Parameters<typeof Icon>[0]["name"] }> = [
  { id: "dashboard", label: "Daily dashboard", icon: "dashboard" },
  { id: "tasks", label: "Tasks", icon: "checkCircle" },
  { id: "users", label: "Users", icon: "portfolio" },
  { id: "compliance", label: "Compliance", icon: "shield" },
  { id: "finance", label: "Finance ops", icon: "balance" },
  { id: "loans", label: "Loans", icon: "market" },
  { id: "reports", label: "Reports", icon: "docs" },
  { id: "settings", label: "Superadmin settings", icon: "settings" }
];

function priorityTone(priority: string): Tone {
  if (["urgent", "critical"].includes(priority)) return "bad";
  if (priority === "high") return "warn";
  if (priority === "low") return "neutral";
  return "info";
}

function statusTone(status: string): Tone {
  if (["approved", "active", "reconciled", "finalized", "settled", "completed"].includes(status)) {
    return "ok";
  }
  if (["urgent", "break", "integrity_break", "dead_letter", "defaulted", "penalty_mode"].includes(status)) {
    return "bad";
  }
  if (["late", "manual_review", "pending_review", "approval_requested", "withdraw_only"].includes(status)) {
    return "warn";
  }
  if (["requested", "due", "unsettled", "published", "open"].includes(status)) return "info";
  return "neutral";
}

function labelize(value: string | null | undefined) {
  if (!value) return "-";
  return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function metadataEntries(metadata: unknown) {
  if (!metadata || typeof metadata !== "object" || Array.isArray(metadata)) return [];
  return Object.entries(metadata as Record<string, unknown>).map(([key, value]) => ({
    key,
    value: Array.isArray(value) ? value.join(", ") : String(value)
  }));
}

function errorMessage(error: unknown) {
  if (error instanceof Error) return error.message;
  return "The request failed. Try again or check the backend session.";
}

function refetchLive(refetch: () => Promise<unknown>) {
  if (!isFixturePreview) void refetch();
}

function queueCount(queues: AdminDashboardQueues | undefined, key: QueueKey) {
  return queues?.[key]?.length ?? 0;
}

function allQueueItems(queues: AdminDashboardQueues | undefined) {
  if (!queues) return [];
  return queueDefinitions.flatMap((definition) => queues[definition.key]);
}

function dueLabel(item: AdminDashboardQueueItem) {
  if (item.due_at) return formatDateTime(item.due_at);
  if (item.due_date) return formatDate(item.due_date);
  return "-";
}

function itemIsOverdue(item: AdminDashboardQueueItem, asOfDate: string) {
  if (!item.due_date && !item.due_at) return false;
  const due = item.due_at ? item.due_at.slice(0, 10) : item.due_date;
  return !!due && due < asOfDate && !["completed", "finalized", "settled"].includes(item.status);
}

function isAdminPortalUser(user: { account_type?: string; status?: string } | undefined) {
  return Boolean(
    user &&
      ["admin", "superadmin"].includes(user.account_type ?? "") &&
      user.status === "active"
  );
}

export function AdminApp() {
  const queryClient = useQueryClient();
  const [localAuthState, setLocalAuthState] = useState<"unknown" | "authenticated" | "signed_out">(
    isFixturePreview ? "authenticated" : "unknown"
  );
  const finishLogout = () => {
    queryClient.clear();
    clearReadonlyImpersonation();
    setLocalAuthState(isFixturePreview ? "authenticated" : "signed_out");
  };
  const logoutMutation = useV1AuthLogoutCreate({
    mutation: { onSettled: finishLogout }
  });
  const sessionQuery = useV1AuthMeRetrieve({
    query: {
      enabled: !isFixturePreview && localAuthState !== "signed_out",
      retry: false,
      refetchOnWindowFocus: false,
      staleTime: 30_000
    }
  });
  const hasSessionAdmin = isAdminPortalUser(sessionQuery.data?.user);
  const authenticated =
    isFixturePreview || localAuthState === "authenticated" || hasSessionAdmin;

  if (!authenticated && sessionQuery.isLoading && localAuthState === "unknown") {
    return (
      <main className="admin-login">
        <section className="admin-login-card">
          <div className="admin-wordmark">
            <span className="brand-mark">{platformName.slice(0, 1)}</span>
            <div className="col" style={{ gap: 0 }}>
              <strong>{platformName} Admin</strong>
              <span>{operatorName}</span>
            </div>
          </div>
          <Empty icon="clock" title="Checking admin session">
            Restoring your existing secure session.
          </Empty>
        </section>
      </main>
    );
  }

  if (!authenticated) {
    return (
      <AdminLogin
        onAuthenticated={() => {
          setLocalAuthState("authenticated");
          void sessionQuery.refetch();
        }}
      />
    );
  }

  return (
    <AdminShell
      isLoggingOut={logoutMutation.isPending}
      onLogout={() => {
        if (isFixturePreview) {
          finishLogout();
          return;
        }
        logoutMutation.mutate();
      }}
    />
  );
}

function AdminLogin({ onAuthenticated }: { onAuthenticated: () => void }) {
  const [initialLoginFlowState] = useState(readAdminLoginFlowState);
  const [step, setStep] = useState<AdminLoginStep>(initialLoginFlowState.step);
  const [email, setEmail] = useState(initialLoginFlowState.email);
  const [password, setPassword] = useState("");
  const [code, setCode] = useState("");
  const [codeId, setCodeId] = useState<string | null>(initialLoginFlowState.codeId);
  const [expiresAt, setExpiresAt] = useState<string | null>(initialLoginFlowState.expiresAt);
  const startLogin = useV1AuthAdminLoginStartCreate();
  const confirmLogin = useV1AuthAdminLoginConfirmCreate();

  useEffect(() => {
    writeAdminLoginFlowState({ step, email, codeId, expiresAt });
  }, [codeId, email, expiresAt, step]);

  function submitCredentials(event: FormEvent) {
    event.preventDefault();
    if (isFixturePreview) {
      setCodeId("preview-admin-code");
      setExpiresAt(new Date(Date.now() + 10 * 60 * 1000).toISOString());
      setStep("code");
      return;
    }
    startLogin.mutate(
      { data: { email, password } },
      {
        onSuccess: (response) => {
          setCodeId(response.code_id);
          setExpiresAt(response.expires_at);
          setCode("");
          setStep("code");
        }
      }
    );
  }

  function submitCode(event: FormEvent) {
    event.preventDefault();
    if (isFixturePreview) {
      onAuthenticated();
      return;
    }
    if (!codeId) return;
    confirmLogin.mutate(
      { data: { code_id: codeId, code } },
      {
        onSuccess: () => {
          clearAdminLoginFlowState();
          onAuthenticated();
        }
      }
    );
  }

  function returnToCredentials() {
    setStep("credentials");
    setCode("");
    setCodeId(null);
    setExpiresAt(null);
  }

  return (
    <main className="admin-login">
      <section className="admin-login-card">
        <div className="admin-wordmark">
          <span className="brand-mark">{platformName.slice(0, 1)}</span>
          <div className="col" style={{ gap: 0 }}>
            <strong>{platformName} Admin</strong>
            <span>{operatorName}</span>
          </div>
        </div>
        <div>
          <h1>Admin console</h1>
          <p>
            Internal operational access for finance, compliance and marketplace administration.
          </p>
        </div>
        {isFixturePreview ? (
          <Banner tone="info" title="Preview admin data">
            This preview uses dummy operations data and does not call the backend.
          </Banner>
        ) : null}
        {step === "credentials" ? (
          <form className="col gap-14" onSubmit={submitCredentials}>
            <Field label="Admin email">
              <input
                autoComplete="email"
                onChange={(event) => setEmail(event.target.value)}
                placeholder="admin@banxum.com"
                required={!isFixturePreview}
                type="email"
                value={email}
              />
            </Field>
            <Field label="Password">
              <input
                autoComplete="current-password"
                onChange={(event) => setPassword(event.target.value)}
                placeholder="Admin password"
                required={!isFixturePreview}
                type="password"
                value={password}
              />
            </Field>
            {startLogin.error ? (
              <Banner tone="bad" title="Login failed">
                {errorMessage(startLogin.error)}
              </Banner>
            ) : null}
            <Button block disabled={startLogin.isPending} type="submit" variant="primary">
              {isFixturePreview ? "Continue to preview code" : "Send email code"}
            </Button>
          </form>
        ) : (
          <form className="col gap-14" onSubmit={submitCode}>
            <Field
              hint={isFixturePreview ? "Preview accepts any 6 digits." : "Use the code sent to your admin email."}
              label="Email code"
            >
              <input
                inputMode="numeric"
                maxLength={6}
                onChange={(event) => setCode(event.target.value.replace(/\D/g, "").slice(0, 6))}
                placeholder="000000"
                required={!isFixturePreview}
                value={code}
              />
            </Field>
            {expiresAt ? (
              <p className="muted" style={{ fontSize: 11.5 }}>
                Code expires {formatDateTime(expiresAt)}.
              </p>
            ) : null}
            {confirmLogin.error ? (
              <Banner tone="bad" title="Code confirmation failed">
                {errorMessage(confirmLogin.error)}
              </Banner>
            ) : null}
            <div className="row gap-8">
              <Button onClick={returnToCredentials} variant="ghost">
                Back
              </Button>
              <Button disabled={code.length < 6 || confirmLogin.isPending} type="submit" variant="primary">
                Open admin console
              </Button>
            </div>
          </form>
        )}
      </section>
    </main>
  );
}

function AdminShell({
  isLoggingOut,
  onLogout
}: {
  isLoggingOut: boolean;
  onLogout: () => void;
}) {
  const [selectedNav, setSelectedNav] = useState("dashboard");

  return (
    <div className="admin-app">
      <aside className="admin-sidebar" aria-label="Admin console navigation">
        <div className="admin-brand">
          <span className="brand-mark">{platformName.slice(0, 1)}</span>
          <div className="col" style={{ gap: 0 }}>
            <strong>{platformName}</strong>
            <span>Admin console</span>
          </div>
        </div>
        <nav className="admin-nav">
          {navItems.map((item) => (
            <button
              aria-current={selectedNav === item.id ? "page" : undefined}
              className={selectedNav === item.id ? "active" : ""}
              key={item.id}
              onClick={() => setSelectedNav(item.id)}
              type="button"
            >
              <Icon name={item.icon} size={16} />
              <span>{item.label}</span>
            </button>
          ))}
        </nav>
        <div className="admin-sidebar-foot">
          <Chip dot={false} tone="ok">Admin session</Chip>
          <Button disabled={isLoggingOut} icon="logout" onClick={onLogout} size="sm" variant="ghost">
            {isLoggingOut ? "Signing out..." : "Sign out"}
          </Button>
        </div>
      </aside>
      <main className="admin-main">
        <header className="admin-topbar">
          <div>
            <p className="eyebrow">Internal operations</p>
            <h1>{selectedNav === "dashboard" ? "Admin operations" : labelize(selectedNav)}</h1>
          </div>
          <div className="row gap-8 wrap">
            {isFixturePreview ? <Chip dot={false} tone="info">Preview data</Chip> : null}
            <Chip dot={false} tone="neutral">{operatorName}</Chip>
          </div>
        </header>
        {selectedNav === "dashboard" ? <AdminDashboard /> : null}
        {selectedNav === "tasks" ? <AdminTasksPanel /> : null}
        {selectedNav === "users" ? <UserAccountsPanel /> : null}
        {selectedNav === "compliance" ? <CompliancePanel /> : null}
        {selectedNav === "finance" ? <FinanceOpsPanel /> : null}
        {selectedNav === "loans" ? <LoansPanel /> : null}
        {selectedNav === "reports" ? <ReportsPanel /> : null}
        {selectedNav === "settings" ? <SettingsPanel /> : null}
      </main>
    </div>
  );
}

function AdminDashboard() {
  const dashboardQuery = useAdminOperationsDashboardData();
  const dashboard = dashboardQuery.data;
  const [selectedQueue, setSelectedQueue] = useState<QueueKey>("admin_tasks");
  const [selectedItem, setSelectedItem] = useState<AdminDashboardQueueItem | null>(null);
  const [syncNotice, setSyncNotice] = useState("");
  const reconciliationTaskSync = useV1AdminOpsReconciliationBreakTasksSyncCreate();

  const selectedDefinition = queueDefinitions.find((definition) => definition.key === selectedQueue)!;
  const queueItems = dashboard?.queues[selectedQueue] ?? [];
  const allItems = useMemo(() => allQueueItems(dashboard?.queues), [dashboard]);
  const urgentItems = allItems.filter((item) => priorityTone(item.priority) === "bad");
  const highItems = allItems.filter((item) => ["urgent", "critical", "high"].includes(item.priority));
  const overdueItems = allItems.filter((item) => itemIsOverdue(item, dashboard?.as_of_date ?? "1970-01-01"));
  const moneyOps = [
    "bank_operations_pending",
    "withdrawals_requested",
    "forced_withdrawals_requested",
    "fx_settlement_deltas",
    "reconciliation_breaks"
  ].reduce((sum, key) => sum + queueCount(dashboard?.queues, key as QueueKey), 0);

  function syncReconciliationBreakTasks() {
    if (isFixturePreview) {
      setSyncNotice(
        "Preview mode: reconciliation task sync would create or reuse tasks for current break snapshots."
      );
      return;
    }
    reconciliationTaskSync.mutate(
      { data: { limit: 100 } },
      {
        onSuccess: (result) => {
          setSyncNotice(
            `Reconciliation tasks synced: ${result.created_count} created, ${result.existing_count} already existed.`
          );
          refetchLive(dashboardQuery.refetch);
        }
      }
    );
  }

  if (dashboardQuery.isLoading && !dashboard) {
    return (
      <div className="admin-content">
        <Card padded>
          <Empty icon="clock" title="Loading admin operations">
            Fetching the latest dashboard queues.
          </Empty>
        </Card>
      </div>
    );
  }

  if (dashboardQuery.error && !dashboard) {
    return (
      <div className="admin-content">
        <Banner
          actions={
            <Button icon="refresh" onClick={() => refetchLive(dashboardQuery.refetch)} size="sm" variant="primary">
              Retry
            </Button>
          }
          tone="bad"
          title="Could not load admin dashboard"
        >
          {errorMessage(dashboardQuery.error)}
        </Banner>
      </div>
    );
  }

  if (!dashboard) return null;

  return (
    <div className="admin-content">
      {isFixturePreview ? (
        <Banner tone="info" title="Preview admin data">
          These queues and amounts are dummy operations data for UI review. They are not platform records.
        </Banner>
      ) : null}
      <section className="admin-kpi-grid" aria-label="Operational summary">
        <Stat raw={String(allItems.length)} label="Open queue items" sub={`As of ${formatDateTime(dashboard.as_of)}`} />
        <Stat raw={String(highItems.length)} label="High priority" sub={`${urgentItems.length} urgent`} />
        <Stat raw={String(overdueItems.length)} label="Overdue SLA" sub={`Window ${dashboard.due_window_days} days`} />
        <Stat raw={String(moneyOps)} label="Finance actions" sub="Bank, FX, withdrawals, reconciliation" />
      </section>

      <div className="admin-dashboard-head">
        <div>
          <h2>Daily queues</h2>
          <p>Short operational queues for finance, compliance, marketplace and servicing work.</p>
        </div>
        <div className="row gap-8 wrap">
          {selectedQueue === "reconciliation_breaks" ? (
            <Button
              disabled={reconciliationTaskSync.isPending}
              icon="checkCircle"
              onClick={syncReconciliationBreakTasks}
              size="sm"
              variant="primary"
            >
              Create tasks
            </Button>
          ) : null}
          <Button icon="refresh" onClick={() => refetchLive(dashboardQuery.refetch)} size="sm">
            Refresh
          </Button>
        </div>
      </div>

      {syncNotice ? (
        <Banner tone="ok" title="Reconciliation task sync">
          {syncNotice}
        </Banner>
      ) : null}
      {reconciliationTaskSync.error ? (
        <Banner tone="bad" title="Could not sync reconciliation tasks">
          {errorMessage(reconciliationTaskSync.error)}
        </Banner>
      ) : null}

      <section className="admin-queue-layout">
        <Card className="admin-queue-tabs">
          <div className="admin-queue-tabs-head">Queues</div>
          {queueDefinitions.map((definition) => {
            const count = queueCount(dashboard.queues, definition.key);
            return (
              <button
                aria-label={`${definition.label}: ${count} open`}
                aria-selected={selectedQueue === definition.key}
                className={selectedQueue === definition.key ? "active" : ""}
                key={definition.key}
                onClick={() => setSelectedQueue(definition.key)}
                type="button"
              >
                <span>
                  <strong>{definition.shortLabel}</strong>
                  <small>{definition.group}</small>
                </span>
                <em>{count}</em>
              </button>
            );
          })}
        </Card>
        <Card className="admin-queue-panel">
          <div className="admin-panel-head">
            <div>
              <h3>{selectedDefinition.label}</h3>
              <p>{selectedDefinition.description}</p>
            </div>
            <Chip dot={false} tone={queueItems.length ? "info" : "neutral"}>
              {queueItems.length} open
            </Chip>
          </div>
          {queueItems.length ? (
            <div className="table-wrap admin-table-wrap">
              <table className="admin-table">
                <thead>
                  <tr>
                    <th>Item</th>
                    <th>Status</th>
                    <th>Priority</th>
                    <th>Due</th>
                    <th>Amount</th>
                    <th>Object</th>
                  </tr>
                </thead>
                <tbody>
                  {queueItems.map((item) => (
                    <tr
                      className={itemIsOverdue(item, dashboard.as_of_date) ? "is-overdue" : ""}
                      key={item.id}
                      onClick={() => setSelectedItem(item)}
                    >
                      <td>
                        <button className="admin-row-button" type="button">
                          <strong>{item.title}</strong>
                          <span>{item.kind}</span>
                        </button>
                      </td>
                      <td><Chip status={item.status} tone={statusTone(item.status)}>{labelize(item.status)}</Chip></td>
                      <td><Chip dot={false} tone={priorityTone(item.priority)}>{labelize(item.priority)}</Chip></td>
                      <td className="mono">{dueLabel(item)}</td>
                      <td>
                        {item.amount_minor === null ? (
                          <span className="muted">-</span>
                        ) : (
                          <Money amountMinor={item.amount_minor} currency={item.currency} />
                        )}
                      </td>
                      <td>
                        <span className="admin-object">{item.object_type}</span>
                        <span className="mono muted">{item.object_id}</span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <Empty icon="checkCircle" title="No items in this queue">
              The dashboard API did not return active work for this queue.
            </Empty>
          )}
        </Card>
      </section>

      <section className="admin-section">
        <div className="admin-dashboard-head">
          <div>
            <h2>Currency operations</h2>
            <p>Balance ageing, withdrawals, pending bank operations and unsettled FX by currency.</p>
          </div>
        </div>
        <Card>
          {dashboard.currency_summaries.length ? (
            <div className="table-wrap admin-table-wrap">
              <table className="admin-table admin-currency-table">
                <thead>
                  <tr>
                    <th>Currency</th>
                    <th>Available</th>
                    <th>Investable</th>
                    <th>Withdraw-only</th>
                    <th>Overdue</th>
                    <th>Frozen</th>
                    <th>Penalty</th>
                    <th>Pending withdrawals</th>
                    <th>Pending bank ops</th>
                    <th>FX unsettled</th>
                  </tr>
                </thead>
                <tbody>
                  {dashboard.currency_summaries.map((summary) => (
                    <tr key={summary.currency}>
                      <td><Chip dot={false} tone="accent">{summary.currency}</Chip></td>
                      <td><Money amountMinor={summary.available_balance_minor} currency={summary.currency} /></td>
                      <td><Money amountMinor={summary.investable_available_minor} currency={summary.currency} /></td>
                      <td><Money amountMinor={summary.withdraw_only_available_minor} currency={summary.currency} /></td>
                      <td><Money amountMinor={summary.overdue_available_minor} currency={summary.currency} /></td>
                      <td><Money amountMinor={summary.frozen_available_minor} currency={summary.currency} /></td>
                      <td><Money amountMinor={summary.penalty_mode_available_minor} currency={summary.currency} /></td>
                      <td>
                        <Money amountMinor={summary.pending_withdrawal_minor + summary.forced_withdrawal_minor} currency={summary.currency} />
                      </td>
                      <td><Money amountMinor={summary.pending_bank_operation_minor} currency={summary.currency} /></td>
                      <td>
                        <div className="col gap-4">
                          <span><span className="muted">Sold </span><Money amountMinor={summary.fx_unsettled_sold_minor} currency={summary.currency} /></span>
                          <span><span className="muted">Bought </span><Money amountMinor={summary.fx_unsettled_bought_minor} currency={summary.currency} /></span>
                          <span><span className="muted">Fee </span><Money amountMinor={summary.fx_unsettled_fee_minor} currency={summary.currency} /></span>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <Empty icon="balance" title="No currency summaries">
              Currency-level operational balances will appear after the backend returns dashboard data.
            </Empty>
          )}
        </Card>
      </section>

      {selectedItem ? (
        <AdminQueueDrawer
          item={selectedItem}
          onClose={() => setSelectedItem(null)}
          queueLabel={selectedDefinition.label}
        />
      ) : null}
    </div>
  );
}

function AdminQueueDrawer({
  item,
  onClose,
  queueLabel
}: {
  item: AdminDashboardQueueItem;
  onClose: () => void;
  queueLabel: string;
}) {
  const metadata = metadataEntries(item.metadata);

  return (
    <Modal drawer title={item.title} onClose={onClose}>
      <div className="admin-drawer-body">
        <div className="row gap-8 wrap">
          <Chip dot={false} tone="neutral">{queueLabel}</Chip>
          <Chip status={item.status} tone={statusTone(item.status)}>{labelize(item.status)}</Chip>
          <Chip dot={false} tone={priorityTone(item.priority)}>{labelize(item.priority)}</Chip>
        </div>
        <div className="admin-detail-grid">
          <ReviewRow label="Kind" value={item.kind} />
          <ReviewRow label="Object" value={`${item.object_type} / ${item.object_id}`} />
          <ReviewRow label="Due" value={dueLabel(item)} />
          <ReviewRow
            label="Amount"
            value={
              item.amount_minor === null ? (
                "-"
              ) : (
                <Money amountMinor={item.amount_minor} currency={item.currency} />
              )
            }
          />
        </div>
        <div>
          <h4>Metadata</h4>
          {metadata.length ? (
            <div className="admin-meta">
              {metadata.map((entry) => (
                <ReviewRow key={entry.key} label={labelize(entry.key)} value={entry.value} />
              ))}
            </div>
          ) : (
            <p className="muted">No metadata returned for this dashboard item.</p>
          )}
        </div>
        <Banner tone="info" title="Module action deferred">
          This drawer provides queue context for the dashboard slice. The next admin slices will connect each
          item to its module-specific action form and audit timeline.
        </Banner>
      </div>
    </Modal>
  );
}

function ReviewRow({ label, value }: { label: string; value: ReactNode }) {
  return (
    <div className="admin-review-row">
      <span>{label}</span>
      <strong>{value}</strong>
    </div>
  );
}
