# Generated by Django 5.2.14 on 2026-06-02 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0004_alter_loan_status_alter_loanevent_event_type'),
        ('marketplace_primary', '0002_primary_order_event_append_only_guard'),
        ('platform_core', '0002_append_only_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorLoanHolding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investor_user_id', models.UUIDField()),
                ('source_type', models.CharField(choices=[('primary_market', 'Primary market'), ('secondary_market', 'Secondary market'), ('manual_admin', 'Manual admin')], max_length=64)),
                ('source_id', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('transferred', 'Transferred'), ('closed', 'Closed')], default='active', max_length=32)),
                ('original_principal_minor', models.BigIntegerField()),
                ('current_principal_minor', models.BigIntegerField()),
                ('loan_share_ppm', models.PositiveIntegerField()),
                ('assignment_effective_at', models.DateTimeField()),
                ('created_by_admin_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investor_loan_holdings', to='platform_core.currency')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investor_holdings', to='loans.loan')),
                ('source_primary_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_holdings', to='marketplace_primary.primaryinvestmentorder')),
            ],
            options={
                'ordering': ['loan', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvestorLoanHoldingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_id', models.UUIDField()),
                ('investor_user_id', models.UUIDField()),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('transferred', 'Transferred'), ('principal_updated', 'Principal updated'), ('closed', 'Closed')], max_length=64)),
                ('actor_user_id', models.UUIDField()),
                ('actor_account_type', models.CharField(max_length=64)),
                ('previous_status', models.CharField(blank=True, max_length=64)),
                ('new_status', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='holdings.investorloanholding')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='investorloanholding',
            index=models.Index(fields=['loan', 'status'], name='holdings_in_loan_id_8c742b_idx'),
        ),
        migrations.AddIndex(
            model_name='investorloanholding',
            index=models.Index(fields=['investor_user_id', 'status'], name='holdings_in_investo_7545a0_idx'),
        ),
        migrations.AddIndex(
            model_name='investorloanholding',
            index=models.Index(fields=['currency', 'status'], name='holdings_in_currenc_67266b_idx'),
        ),
        migrations.AddIndex(
            model_name='investorloanholding',
            index=models.Index(fields=['source_type', 'source_id'], name='holdings_in_source__b19f4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='investorloanholding',
            constraint=models.CheckConstraint(condition=models.Q(('original_principal_minor__gt', 0)), name='holding_original_principal_positive'),
        ),
        migrations.AddConstraint(
            model_name='investorloanholding',
            constraint=models.CheckConstraint(condition=models.Q(('current_principal_minor__gte', 0)), name='holding_current_principal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='investorloanholding',
            constraint=models.CheckConstraint(condition=models.Q(('current_principal_minor__lte', models.F('original_principal_minor'))), name='holding_current_principal_not_above_original'),
        ),
        migrations.AddConstraint(
            model_name='investorloanholding',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id'), name='unique_holding_source'),
        ),
        migrations.AddIndex(
            model_name='investorloanholdingevent',
            index=models.Index(fields=['holding', 'occurred_at'], name='holdings_in_holding_8c90d9_idx'),
        ),
        migrations.AddIndex(
            model_name='investorloanholdingevent',
            index=models.Index(fields=['loan_id', 'event_type'], name='holdings_in_loan_id_cd4ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='investorloanholdingevent',
            index=models.Index(fields=['investor_user_id', 'occurred_at'], name='holdings_in_investo_19db98_idx'),
        ),
    ]
