# Generated by Django 5.2.16 on 2026-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0002_holding_event_append_only_guard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorloanholding',
            name='source_type',
            field=models.CharField(choices=[('primary_market', 'Primary market'), ('originator_claim', 'Loan Originator claim'), ('secondary_market', 'Secondary market'), ('manual_admin', 'Manual admin')], max_length=64),
        ),
    ]
