# Generated by Django 5.2.16 on 2026-08-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0003_alter_investorloanholding_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorloanholding',
            name='economic_entitlement_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
