# Generated by Django 5.2.14 on 2026-06-02 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('kyc_manual_review', 'KYC manual review'), ('account_access_review', 'Account access review'), ('borrower_onboarding', 'Borrower onboarding'), ('loan_setup', 'Loan setup'), ('payment_reconciliation', 'Payment reconciliation'), ('fx_settlement', 'FX settlement'), ('document_review', 'Document review'), ('email_delivery_failure', 'Email delivery failure'), ('reporting', 'Reporting'), ('support', 'Support'), ('other', 'Other')], max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('waiting', 'Waiting'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='open', max_length=32)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('related_object_type', models.CharField(blank=True, max_length=128)),
                ('related_object_id', models.CharField(blank=True, max_length=128)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_note', models.TextField(blank=True)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_admin_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_admin_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'due_at', '-priority', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AdminTaskEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status changed'), ('assigned', 'Assigned')], max_length=32)),
                ('actor_user_id', models.UUIDField()),
                ('actor_account_type', models.CharField(max_length=64)),
                ('previous_status', models.CharField(blank=True, max_length=32)),
                ('new_status', models.CharField(blank=True, max_length=32)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='admin_ops.admintask')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='admintask',
            index=models.Index(fields=['status', 'priority'], name='admin_ops_a_status_c641d6_idx'),
        ),
        migrations.AddIndex(
            model_name='admintask',
            index=models.Index(fields=['task_type', 'status'], name='admin_ops_a_task_ty_48876e_idx'),
        ),
        migrations.AddIndex(
            model_name='admintask',
            index=models.Index(fields=['assigned_admin', 'status'], name='admin_ops_a_assigne_a7d926_idx'),
        ),
        migrations.AddIndex(
            model_name='admintask',
            index=models.Index(fields=['due_at'], name='admin_ops_a_due_at_3c94ee_idx'),
        ),
        migrations.AddIndex(
            model_name='admintask',
            index=models.Index(fields=['related_object_type', 'related_object_id'], name='admin_ops_a_related_047baf_idx'),
        ),
        migrations.AddIndex(
            model_name='admintaskevent',
            index=models.Index(fields=['task', 'occurred_at'], name='admin_ops_a_task_id_410502_idx'),
        ),
        migrations.AddIndex(
            model_name='admintaskevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='admin_ops_a_event_t_83848d_idx'),
        ),
        migrations.AddIndex(
            model_name='admintaskevent',
            index=models.Index(fields=['actor_user_id', 'occurred_at'], name='admin_ops_a_actor_u_9369f4_idx'),
        ),
    ]
