# Generated by Django 5.2.16 on 2026-08-05 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_ops", "0005_alter_admintask_task_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="admintask",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("related_object_type", "LoanFundingCloseFailure"), ("task_type", "loan_setup")
                ),
                fields=("task_type", "related_object_type", "related_object_id"),
                name="unique_loan_funding_close_failure_task",
            ),
        ),
    ]
