# Generated by Django 5.2.14 on 2026-06-02 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_borrower_entity_event_append_only_guard'),
        ('platform_core', '0002_append_only_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('investor_summary', models.TextField()),
                ('purpose', models.CharField(choices=[('working_capital', 'Working capital'), ('liquidity', 'Liquidity'), ('refinancing', 'Refinancing'), ('debt_consolidation', 'Debt consolidation'), ('acquisition', 'Acquisition'), ('bridge_financing', 'Bridge financing'), ('project_finance', 'Project finance'), ('corporate_project_finance', 'Corporate project finance'), ('capex', 'Capex / business expansion'), ('development', 'Development'), ('inventory_trade_finance', 'Inventory or trade finance'), ('other', 'Other')], max_length=64)),
                ('purpose_description', models.TextField(blank=True)),
                ('principal_minor', models.BigIntegerField()),
                ('interest_rate_bps', models.PositiveIntegerField()),
                ('term_months', models.PositiveSmallIntegerField()),
                ('repayment_type', models.CharField(choices=[('equal_installments', 'Equal installments'), ('bullet_periodic_interest', 'Bullet principal with periodic interest'), ('amortizing_principal_interest', 'Amortizing principal and interest'), ('interest_only_then_bullet', 'Interest-only then bullet'), ('interest_only_then_amortizing', 'Interest-only then amortizing')], max_length=64)),
                ('interest_only_months', models.PositiveSmallIntegerField(default=0)),
                ('funding_deadline', models.DateField()),
                ('first_payment_date', models.DateField()),
                ('collateral_type', models.CharField(choices=[('real_estate', 'Real estate'), ('corporate_guarantee', 'Corporate guarantee'), ('personal_guarantee', 'Personal guarantee'), ('receivables', 'Receivables'), ('invoices', 'Invoices'), ('equipment', 'Equipment'), ('inventory', 'Inventory'), ('securities_pledge', 'Securities pledge'), ('cash_collateral', 'Cash collateral'), ('share_pledge', 'Share pledge'), ('asset_backed', 'Asset backed'), ('mixed_collateral', 'Mixed collateral'), ('unsecured_exception', 'Unsecured exception'), ('other', 'Other')], default='real_estate', max_length=64)),
                ('collateral_value_minor', models.BigIntegerField()),
                ('collateral_description', models.TextField(blank=True)),
                ('risk_rating', models.CharField(choices=[('AAA', 'AAA'), ('AA+', 'AA+'), ('AA', 'AA'), ('AA-', 'AA-'), ('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('BBB+', 'BBB+'), ('BBB', 'BBB'), ('BBB-', 'BBB-'), ('BB+', 'BB+'), ('BB', 'BB'), ('BB-', 'BB-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D'), ('unrated', 'Unrated')], max_length=16)),
                ('borrower_success_fee_bps', models.PositiveSmallIntegerField(default=200)),
                ('lender_payment_fee_minor', models.BigIntegerField(default=0)),
                ('default_penalty_interest_bps', models.PositiveIntegerField(default=0)),
                ('recovery_fee_bps', models.PositiveIntegerField(default=0)),
                ('recovery_waterfall_version', models.CharField(default='v1', max_length=64)),
                ('schedule_version', models.PositiveIntegerField(default=1)),
                ('total_scheduled_principal_minor', models.BigIntegerField(default=0)),
                ('total_scheduled_interest_minor', models.BigIntegerField(default=0)),
                ('committed_principal_minor', models.BigIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_admin_id', models.UUIDField()),
                ('updated_by_admin_id', models.UUIDField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='entities.borrowerentity')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='platform_core.currency')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LoanEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('published', 'Published'), ('schedule_generated', 'Schedule generated')], max_length=32)),
                ('actor_user_id', models.UUIDField()),
                ('actor_account_type', models.CharField(max_length=64)),
                ('previous_status', models.CharField(blank=True, max_length=32)),
                ('new_status', models.CharField(blank=True, max_length=32)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='loans.loan')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_version', models.PositiveIntegerField()),
                ('installment_number', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('principal_minor', models.BigIntegerField()),
                ('interest_minor', models.BigIntegerField()),
                ('total_minor', models.BigIntegerField()),
                ('admin_overridden', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='loans.loan')),
            ],
            options={
                'ordering': ['schedule_version', 'installment_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status', 'funding_deadline'], name='loans_loan_status_320054_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['borrower', 'status'], name='loans_loan_borrowe_d07c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['currency', 'status'], name='loans_loan_currenc_b0d978_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['purpose', 'status'], name='loans_loan_purpose_52f583_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['risk_rating', 'status'], name='loans_loan_risk_ra_4b1e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='loanevent',
            index=models.Index(fields=['loan', 'occurred_at'], name='loans_loane_loan_id_d83566_idx'),
        ),
        migrations.AddIndex(
            model_name='loanevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='loans_loane_event_t_72c62f_idx'),
        ),
        migrations.AddIndex(
            model_name='loanevent',
            index=models.Index(fields=['actor_user_id', 'occurred_at'], name='loans_loane_actor_u_737140_idx'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['loan', 'schedule_version'], name='loans_loani_loan_id_6f59af_idx'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['due_date'], name='loans_loani_due_dat_1afa52_idx'),
        ),
        migrations.AddConstraint(
            model_name='loaninstallment',
            constraint=models.UniqueConstraint(fields=('loan', 'schedule_version', 'installment_number'), name='unique_loan_schedule_installment_number'),
        ),
    ]
