# Generated by Django 5.2.14 on 2026-06-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_borrower_entity_event_append_only_guard'),
        ('loans', '0002_loan_event_append_only_guard'),
        ('platform_core', '0002_append_only_guards'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('committed_principal_minor__gte', 0), ('committed_principal_minor__lte', models.F('principal_minor'))), name='loan_committed_principal_within_principal'),
        ),
    ]
