# Generated by Django 5.2.14 on 2026-06-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_loan_committed_principal_within_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('funded', 'Funded'), ('cancelled', 'Cancelled')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='loanevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('published', 'Published'), ('funding_closed', 'Funding closed'), ('schedule_generated', 'Schedule generated')], max_length=32),
        ),
    ]
