# Generated by Django 5.2.14 on 2026-06-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loan_status_alter_loanevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('published', 'Published'), ('funding_closed', 'Funding closed'), ('schedule_generated', 'Schedule generated'), ('servicing_status_changed', 'Servicing status changed'), ('recovery_recorded', 'Recovery recorded'), ('write_off_recorded', 'Write-off recorded')], max_length=32),
        ),
    ]
