# Generated by Django 5.2.16 on 2026-08-04 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_borrowerentity_business_classification_and_more'),
        ('loans', '0011_active_servicing_status'),
        ('platform_core', '0004_qa_dev_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='product_type',
            field=models.CharField(choices=[('direct', 'Direct loan'), ('originator_claim', 'Loan Originator claim')], default='direct', max_length=32),
        ),
        migrations.AlterField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='entities.borrowerentity'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='funding_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['product_type', 'status'], name='loans_loan_product_20e144_idx'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product_type', 'direct'), ('borrower__isnull', False), ('funding_deadline__isnull', False)), models.Q(('product_type', 'originator_claim'), ('borrower__isnull', True), ('funding_deadline__isnull', True), ('is_refinancing', False)), _connector='OR'), name='loan_product_type_required_fields'),
        ),
    ]
