# Generated by Django 5.2.16 on 2026-08-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_borrowerentity_business_classification_and_more'),
        ('loans', '0012_loan_product_type_alter_loan_borrower_and_more'),
        ('platform_core', '0004_qa_dev_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='skin_in_the_game_bps',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('skin_in_the_game_bps__lt', 10000)), name='loan_skin_in_the_game_bps_valid'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('skin_in_the_game_bps', 0), ('product_type', 'originator_claim'), _connector='OR'), name='loan_skin_in_the_game_originator_only'),
        ),
    ]
