# Generated by Django 5.2.16 on 2026-08-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0003_borrowerentity_business_classification_and_more"),
        ("loans", "0014_universal_payment_waterfall"),
        ("platform_core", "0004_qa_dev_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="minimum_subscription_bps",
            field=models.PositiveSmallIntegerField(default=5000),
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_subscription_bps__lte", 10000)),
                name="loan_minimum_subscription_bps_valid",
            ),
        ),
    ]
