# Generated by Django 5.2.16 on 2026-08-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0015_loan_minimum_subscription_bps_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("funding_close_failed", "Funding close failed"),
                    ("funded", "Funded"),
                    ("active", "Active"),
                    ("late", "Late"),
                    ("defaulted", "Defaulted"),
                    ("repaid", "Repaid"),
                    ("written_off", "Written off"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="loanevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("published", "Published"),
                    ("funding_closed", "Funding closed"),
                    ("funding_close_failed", "Funding close failed"),
                    ("disbursed", "Disbursed"),
                    ("funding_cancelled", "Funding cancelled"),
                    ("schedule_generated", "Schedule generated"),
                    ("servicing_status_changed", "Servicing status changed"),
                    ("recovery_recorded", "Recovery recorded"),
                    ("write_off_recorded", "Write-off recorded"),
                ],
                max_length=32,
            ),
        ),
    ]
