# Generated by Django 5.2.16 on 2026-09-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_borrowerentity_business_classification_and_more'),
        ('loans', '0016_alter_loan_status_alter_loanevent_event_type'),
        ('platform_core', '0004_qa_dev_mode'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loan',
            name='loan_product_type_required_fields',
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product_type', 'direct'), ('borrower__isnull', False), ('funding_deadline__isnull', False)), models.Q(('product_type', 'originator_claim'), ('borrower__isnull', True), ('is_refinancing', False)), _connector='OR'), name='loan_product_type_required_fields'),
        ),
    ]
