# Generated by Django 5.2.16 on 2026-09-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_remove_loan_loan_product_type_required_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('published', 'Published'), ('funding_closed', 'Funding closed'), ('funding_close_failed', 'Funding close failed'), ('disbursed', 'Disbursed'), ('funding_cancelled', 'Funding cancelled'), ('originator_subscription_activated', 'Originator subscription activated'), ('schedule_generated', 'Schedule generated'), ('servicing_status_changed', 'Servicing status changed'), ('recovery_recorded', 'Recovery recorded'), ('write_off_recorded', 'Write-off recorded')], max_length=48),
        ),
    ]
