# Generated by Django 5.2.14 on 2026-06-02 11:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_core', '0002_append_only_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(choices=[('lender_deposit', 'Lender deposit'), ('lender_withdrawal', 'Lender withdrawal'), ('borrower_loan_disbursement', 'Borrower loan disbursement'), ('borrower_repayment', 'Borrower repayment'), ('garanta_out', 'Garanta out'), ('garanta_in', 'Garanta in'), ('currency_exchange_external_settlement', 'Currency exchange external settlement')], max_length=64)),
                ('status', models.CharField(choices=[('reconciled', 'Reconciled'), ('pending_review', 'Pending review'), ('unmatched', 'Unmatched'), ('returned', 'Returned')], default='reconciled', max_length=32)),
                ('amount_minor', models.BigIntegerField()),
                ('booking_date', models.DateField()),
                ('value_date', models.DateField()),
                ('collection_account_identifier', models.CharField(blank=True, max_length=128)),
                ('payer_name', models.CharField(blank=True, max_length=255)),
                ('payer_account_identifier', models.CharField(blank=True, max_length=128)),
                ('payee_name', models.CharField(blank=True, max_length=255)),
                ('payee_account_identifier', models.CharField(blank=True, max_length=128)),
                ('bank_reference', models.CharField(blank=True, max_length=160)),
                ('payment_reference', models.CharField(blank=True, max_length=160)),
                ('linked_object_type', models.CharField(blank=True, max_length=128)),
                ('linked_object_id', models.CharField(blank=True, max_length=128)),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('confirmed_by_admin_id', models.UUIDField()),
                ('confirmed_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_operations', to='platform_core.currency')),
            ],
            options={
                'ordering': ['-confirmed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('collection_cash', 'Collection cash'), ('investor_balance_liability', 'Investor balance liability'), ('garanta_accrued_revenue', 'Garanta accrued revenue'), ('suspense_unmatched_cash', 'Suspense/unmatched cash'), ('withdrawal_payable', 'Withdrawal payable'), ('refund_payable', 'Refund payable'), ('loan_funding_escrow', 'Loan funding escrow'), ('borrower_disbursement_payable', 'Borrower disbursement payable'), ('platform_fee_revenue', 'Platform fee revenue'), ('fx_clearing', 'FX clearing'), ('fx_fee_revenue', 'FX fee revenue'), ('fx_gain_loss', 'FX gain/loss'), ('recovery_distribution_payable', 'Recovery distribution payable')], max_length=64)),
                ('owner_type', models.CharField(blank=True, max_length=64)),
                ('owner_id', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_accounts', to='platform_core.currency')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LedgerJournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=128)),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('internal', 'Internal')], max_length=16)),
                ('booking_date', models.DateField()),
                ('value_date', models.DateField()),
                ('effective_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('gross_amount_minor', models.BigIntegerField()),
                ('net_amount_minor', models.BigIntegerField()),
                ('source_type', models.CharField(max_length=128)),
                ('source_id', models.CharField(max_length=128)),
                ('lender_user_id', models.UUIDField(blank=True, null=True)),
                ('borrower_id', models.UUIDField(blank=True, null=True)),
                ('loan_id', models.UUIDField(blank=True, null=True)),
                ('bank_reference', models.CharField(blank=True, max_length=160)),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('actor_type', models.CharField(max_length=64)),
                ('actor_id', models.CharField(max_length=128)),
                ('tax_metadata', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('bank_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='ledger.bankoperation')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_journal_entries', to='platform_core.currency')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='ledger.ledgerjournalentry')),
            ],
            options={
                'ordering': ['booking_date', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvestorBalanceLot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investor_user_id', models.UUIDField()),
                ('source_type', models.CharField(choices=[('deposit', 'Deposit'), ('installment', 'Installment'), ('secondary_market_proceeds', 'Secondary-market proceeds'), ('fx_proceeds', 'FX proceeds'), ('refund', 'Refund'), ('correction', 'Correction'), ('penalty_reversal', 'Penalty reversal')], max_length=64)),
                ('source_id', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('available', 'Available'), ('consumed', 'Consumed'), ('frozen', 'Frozen'), ('penalty_mode', 'Penalty mode'), ('penalty_exhausted', 'Penalty exhausted')], default='available', max_length=32)),
                ('received_at', models.DateTimeField()),
                ('investment_deadline_at', models.DateTimeField()),
                ('withdrawal_deadline_at', models.DateTimeField()),
                ('original_amount_minor', models.BigIntegerField()),
                ('available_amount_minor', models.BigIntegerField()),
                ('invested_amount_minor', models.BigIntegerField(default=0)),
                ('withdrawn_amount_minor', models.BigIntegerField(default=0)),
                ('penalized_amount_minor', models.BigIntegerField(default=0)),
                ('lineage', models.JSONField(blank=True, default=list)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investor_balance_lots', to='platform_core.currency')),
                ('source_journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_lots', to='ledger.ledgerjournalentry')),
            ],
            options={
                'ordering': ['received_at', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=16)),
                ('amount_minor', models.BigIntegerField()),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='ledger.ledgeraccount')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_postings', to='platform_core.currency')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='ledger.ledgerjournalentry')),
            ],
            options={
                'ordering': ['journal_entry', 'side', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of_date', models.DateField()),
                ('bank_stated_balance_minor', models.BigIntegerField()),
                ('investor_balance_liability_minor', models.BigIntegerField()),
                ('garanta_accrued_revenue_minor', models.BigIntegerField(default=0)),
                ('suspense_unmatched_cash_minor', models.BigIntegerField(default=0)),
                ('pending_exception_balance_minor', models.BigIntegerField(default=0)),
                ('reconciliation_difference_minor', models.BigIntegerField()),
                ('created_by_admin_id', models.UUIDField()),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_snapshots', to='platform_core.currency')),
            ],
            options={
                'ordering': ['-as_of_date', '-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='bankoperation',
            index=models.Index(fields=['operation_type', 'status'], name='ledger_bank_operati_f5b1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='bankoperation',
            index=models.Index(fields=['currency', 'value_date'], name='ledger_bank_currenc_f15713_idx'),
        ),
        migrations.AddIndex(
            model_name='bankoperation',
            index=models.Index(fields=['bank_reference'], name='ledger_bank_bank_re_598e76_idx'),
        ),
        migrations.AddIndex(
            model_name='bankoperation',
            index=models.Index(fields=['payment_reference'], name='ledger_bank_payment_04e5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='bankoperation',
            index=models.Index(fields=['linked_object_type', 'linked_object_id'], name='ledger_bank_linked__ff543b_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['account_type', 'currency'], name='ledger_ledg_account_5baf09_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['owner_type', 'owner_id'], name='ledger_ledg_owner_t_5fb4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerjournalentry',
            index=models.Index(fields=['event_type', 'booking_date'], name='ledger_ledg_event_t_48b66b_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerjournalentry',
            index=models.Index(fields=['currency', 'booking_date'], name='ledger_ledg_currenc_70a147_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerjournalentry',
            index=models.Index(fields=['lender_user_id', 'currency'], name='ledger_ledg_lender__dcba34_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerjournalentry',
            index=models.Index(fields=['source_type', 'source_id'], name='ledger_ledg_source__22dfde_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerjournalentry',
            index=models.Index(fields=['bank_reference'], name='ledger_ledg_bank_re_d429cb_idx'),
        ),
        migrations.AddIndex(
            model_name='investorbalancelot',
            index=models.Index(fields=['investor_user_id', 'currency', 'status'], name='ledger_inve_investo_b55880_idx'),
        ),
        migrations.AddIndex(
            model_name='investorbalancelot',
            index=models.Index(fields=['currency', 'investment_deadline_at'], name='ledger_inve_currenc_0061ae_idx'),
        ),
        migrations.AddIndex(
            model_name='investorbalancelot',
            index=models.Index(fields=['currency', 'withdrawal_deadline_at'], name='ledger_inve_currenc_fabed3_idx'),
        ),
        migrations.AddIndex(
            model_name='investorbalancelot',
            index=models.Index(fields=['source_type', 'source_id'], name='ledger_inve_source__7dedf7_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerposting',
            index=models.Index(fields=['journal_entry', 'side'], name='ledger_ledg_journal_b83d50_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerposting',
            index=models.Index(fields=['account', 'currency'], name='ledger_ledg_account_1960b0_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationsnapshot',
            index=models.Index(fields=['currency', 'as_of_date'], name='ledger_reco_currenc_77e49c_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationsnapshot',
            index=models.Index(fields=['created_by_admin_id', 'created_at'], name='ledger_reco_created_53279c_idx'),
        ),
    ]
