# Generated by Django 5.2.14 on 2026-06-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_ledger_append_only_guards"),
        ("platform_core", "0002_append_only_guards"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="investorbalancelot",
            constraint=models.CheckConstraint(
                condition=models.Q(original_amount_minor__gte=0)
                & models.Q(available_amount_minor__gte=0)
                & models.Q(invested_amount_minor__gte=0)
                & models.Q(withdrawn_amount_minor__gte=0)
                & models.Q(penalized_amount_minor__gte=0),
                name="ledger_balance_lot_amounts_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="investorbalancelot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    original_amount_minor=models.F("available_amount_minor")
                    + models.F("invested_amount_minor")
                    + models.F("withdrawn_amount_minor")
                    + models.F("penalized_amount_minor")
                ),
                name="ledger_balance_lot_amounts_conserved",
            ),
        ),
        migrations.AddConstraint(
            model_name="investorbalancelot",
            constraint=models.CheckConstraint(
                condition=~models.Q(status__in=["consumed", "penalty_exhausted"])
                | models.Q(available_amount_minor=0),
                name="ledger_balance_lot_terminal_zero_available",
            ),
        ),
    ]
