# Generated by Django 5.2.14 on 2026-06-02 12:17

import django.db.models.deletion
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0003_investorbalancelot_ledger_balance_lot_amounts_nonnegative_and_more"),
        ("platform_core", "0002_append_only_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestorWithdrawalRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("investor_user_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("finalized", "Finalized"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=32,
                    ),
                ),
                ("amount_minor", models.BigIntegerField()),
                ("destination_iban", models.CharField(max_length=128)),
                ("destination_account_name", models.CharField(blank=True, max_length=255)),
                ("requested_by_user_id", models.UUIDField()),
                ("requested_at", models.DateTimeField()),
                ("is_forced", models.BooleanField(default=False)),
                ("lot_allocations", models.JSONField(blank=True, default=list)),
                ("finalized_by_admin_id", models.UUIDField(blank=True, null=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("bank_reference", models.CharField(blank=True, max_length=160)),
                ("payment_reference", models.CharField(blank=True, max_length=160)),
                ("evidence_reference", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                (
                    "bank_operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawal_requests",
                        to="ledger.bankoperation",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investor_withdrawal_requests",
                        to="platform_core.currency",
                    ),
                ),
                (
                    "finalization_journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawal_requests_finalized",
                        to="ledger.ledgerjournalentry",
                    ),
                ),
                (
                    "request_journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawal_requests_opened",
                        to="ledger.ledgerjournalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["investor_user_id", "currency", "status"],
                        name="ledger_inve_investo_169ed3_idx",
                    ),
                    models.Index(
                        fields=["status", "requested_at"],
                        name="ledger_inve_status_d350db_idx",
                    ),
                    models.Index(
                        fields=["finalized_at"],
                        name="ledger_inve_finaliz_3d6088_idx",
                    ),
                    models.Index(
                        fields=["bank_reference"],
                        name="ledger_inve_bank_re_05f9b6_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(amount_minor__gt=0),
                        name="ledger_withdrawal_request_amount_positive",
                    )
                ],
            },
        ),
    ]
