# Generated by Django 5.2.14 on 2026-06-02 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0004_investorwithdrawalrequest"),
        ("platform_core", "0002_append_only_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="investorwithdrawalrequest",
            name="cancellation_journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="withdrawal_requests_cancelled",
                to="ledger.ledgerjournalentry",
            ),
        ),
        migrations.AddField(
            model_name="investorwithdrawalrequest",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="investorwithdrawalrequest",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="investorwithdrawalrequest",
            name="cancelled_by_admin_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="investorwithdrawalrequest",
            index=models.Index(fields=["cancelled_at"], name="ledger_inve_cancell_ffb3bf_idx"),
        ),
    ]
