# Generated by Django 5.2.14 on 2026-06-02 17:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0005_investorwithdrawalrequest_cancellation_journal_entry_and_more"),
        ("platform_core", "0002_append_only_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestorPayoutInstruction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("investor_user_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("disabled", "Disabled")],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("destination_iban", models.CharField(max_length=128)),
                ("destination_account_name", models.CharField(max_length=255)),
                ("is_verified_usable", models.BooleanField(default=False)),
                ("verified_by_admin_id", models.UUIDField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_by_admin_id", models.UUIDField()),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investor_payout_instructions",
                        to="platform_core.currency",
                    ),
                ),
            ],
            options={
                "ordering": ["investor_user_id", "currency", "-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["investor_user_id", "currency", "status"],
                        name="ledger_inve_investo_064294_idx",
                    ),
                    models.Index(
                        fields=["is_verified_usable", "status"],
                        name="ledger_inve_is_veri_7038a8_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(status="active"),
                        fields=("investor_user_id", "currency"),
                        name="ledger_one_active_payout_instruction_per_currency",
                    )
                ],
            },
        ),
    ]
