# Generated by Django 5.2.14 on 2026-06-02 22:42

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_investorpayoutinstruction'),
        ('platform_core', '0002_append_only_guards'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='investorbalancelot',
            name='ledger_balance_lot_amounts_nonnegative',
        ),
        migrations.RemoveConstraint(
            model_name='investorbalancelot',
            name='ledger_balance_lot_amounts_conserved',
        ),
        migrations.AddField(
            model_name='investorbalancelot',
            name='converted_amount_minor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='investorbalancelot',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount_minor__gte', 0), ('available_amount_minor__gte', 0), ('invested_amount_minor__gte', 0), ('converted_amount_minor__gte', 0), ('withdrawn_amount_minor__gte', 0), ('penalized_amount_minor__gte', 0)), name='ledger_balance_lot_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='investorbalancelot',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount_minor', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('available_amount_minor'), '+', models.F('invested_amount_minor')), '+', models.F('converted_amount_minor')), '+', models.F('withdrawn_amount_minor')), '+', models.F('penalized_amount_minor')))), name='ledger_balance_lot_amounts_conserved'),
        ),
    ]
