# Generated by Django 5.2.14 on 2026-06-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_remove_investorbalancelot_ledger_balance_lot_amounts_nonnegative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbalancelot',
            name='source_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('installment', 'Installment'), ('recovery_distribution', 'Recovery distribution'), ('secondary_market_proceeds', 'Secondary-market proceeds'), ('fx_proceeds', 'FX proceeds'), ('refund', 'Refund'), ('correction', 'Correction'), ('penalty_reversal', 'Penalty reversal')], max_length=64),
        ),
    ]
