# Generated by Django 5.2.16 on 2026-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_additive_payout_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankoperation',
            name='operation_type',
            field=models.CharField(choices=[('lender_deposit', 'Lender deposit'), ('lender_withdrawal', 'Lender withdrawal'), ('borrower_loan_disbursement', 'Borrower loan disbursement'), ('borrower_repayment', 'Borrower repayment'), ('garanta_out', 'Garanta out'), ('garanta_in', 'Garanta in'), ('currency_exchange_external_settlement', 'Currency exchange external settlement'), ('originator_settlement', 'Loan Originator settlement')], max_length=64),
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='account_type',
            field=models.CharField(choices=[('collection_cash', 'Collection cash'), ('investor_balance_liability', 'Investor balance liability'), ('garanta_accrued_revenue', 'Garanta accrued revenue'), ('suspense_unmatched_cash', 'Suspense/unmatched cash'), ('withdrawal_payable', 'Withdrawal payable'), ('refund_payable', 'Refund payable'), ('loan_funding_escrow', 'Loan funding escrow'), ('borrower_disbursement_payable', 'Borrower disbursement payable'), ('platform_fee_revenue', 'Platform fee revenue'), ('fx_clearing', 'FX clearing'), ('fx_fee_revenue', 'FX fee revenue'), ('fx_gain_loss', 'FX gain/loss'), ('recovery_distribution_payable', 'Recovery distribution payable'), ('originator_settlement_payable', 'Loan Originator settlement payable'), ('originator_servicing_payable', 'Loan Originator servicing payable')], max_length=64),
        ),
    ]
