# Generated by Django 5.2.16 on 2026-08-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_alter_bankoperation_operation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbalancelot',
            name='source_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('installment', 'Installment'), ('originator_claim_repayment', 'Loan Originator claim repayment'), ('recovery_distribution', 'Recovery distribution'), ('secondary_market_proceeds', 'Secondary-market proceeds'), ('fx_proceeds', 'FX proceeds'), ('refund', 'Refund'), ('correction', 'Correction'), ('penalty_reversal', 'Penalty reversal')], max_length=64),
        ),
    ]
