# Generated by Django 5.2.14 on 2026-06-03 20:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_document_append_only_guards'),
        ('holdings', '0002_holding_event_append_only_guard'),
        ('loans', '0005_alter_loan_status_alter_loanevent_event_type'),
        ('platform_core', '0002_append_only_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryMarketListing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_user_id', models.UUIDField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('approval_requested', 'Approval requested'), ('rejected', 'Rejected'), ('removed', 'Removed'), ('sold', 'Sold'), ('cancelled', 'Cancelled')], max_length=64)),
                ('publication_type', models.CharField(choices=[('automatic', 'Automatic'), ('admin_approved', 'Admin approved')], max_length=64)),
                ('current_principal_minor', models.BigIntegerField()),
                ('price_bps', models.PositiveIntegerField()),
                ('transfer_price_minor', models.BigIntegerField()),
                ('discount_premium_bps', models.IntegerField()),
                ('accrued_interest_minor', models.BigIntegerField(default=0)),
                ('accrued_interest_from_date', models.DateField(blank=True, null=True)),
                ('accrued_interest_to_date', models.DateField()),
                ('maker_fee_bps', models.PositiveIntegerField()),
                ('taker_fee_bps', models.PositiveIntegerField()),
                ('minimum_maker_fee_minor', models.BigIntegerField(default=0)),
                ('minimum_taker_fee_minor', models.BigIntegerField(default=0)),
                ('maker_fee_minor', models.BigIntegerField(default=0)),
                ('taker_fee_minor', models.BigIntegerField(default=0)),
                ('seller_net_proceeds_minor', models.BigIntegerField()),
                ('buyer_total_cost_minor', models.BigIntegerField()),
                ('loan_status_at_listing', models.CharField(max_length=64)),
                ('days_past_due', models.PositiveIntegerField(default=0)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('risk_acknowledgement_required', models.BooleanField(default=False)),
                ('public_disclosure_note', models.TextField(blank=True)),
                ('listed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_admin_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_reason', models.TextField(blank=True)),
                ('rejected_by_admin_id', models.UUIDField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('removed_by_admin_id', models.UUIDField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removal_reason', models.TextField(blank=True)),
                ('created_by_user_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary_market_listings', to='platform_core.currency')),
                ('document_acceptance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary_market_listings', to='documents.documentacceptanceevidence')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary_market_listings', to='holdings.investorloanholding')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary_market_listings', to='loans.loan')),
            ],
            options={
                'ordering': ['-listed_at', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SecondaryMarketListingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holding_id', models.UUIDField()),
                ('loan_id', models.UUIDField()),
                ('seller_user_id', models.UUIDField()),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('auto_published', 'Auto published'), ('approval_requested', 'Approval requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('removed', 'Removed')], max_length=64)),
                ('actor_user_id', models.UUIDField()),
                ('actor_account_type', models.CharField(max_length=64)),
                ('previous_status', models.CharField(blank=True, max_length=64)),
                ('new_status', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='secondary_market.secondarymarketlisting')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='secondarymarketlisting',
            index=models.Index(fields=['status', 'listed_at'], name='secondary_m_status_b82d13_idx'),
        ),
        migrations.AddIndex(
            model_name='secondarymarketlisting',
            index=models.Index(fields=['seller_user_id', 'status', 'created_at'], name='secondary_m_seller__e77df1_idx'),
        ),
        migrations.AddIndex(
            model_name='secondarymarketlisting',
            index=models.Index(fields=['holding', 'status'], name='secondary_m_holding_f494ea_idx'),
        ),
        migrations.AddIndex(
            model_name='secondarymarketlisting',
            index=models.Index(fields=['loan', 'status'], name='secondary_m_loan_id_e965d1_idx'),
        ),
        migrations.AddIndex(
            model_name='secondarymarketlisting',
            index=models.Index(fields=['currency', 'status'], name='secondary_m_currenc_4410e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='secondarymarketlisting',
            constraint=models.CheckConstraint(condition=models.Q(('current_principal_minor__gt', 0)), name='secondary_listing_current_principal_positive'),
        ),
        migrations.AddConstraint(
            model_name='secondarymarketlisting',
            constraint=models.CheckConstraint(condition=models.Q(('price_bps__gt', 0)), name='secondary_listing_price_bps_positive'),
        ),
        migrations.AddConstraint(
            model_name='secondarymarketlisting',
            constraint=models.CheckConstraint(condition=models.Q(('transfer_price_minor__gt', 0)), name='secondary_listing_transfer_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='secondarymarketlisting',
            constraint=models.CheckConstraint(condition=models.Q(('accrued_interest_minor__gte', 0)), name='secondary_listing_accrued_interest_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='secondarymarketlisting',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_maker_fee_minor__gte', 0), ('minimum_taker_fee_minor__gte', 0), ('maker_fee_minor__gte', 0), ('taker_fee_minor__gte', 0)), name='secondary_listing_fees_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='secondarymarketlisting',
            constraint=models.CheckConstraint(condition=models.Q(('seller_net_proceeds_minor__gte', 0)), name='secondary_listing_seller_net_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='secondarymarketlisting',
            constraint=models.CheckConstraint(condition=models.Q(('buyer_total_cost_minor__gt', 0)), name='secondary_listing_buyer_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='secondarymarketlisting',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'approval_requested'])), fields=('holding',), name='unique_open_secondary_listing_per_holding'),
        ),
        migrations.AddIndex(
            model_name='secondarymarketlistingevent',
            index=models.Index(fields=['listing', 'occurred_at'], name='secondary_m_listing_c9c45d_idx'),
        ),
        migrations.AddIndex(
            model_name='secondarymarketlistingevent',
            index=models.Index(fields=['loan_id', 'event_type'], name='secondary_m_loan_id_00eb44_idx'),
        ),
        migrations.AddIndex(
            model_name='secondarymarketlistingevent',
            index=models.Index(fields=['holding_id', 'event_type'], name='secondary_m_holding_faa213_idx'),
        ),
        migrations.AddIndex(
            model_name='secondarymarketlistingevent',
            index=models.Index(fields=['seller_user_id', 'occurred_at'], name='secondary_m_seller__99e7db_idx'),
        ),
        migrations.AddIndex(
            model_name='secondarymarketlistingevent',
            index=models.Index(fields=['actor_user_id', 'occurred_at'], name='secondary_m_actor_u_9bae57_idx'),
        ),
    ]
