# Generated by Django 5.2.14 on 2026-06-03 21:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_append_only_guards'),
        ('holdings', '0002_holding_event_append_only_guard'),
        ('ledger', '0007_remove_investorbalancelot_ledger_balance_lot_amounts_nonnegative_and_more'),
        ('loans', '0005_alter_loan_status_alter_loanevent_event_type'),
        ('platform_core', '0002_append_only_guards'),
        ('secondary_market', '0002_secondary_listing_event_append_only_guard'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondarymarketlisting',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondarymarketlisting',
            name='sold_to_user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secondarymarketlistingevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('auto_published', 'Auto published'), ('approval_requested', 'Approval requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('removed', 'Removed'), ('sold', 'Sold')], max_length=64),
        ),
        migrations.CreateModel(
            name='SecondaryMarketPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_user_id', models.UUIDField()),
                ('seller_user_id', models.UUIDField()),
                ('current_principal_minor', models.BigIntegerField()),
                ('price_bps', models.PositiveIntegerField()),
                ('transfer_price_minor', models.BigIntegerField()),
                ('discount_premium_bps', models.IntegerField()),
                ('accrued_interest_minor', models.BigIntegerField(default=0)),
                ('accrued_interest_from_date', models.DateField(blank=True, null=True)),
                ('accrued_interest_to_date', models.DateField()),
                ('maker_fee_bps', models.PositiveIntegerField()),
                ('taker_fee_bps', models.PositiveIntegerField()),
                ('minimum_maker_fee_minor', models.BigIntegerField(default=0)),
                ('minimum_taker_fee_minor', models.BigIntegerField(default=0)),
                ('maker_fee_minor', models.BigIntegerField(default=0)),
                ('taker_fee_minor', models.BigIntegerField(default=0)),
                ('seller_net_proceeds_minor', models.BigIntegerField()),
                ('buyer_total_cost_minor', models.BigIntegerField()),
                ('loan_status_at_purchase', models.CharField(max_length=64)),
                ('days_past_due', models.PositiveIntegerField(default=0)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('risk_acknowledgement_accepted', models.BooleanField(default=False)),
                ('buyer_lot_allocations', models.JSONField(blank=True, default=list)),
                ('purchased_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('buyer_holding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary_market_purchases', to='holdings.investorloanholding')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary_market_purchases', to='platform_core.currency')),
                ('ledger_journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary_market_purchases', to='ledger.ledgerjournalentry')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='secondary_market.secondarymarketlisting')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary_market_purchases', to='loans.loan')),
                ('purchase_document_acceptance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary_market_purchases', to='documents.documentacceptanceevidence')),
                ('seller_balance_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary_market_sales', to='ledger.investorbalancelot')),
                ('seller_holding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary_market_sales', to='holdings.investorloanholding')),
            ],
            options={
                'ordering': ['-purchased_at', '-id'],
                'indexes': [models.Index(fields=['listing', 'purchased_at'], name='secondary_m_listing_aa4dfb_idx'), models.Index(fields=['buyer_user_id', 'purchased_at'], name='secondary_m_buyer_u_e0e78d_idx'), models.Index(fields=['seller_user_id', 'purchased_at'], name='secondary_m_seller__874927_idx'), models.Index(fields=['loan', 'purchased_at'], name='secondary_m_loan_id_fddd45_idx'), models.Index(fields=['currency', 'purchased_at'], name='secondary_m_currenc_11788f_idx')],
                'constraints': [models.UniqueConstraint(fields=('listing',), name='unique_purchase_per_listing'), models.CheckConstraint(condition=models.Q(('current_principal_minor__gt', 0)), name='secondary_purchase_current_principal_positive'), models.CheckConstraint(condition=models.Q(('price_bps__gt', 0)), name='secondary_purchase_price_bps_positive'), models.CheckConstraint(condition=models.Q(('transfer_price_minor__gt', 0)), name='secondary_purchase_transfer_price_positive'), models.CheckConstraint(condition=models.Q(('accrued_interest_minor__gte', 0)), name='secondary_purchase_accrued_interest_nonnegative'), models.CheckConstraint(condition=models.Q(('minimum_maker_fee_minor__gte', 0), ('minimum_taker_fee_minor__gte', 0), ('maker_fee_minor__gte', 0), ('taker_fee_minor__gte', 0)), name='secondary_purchase_fees_nonnegative'), models.CheckConstraint(condition=models.Q(('seller_net_proceeds_minor__gte', 0)), name='secondary_purchase_seller_net_nonnegative'), models.CheckConstraint(condition=models.Q(('buyer_total_cost_minor__gt', 0)), name='secondary_purchase_buyer_total_positive')],
            },
        ),
    ]
