# Generated by Codex on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secondary_market", "0004_secondary_purchase_append_only_guard"),
    ]

    operations = [
        migrations.AddField(
            model_name="secondarymarketlisting",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="secondarymarketlisting",
            name="cancelled_by_user_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="secondarymarketlisting",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="secondarymarketlistingevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("auto_published", "Auto published"),
                    ("approval_requested", "Approval requested"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("removed", "Removed"),
                    ("cancelled", "Cancelled"),
                    ("sold", "Sold"),
                ],
                max_length=64,
            ),
        ),
    ]
