# Generated by Django 5.2.16 on 2026-07-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0005_secondarymarketlisting_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondarymarketlistingevent',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='secondarymarketlistingevent',
            name='request_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='secondarymarketlistingevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('auto_published', 'Auto published'), ('approval_requested', 'Approval requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('removed', 'Removed'), ('cancelled', 'Cancelled'), ('sold', 'Sold')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='secondarymarketlistingevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='unique_secondary_listing_event_idempotency_key'),
        ),
    ]
