# Generated by Django 5.2.16 on 2026-08-04 13:14

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


def backfill_existing_settlement_split(apps, schema_editor):
    settlement_model = apps.get_model("originator_claims", "OriginatorSettlement")
    settlement_model.objects.update(
        purchase_amount_minor=models.F("amount_minor"),
        servicing_amount_minor=0,
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0003_alter_investorloanholding_source_type'),
        ('ledger', '0011_alter_investorbalancelot_source_type'),
        ('originator_claims', '0002_append_only_guards'),
        ('platform_core', '0004_qa_dev_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorOriginatorRepaymentDistributionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor_user_id', models.UUIDField()),
                ('amount_minor', models.BigIntegerField()),
                ('principal_minor', models.BigIntegerField(default=0)),
                ('interest_minor', models.BigIntegerField(default=0)),
                ('penalty_minor', models.BigIntegerField(default=0)),
                ('current_principal_before_minor', models.BigIntegerField()),
                ('current_principal_after_minor', models.BigIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['repayment', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OriginatorBorrowerRepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_reference', models.CharField(max_length=128)),
                ('payment_type', models.CharField(choices=[('regular', 'Regular payment'), ('repayment_in_advance', 'Repayment in advance')], max_length=32)),
                ('principal_minor', models.BigIntegerField()),
                ('interest_minor', models.BigIntegerField()),
                ('penalty_minor', models.BigIntegerField(default=0)),
                ('fee_minor', models.BigIntegerField(default=0)),
                ('amount_minor', models.BigIntegerField()),
                ('investor_distributed_minor', models.BigIntegerField()),
                ('originator_payable_minor', models.BigIntegerField()),
                ('principal_before_minor', models.BigIntegerField()),
                ('principal_after_minor', models.BigIntegerField()),
                ('originator_principal_before_minor', models.BigIntegerField()),
                ('originator_principal_after_minor', models.BigIntegerField()),
                ('booking_date', models.DateField()),
                ('value_date', models.DateField()),
                ('created_by_admin_id', models.UUIDField()),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-value_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OriginatorSettlementRepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='originatorsettlement',
            name='originator_settlement_positive',
        ),
        migrations.AddField(
            model_name='originatorsettlement',
            name='purchase_amount_minor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='originatorsettlement',
            name='repayment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='originatorsettlement',
            name='servicing_amount_minor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='originatorclaimevent',
            name='event_type',
            field=models.CharField(choices=[('originator_created', 'Originator created'), ('originator_updated', 'Originator updated'), ('import_validated', 'Import validated'), ('loan_created', 'Loan created'), ('opportunity_published', 'Opportunity published'), ('opportunity_closed', 'Opportunity closed'), ('quote_created', 'Quote created'), ('claim_purchased', 'Claim purchased'), ('repayment_recorded', 'Repayment recorded'), ('servicing_status_changed', 'Servicing status changed'), ('settlement_recorded', 'Settlement recorded')], max_length=64),
        ),
        migrations.AlterField(
            model_name='originatorsettlement',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_existing_settlement_split, noop_reverse),
        migrations.AddConstraint(
            model_name='originatorsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0), ('purchase_amount_minor__gte', 0), ('servicing_amount_minor__gte', 0), models.Q(('purchase_count__gt', 0), ('repayment_count__gt', 0), _connector='OR')), name='originator_settlement_positive'),
        ),
        migrations.AddConstraint(
            model_name='originatorsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor', django.db.models.expressions.CombinedExpression(models.F('purchase_amount_minor'), '+', models.F('servicing_amount_minor')))), name='originator_settlement_amount_conserved'),
        ),
        migrations.AddField(
            model_name='investororiginatorrepaymentdistributionline',
            name='balance_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='originator_repayment_distribution_lines', to='ledger.investorbalancelot'),
        ),
        migrations.AddField(
            model_name='investororiginatorrepaymentdistributionline',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform_core.currency'),
        ),
        migrations.AddField(
            model_name='investororiginatorrepaymentdistributionline',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='originator_repayment_distribution_lines', to='holdings.investorloanholding'),
        ),
        migrations.AddField(
            model_name='originatorborrowerrepayment',
            name='bank_operation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='originator_borrower_repayment', to='ledger.bankoperation'),
        ),
        migrations.AddField(
            model_name='originatorborrowerrepayment',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform_core.currency'),
        ),
        migrations.AddField(
            model_name='originatorborrowerrepayment',
            name='journal_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='originator_borrower_repayment', to='ledger.ledgerjournalentry'),
        ),
        migrations.AddField(
            model_name='originatorborrowerrepayment',
            name='loan_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_repayments', to='originator_claims.originatorloanimport'),
        ),
        migrations.AddField(
            model_name='originatorborrowerrepayment',
            name='loan_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='originator_claims.originatorloanprofile'),
        ),
        migrations.AddField(
            model_name='investororiginatorrepaymentdistributionline',
            name='repayment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investor_distribution_lines', to='originator_claims.originatorborrowerrepayment'),
        ),
        migrations.AddField(
            model_name='originatorsettlementrepayment',
            name='repayment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_link', to='originator_claims.originatorborrowerrepayment'),
        ),
        migrations.AddField(
            model_name='originatorsettlementrepayment',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_links', to='originator_claims.originatorsettlement'),
        ),
        migrations.AddConstraint(
            model_name='originatorborrowerrepayment',
            constraint=models.UniqueConstraint(fields=('loan_profile', 'payment_reference'), name='originator_unique_recorded_payment_reference'),
        ),
        migrations.AddConstraint(
            model_name='originatorborrowerrepayment',
            constraint=models.CheckConstraint(condition=models.Q(('principal_minor__gte', 0), ('interest_minor__gte', 0), ('penalty_minor__gte', 0), ('fee_minor__gte', 0), ('amount_minor__gt', 0), ('investor_distributed_minor__gte', 0), ('originator_payable_minor__gte', 0), ('principal_before_minor__gt', 0), ('principal_after_minor__gte', 0), ('originator_principal_before_minor__gte', 0), ('originator_principal_after_minor__gte', 0)), name='originator_repayment_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='originatorborrowerrepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('principal_minor'), '+', models.F('interest_minor')), '+', models.F('penalty_minor')), '+', models.F('fee_minor')))), name='originator_repayment_components_conserved'),
        ),
        migrations.AddConstraint(
            model_name='originatorborrowerrepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor', django.db.models.expressions.CombinedExpression(models.F('investor_distributed_minor'), '+', models.F('originator_payable_minor')))), name='originator_repayment_distribution_conserved'),
        ),
        migrations.AddConstraint(
            model_name='originatorborrowerrepayment',
            constraint=models.CheckConstraint(condition=models.Q(('principal_after_minor', django.db.models.expressions.CombinedExpression(models.F('principal_before_minor'), '-', models.F('principal_minor')))), name='originator_repayment_principal_conserved'),
        ),
        migrations.AddConstraint(
            model_name='investororiginatorrepaymentdistributionline',
            constraint=models.UniqueConstraint(fields=('repayment', 'holding'), name='originator_unique_repayment_holding_line'),
        ),
        migrations.AddConstraint(
            model_name='investororiginatorrepaymentdistributionline',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0), ('principal_minor__gte', 0), ('interest_minor__gte', 0), ('penalty_minor__gte', 0), ('current_principal_before_minor__gte', 0), ('current_principal_after_minor__gte', 0)), name='originator_distribution_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='investororiginatorrepaymentdistributionline',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('principal_minor'), '+', models.F('interest_minor')), '+', models.F('penalty_minor')))), name='originator_distribution_amount_conserved'),
        ),
        migrations.AddConstraint(
            model_name='investororiginatorrepaymentdistributionline',
            constraint=models.CheckConstraint(condition=models.Q(('current_principal_after_minor', django.db.models.expressions.CombinedExpression(models.F('current_principal_before_minor'), '-', models.F('principal_minor')))), name='originator_distribution_principal_conserved'),
        ),
        migrations.AddConstraint(
            model_name='originatorsettlementrepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='originator_repayment_settlement_link_positive'),
        ),
    ]
