# Generated by Django 5.2.16 on 2026-08-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originator_claims', '0004_append_only_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='originatorloanprofile',
            name='held_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='originatorloanprofile',
            name='held_by_admin_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='originatorloanprofile',
            name='hold_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='originatorloanprofile',
            name='is_on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
