# Generated by Django 5.2.16 on 2026-09-03 12:19

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


APPEND_ONLY_TABLES = (
    "originator_claims_originatorfundingroundclose",
    "originator_claims_originatorsubscriptionactivation",
    "originator_claims_originatorsubscriptioncancellation",
)


def install_append_only_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == "postgresql":
            for table in APPEND_ONLY_TABLES:
                cursor.execute(
                    f"""
                    DROP TRIGGER IF EXISTS {table}_append_only_guard ON {table};
                    CREATE TRIGGER {table}_append_only_guard
                    BEFORE UPDATE OR DELETE ON {table}
                    FOR EACH ROW
                    EXECUTE FUNCTION platform_core_prevent_append_only_mutation();
                    """
                )
        elif vendor == "sqlite":
            for table in APPEND_ONLY_TABLES:
                cursor.execute(f"DROP TRIGGER IF EXISTS {table}_append_only_update_guard;")
                cursor.execute(f"DROP TRIGGER IF EXISTS {table}_append_only_delete_guard;")
                cursor.execute(
                    f"""
                    CREATE TRIGGER {table}_append_only_update_guard
                    BEFORE UPDATE ON {table}
                    BEGIN
                        SELECT RAISE(ABORT, 'append-only table cannot be updated');
                    END;
                    """
                )
                cursor.execute(
                    f"""
                    CREATE TRIGGER {table}_append_only_delete_guard
                    BEFORE DELETE ON {table}
                    BEGIN
                        SELECT RAISE(ABORT, 'append-only table cannot be deleted');
                    END;
                    """
                )


def uninstall_append_only_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == "postgresql":
            for table in APPEND_ONLY_TABLES:
                cursor.execute(f"DROP TRIGGER IF EXISTS {table}_append_only_guard ON {table};")
        elif vendor == "sqlite":
            for table in APPEND_ONLY_TABLES:
                cursor.execute(f"DROP TRIGGER IF EXISTS {table}_append_only_update_guard;")
                cursor.execute(f"DROP TRIGGER IF EXISTS {table}_append_only_delete_guard;")


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0011_alter_investorbalancelot_source_type"),
        ("loans", "0017_remove_loan_loan_product_type_required_fields_and_more"),
        ("originator_claims", "0007_originator_repayment_platform_costs"),
    ]

    operations = [
        migrations.CreateModel(
            name="OriginatorFundingRoundClose",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subscribed_principal_minor", models.BigIntegerField()),
                ("allocated_order_count", models.PositiveIntegerField()),
                ("funding_deadline", models.DateField()),
                ("close_reason", models.CharField(max_length=64)),
                ("triggered_by_user_id", models.UUIDField()),
                ("closed_at", models.DateTimeField()),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-closed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OriginatorSubscriptionActivation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("boundary_payment_reference", models.CharField(max_length=128)),
                ("boundary_payment_date", models.DateField()),
                ("starting_outstanding_principal_minor", models.BigIntegerField()),
                ("assigned_principal_minor", models.BigIntegerField()),
                ("originator_retained_principal_minor", models.BigIntegerField()),
                ("activated_by_admin_id", models.UUIDField()),
                ("activated_at", models.DateTimeField()),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-activated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OriginatorSubscriptionCancellation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("released_principal_minor", models.BigIntegerField(default=0)),
                ("released_order_count", models.PositiveIntegerField(default=0)),
                ("closed_not_invested_order_count", models.PositiveIntegerField(default=0)),
                ("reason", models.TextField()),
                ("cancelled_by_admin_id", models.UUIDField()),
                ("cancelled_at", models.DateTimeField()),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-cancelled_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="originatorloanprofile",
            name="activation_outstanding_principal_minor",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="originatorloanprofile",
            name="distribution_model",
            field=models.CharField(
                choices=[
                    ("legacy_yield_v1", "Legacy yield-priced claim"),
                    ("par_component_v2", "Par subscription with component participation"),
                ],
                default="legacy_yield_v1",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="originatorloanprofile",
            name="entitlement_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="originatorloanprofile",
            name="funding_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="originatorloanprofile",
            name="investor_interest_participation_bps",
            field=models.PositiveSmallIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name="originatorloanprofile",
            name="investor_penalty_participation_bps",
            field=models.PositiveSmallIntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name="originatorclaimevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("originator_created", "Originator created"),
                    ("originator_updated", "Originator updated"),
                    ("import_validated", "Import validated"),
                    ("loan_created", "Loan created"),
                    ("opportunity_published", "Opportunity published"),
                    ("opportunity_closed", "Opportunity closed"),
                    ("opportunity_held", "Opportunity held"),
                    ("funding_round_closed", "Funding round closed"),
                    ("funding_round_close_failed", "Funding round close failed"),
                    ("subscription_activated", "Subscription activated"),
                    ("subscription_cancelled", "Subscription cancelled"),
                    ("quote_created", "Quote created"),
                    ("claim_purchased", "Claim purchased"),
                    ("repayment_recorded", "Repayment recorded"),
                    ("servicing_status_changed", "Servicing status changed"),
                    ("settlement_recorded", "Settlement recorded"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="originatorloanprofile",
            name="opportunity_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("open", "Open"),
                    ("awaiting_activation", "Awaiting activation"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="originatorloanprofile",
            index=models.Index(
                fields=["distribution_model", "funding_deadline"],
                name="originator__distrib_dfb613_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="originatorloanprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("investor_interest_participation_bps__lte", 10000),
                    ("investor_penalty_participation_bps__lte", 10000),
                ),
                name="originator_component_participation_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="originatorloanprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("activation_outstanding_principal_minor__isnull", True),
                    ("activation_outstanding_principal_minor__gt", 0),
                    _connector="OR",
                ),
                name="originator_activation_principal_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="originatorloanprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("distribution_model", "legacy_yield_v1"),
                    models.Q(
                        ("funding_deadline__isnull", False),
                        ("entitlement_start_date__isnull", False),
                        ("activation_outstanding_principal_minor__isnull", False),
                        ("funding_deadline__lt", models.F("entitlement_start_date")),
                        ("premium_fee_bps", 0),
                    ),
                    _connector="OR",
                ),
                name="originator_par_subscription_terms_complete",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="originatorloanprofile",
            name="originator_target_yield_positive",
        ),
        migrations.AddConstraint(
            model_name="originatorloanprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_yield_bps__gte", 0)),
                name="originator_target_yield_nonnegative",
            ),
        ),
        migrations.AddField(
            model_name="originatorfundingroundclose",
            name="loan_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="funding_round_close",
                to="originator_claims.originatorloanprofile",
            ),
        ),
        migrations.AddField(
            model_name="originatorsubscriptionactivation",
            name="activation_journal_entry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="originator_subscription_activation",
                to="ledger.ledgerjournalentry",
            ),
        ),
        migrations.AddField(
            model_name="originatorsubscriptionactivation",
            name="funding_round_close",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activation",
                to="originator_claims.originatorfundingroundclose",
            ),
        ),
        migrations.AddField(
            model_name="originatorsubscriptionactivation",
            name="loan_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscription_activation",
                to="originator_claims.originatorloanprofile",
            ),
        ),
        migrations.AddField(
            model_name="originatorsubscriptioncancellation",
            name="loan_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscription_cancellation",
                to="originator_claims.originatorloanprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="originatorfundingroundclose",
            constraint=models.CheckConstraint(
                condition=models.Q(("subscribed_principal_minor__gt", 0)),
                name="originator_round_close_subscription_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="originatorfundingroundclose",
            constraint=models.CheckConstraint(
                condition=models.Q(("allocated_order_count__gt", 0)),
                name="originator_round_close_has_orders",
            ),
        ),
        migrations.AddConstraint(
            model_name="originatorsubscriptionactivation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("starting_outstanding_principal_minor__gt", 0),
                    ("assigned_principal_minor__gt", 0),
                    ("originator_retained_principal_minor__gte", 0),
                ),
                name="originator_activation_amounts_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="originatorsubscriptionactivation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "starting_outstanding_principal_minor",
                        django.db.models.expressions.CombinedExpression(
                            models.F("assigned_principal_minor"),
                            "+",
                            models.F("originator_retained_principal_minor"),
                        ),
                    )
                ),
                name="originator_activation_principal_conserved",
            ),
        ),
        migrations.AddConstraint(
            model_name="originatorsubscriptioncancellation",
            constraint=models.CheckConstraint(
                condition=models.Q(("released_principal_minor__gte", 0)),
                name="originator_subscription_cancel_release_nonnegative",
            ),
        ),
        migrations.AlterField(
            model_name="originatorloanprofile",
            name="distribution_model",
            field=models.CharField(
                choices=[
                    ("legacy_yield_v1", "Legacy yield-priced claim"),
                    ("par_component_v2", "Par subscription with component participation"),
                ],
                default="par_component_v2",
                max_length=32,
            ),
        ),
        migrations.RunPython(install_append_only_guards, uninstall_append_only_guards),
    ]
