# Generated by Django 5.2.16 on 2026-09-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("originator_claims", "0008_originatorfundingroundclose_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="originatorclaimevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("originator_created", "Originator created"),
                    ("originator_updated", "Originator updated"),
                    ("import_validated", "Import validated"),
                    ("loan_created", "Loan created"),
                    ("opportunity_published", "Opportunity published"),
                    ("opportunity_closed", "Opportunity closed"),
                    ("opportunity_held", "Opportunity held"),
                    ("funding_round_closed", "Funding round closed"),
                    ("funding_round_close_failed", "Funding round close failed"),
                    ("subscription_activation_overdue", "Subscription activation overdue"),
                    ("subscription_activated", "Subscription activated"),
                    ("subscription_cancelled", "Subscription cancelled"),
                    ("quote_created", "Quote created"),
                    ("claim_purchased", "Claim purchased"),
                    ("repayment_recorded", "Repayment recorded"),
                    ("servicing_status_changed", "Servicing status changed"),
                    ("settlement_recorded", "Settlement recorded"),
                ],
                max_length=64,
            ),
        ),
    ]
