# Generated by Django 5.2.16 on 2026-09-07 12:57

from importlib import import_module

from django.db import migrations, models


def restore_evidence_guards(apps, schema_editor):
    import_module(
        "backend.apps.originator_claims.migrations.0008_originatorfundingroundclose_and_more"
    ).install_append_only_guards(apps, schema_editor)


class Migration(migrations.Migration):
    dependencies = [
        ("originator_claims", "0009_alter_originatorclaimevent_event_type"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, restore_evidence_guards),
        migrations.AlterField(
            model_name="originatorsubscriptionactivation",
            name="boundary_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="originatorsubscriptionactivation",
            name="boundary_payment_reference",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.RunPython(restore_evidence_guards, migrations.RunPython.noop),
    ]
