# Generated by Django 5.2.16 on 2026-09-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("originator_claims", "0010_automatic_subscription_activation"),
    ]

    operations = [
        migrations.AddField(
            model_name="originatorloanprofile",
            name="borrower_legal_name_public",
            field=models.BooleanField(default=False),
        ),
    ]
