# Generated by Django 5.2.16 on 2026-09-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("originator_claims", "0011_explicit_borrower_identity_disclosure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanoriginator",
            name="kyb_evidence_reference",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
