# Generated by Django 5.2.16 on 2026-09-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originator_claims', '0012_offline_company_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanoriginator',
            name='investor_story',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
