# Generated by Django 5.2.14 on 2026-06-02 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_core', '0002_append_only_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerEntity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=255)),
                ('year_founded', models.PositiveSmallIntegerField()),
                ('entity_type', models.CharField(choices=[('swiss_company', 'Swiss company'), ('non_swiss_company', 'Non-Swiss company'), ('real_estate_project_company', 'Real estate project company'), ('special_purpose_vehicle', 'Special purpose vehicle'), ('other', 'Other')], default='swiss_company', max_length=64)),
                ('kyb_status', models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('manual_review', 'Manual review'), ('expired', 'Expired'), ('reverification_required', 'Re-verification required')], default='pending', max_length=32)),
                ('compliance_hold', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('registration_number', models.CharField(blank=True, max_length=128)),
                ('registered_address', models.TextField(blank=True)),
                ('operating_address', models.TextField(blank=True)),
                ('industry_activity', models.TextField(blank=True)),
                ('ownership_structure', models.TextField(blank=True)),
                ('beneficial_owners', models.JSONField(blank=True, default=list)),
                ('directors_officers', models.JSONField(blank=True, default=list)),
                ('authorized_signatories', models.JSONField(blank=True, default=list)),
                ('bank_account_details', models.JSONField(blank=True, default=dict)),
                ('financials_currency', models.CharField(blank=True, max_length=3)),
                ('assets_minor', models.BigIntegerField(blank=True, null=True)),
                ('liabilities_minor', models.BigIntegerField(blank=True, null=True)),
                ('revenue_last_year_minor', models.BigIntegerField(blank=True, null=True)),
                ('profit_last_year_minor', models.BigIntegerField(blank=True, null=True)),
                ('created_by_admin_id', models.UUIDField()),
                ('updated_by_admin_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ['legal_name', 'id'],
                'indexes': [models.Index(fields=['legal_name'], name='entities_bo_legal_n_d9457c_idx'), models.Index(fields=['kyb_status', 'compliance_hold'], name='entities_bo_kyb_sta_946de8_idx'), models.Index(fields=['country'], name='entities_bo_country_9b2b42_idx'), models.Index(fields=['entity_type'], name='entities_bo_entity__5a29b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='BorrowerDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('presentation', 'Borrower presentation'), ('financials', 'Financial PDF'), ('kyb_evidence', 'KYB/AML evidence'), ('generic', 'Generic borrower document'), ('other', 'Other')], max_length=64)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('investor_visible', models.BooleanField(default=False)),
                ('created_by_admin_id', models.UUIDField()),
                ('created_by_account_type', models.CharField(max_length=64)),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrower_documents', to='platform_core.storedfile')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='entities.borrowerentity')),
            ],
            options={
                'ordering': ['document_type', 'display_name', 'id'],
                'indexes': [models.Index(fields=['borrower', 'document_type'], name='entities_bo_borrowe_ce9333_idx'), models.Index(fields=['borrower', 'investor_visible'], name='entities_bo_borrowe_d163cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='BorrowerEntityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('kyb_status_changed', 'KYB status changed'), ('document_added', 'Document added')], max_length=32)),
                ('actor_user_id', models.UUIDField()),
                ('actor_account_type', models.CharField(max_length=64)),
                ('previous_kyb_status', models.CharField(blank=True, max_length=32)),
                ('new_kyb_status', models.CharField(blank=True, max_length=32)),
                ('note', models.TextField(blank=True)),
                ('evidence_summary', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='entities.borrowerentity')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['borrower', 'occurred_at'], name='entities_bo_borrowe_35c1f4_idx'), models.Index(fields=['event_type', 'occurred_at'], name='entities_bo_event_t_763a6a_idx'), models.Index(fields=['actor_user_id', 'occurred_at'], name='entities_bo_actor_u_1ba892_idx')],
            },
        ),
    ]
