# Generated by Django 5.2.14 on 2026-07-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_borrower_entity_event_append_only_guard'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowerentity',
            name='business_classification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='borrowerentity',
            name='business_classification_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowerentity',
            name='contact_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='borrowerentity',
            name='contact_info_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowerentity',
            name='financial_risk',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='borrowerentity',
            name='kyb_aml_observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='borrowerentity',
            name='registered_address_public',
            field=models.BooleanField(default=False),
        ),
    ]
