# Generated by Django 5.2.16 on 2026-09-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_borrowerentity_business_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowerentity',
            name='investor_story',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
