from __future__ import annotations

from django.urls import path

from backend.apps.ledger.api.views import (
    AdminPayoutInstructionDetailView,
    AdminPayoutInstructionRevokeView,
    AdminPayoutInstructionVerifyView,
    BalanceAgeingScanView,
    BorrowerDisbursementFinalizeView,
    CollectionAccountListView,
    InvestorBalanceSummaryView,
    InvestorPayoutInstructionRegisterView,
    InvestorSelfServicePayoutInstructionRegisterView,
    InvestorWithdrawalCancelView,
    InvestorWithdrawalFinalizeView,
    InvestorWithdrawalHistoryView,
    InvestorWithdrawalRequestCreateView,
    LenderDepositDeclareView,
    ReconciliationSnapshotCreateView,
)

urlpatterns = [
    path(
        "admin/lender-deposits/",
        LenderDepositDeclareView.as_view(),
        name="ledger-lender-deposit-declare",
    ),
    path(
        "admin/payout-instructions/",
        InvestorPayoutInstructionRegisterView.as_view(),
        name="ledger-investor-payout-instruction-register",
    ),
    path(
        "admin/payout-instructions/<uuid:instruction_id>/",
        AdminPayoutInstructionDetailView.as_view(),
        name="ledger-admin-payout-instruction-detail",
    ),
    path(
        "admin/payout-instructions/<uuid:instruction_id>/verify/",
        AdminPayoutInstructionVerifyView.as_view(),
        name="ledger-admin-payout-instruction-verify",
    ),
    path(
        "admin/payout-instructions/<uuid:instruction_id>/revoke/",
        AdminPayoutInstructionRevokeView.as_view(),
        name="ledger-admin-payout-instruction-revoke",
    ),
    path(
        "admin/collection-accounts/",
        CollectionAccountListView.as_view(),
        name="ledger-admin-collection-accounts",
    ),
    path(
        "payout-instructions/",
        InvestorSelfServicePayoutInstructionRegisterView.as_view(),
        name="ledger-investor-self-service-payout-instruction-register",
    ),
    path(
        "admin/investor-balance-summary/",
        InvestorBalanceSummaryView.as_view(),
        name="ledger-investor-balance-summary",
    ),
    path(
        "withdrawal-requests/",
        InvestorWithdrawalRequestCreateView.as_view(),
        name="ledger-investor-withdrawal-request-create",
    ),
    path(
        "admin/withdrawal-requests/history/",
        InvestorWithdrawalHistoryView.as_view(),
        name="ledger-investor-withdrawal-history",
    ),
    path(
        "admin/withdrawal-requests/<uuid:withdrawal_request_id>/finalize/",
        InvestorWithdrawalFinalizeView.as_view(),
        name="ledger-investor-withdrawal-finalize",
    ),
    path(
        "admin/withdrawal-requests/<uuid:withdrawal_request_id>/cancel/",
        InvestorWithdrawalCancelView.as_view(),
        name="ledger-investor-withdrawal-cancel",
    ),
    path(
        "admin/borrower-disbursements/",
        BorrowerDisbursementFinalizeView.as_view(),
        name="ledger-borrower-disbursement-finalize",
    ),
    path(
        "admin/reconciliation-snapshots/",
        ReconciliationSnapshotCreateView.as_view(),
        name="ledger-reconciliation-snapshot-create",
    ),
    path(
        "admin/balance-ageing-scans/",
        BalanceAgeingScanView.as_view(),
        name="ledger-balance-ageing-scan",
    ),
]
