# Generated by Django 5.2.14 on 2026-06-02 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('registration', 'Registration terms'), ('primary_market_investment', 'Primary-market investment'), ('secondary_market_purchase', 'Secondary-market purchase'), ('secondary_market_listing', 'Secondary-market listing')], max_length=64)),
                ('template_key', models.CharField(default='default', max_length=128)),
                ('language', models.CharField(default='en', max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_by_superadmin_id', models.UUIDField()),
                ('updated_by_superadmin_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ['category', 'template_key', 'language'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('checkbox_labels', models.JSONField(blank=True, default=list)),
                ('variable_schema', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('created_by_superadmin_id', models.UUIDField()),
                ('source_version_id', models.UUIDField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('legal_review_reference', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.documenttemplate')),
            ],
            options={
                'ordering': ['template', 'version_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='current_published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.documenttemplateversion'),
        ),
        migrations.CreateModel(
            name='DocumentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, choices=[('registration', 'Registration terms'), ('primary_market_investment', 'Primary-market investment'), ('secondary_market_purchase', 'Secondary-market purchase'), ('secondary_market_listing', 'Secondary-market listing')], max_length=64)),
                ('event_type', models.CharField(choices=[('template_created', 'Template created'), ('version_created', 'Version created'), ('version_published', 'Version published'), ('accepted', 'Accepted')], max_length=64)),
                ('actor_user_id', models.UUIDField()),
                ('actor_account_type', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='documents.documenttemplate')),
                ('template_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='documents.documenttemplateversion')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAcceptanceEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField()),
                ('category', models.CharField(choices=[('registration', 'Registration terms'), ('primary_market_investment', 'Primary-market investment'), ('secondary_market_purchase', 'Secondary-market purchase'), ('secondary_market_listing', 'Secondary-market listing')], max_length=64)),
                ('template_version_number', models.PositiveIntegerField()),
                ('template_hash', models.CharField(max_length=64)),
                ('context_type', models.CharField(max_length=64)),
                ('context_id', models.CharField(max_length=128)),
                ('accepted_checkbox_labels', models.JSONField(blank=True, default=list)),
                ('data_snapshot', models.JSONField(blank=True, default=dict)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='documents.documenttemplate')),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='documents.documenttemplateversion')),
            ],
            options={
                'ordering': ['-accepted_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='documenttemplateversion',
            index=models.Index(fields=['template', 'status'], name='documents_d_templat_51b418_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttemplateversion',
            index=models.Index(fields=['content_hash'], name='documents_d_content_b67bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttemplateversion',
            index=models.Index(fields=['created_at'], name='documents_d_created_1e7f5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='documenttemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_number'), name='unique_document_template_version_number'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['category', 'template_key', 'language'], name='documents_d_categor_4f286c_idx'),
        ),
        migrations.AddConstraint(
            model_name='documenttemplate',
            constraint=models.UniqueConstraint(fields=('category', 'template_key', 'language'), name='unique_document_template_identity'),
        ),
        migrations.AddIndex(
            model_name='documentevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='documents_d_event_t_f10d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentevent',
            index=models.Index(fields=['template', 'occurred_at'], name='documents_d_templat_73c173_idx'),
        ),
        migrations.AddIndex(
            model_name='documentevent',
            index=models.Index(fields=['template_version', 'occurred_at'], name='documents_d_templat_8d693d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentevent',
            index=models.Index(fields=['actor_user_id', 'occurred_at'], name='documents_d_actor_u_8c0649_idx'),
        ),
        migrations.AddIndex(
            model_name='documentacceptanceevidence',
            index=models.Index(fields=['user_id', 'category', 'accepted_at'], name='documents_d_user_id_415acd_idx'),
        ),
        migrations.AddIndex(
            model_name='documentacceptanceevidence',
            index=models.Index(fields=['context_type', 'context_id'], name='documents_d_context_e408b8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentacceptanceevidence',
            index=models.Index(fields=['template_version'], name='documents_d_templat_0615f8_idx'),
        ),
    ]
