# Generated by Django 5.2.14 on 2026-07-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_rendered_artifact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacceptanceevidence',
            name='category',
            field=models.CharField(choices=[('registration', 'Registration terms'), ('primary_market_investment', 'Primary-market investment'), ('secondary_market_purchase', 'Secondary-market purchase'), ('secondary_market_listing', 'Secondary-market listing'), ('risk_disclosure', 'Risk disclosure')], max_length=64),
        ),
        migrations.AlterField(
            model_name='documentevent',
            name='category',
            field=models.CharField(blank=True, choices=[('registration', 'Registration terms'), ('primary_market_investment', 'Primary-market investment'), ('secondary_market_purchase', 'Secondary-market purchase'), ('secondary_market_listing', 'Secondary-market listing'), ('risk_disclosure', 'Risk disclosure')], max_length=64),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='category',
            field=models.CharField(choices=[('registration', 'Registration terms'), ('primary_market_investment', 'Primary-market investment'), ('secondary_market_purchase', 'Secondary-market purchase'), ('secondary_market_listing', 'Secondary-market listing'), ('risk_disclosure', 'Risk disclosure')], max_length=64),
        ),
    ]
