# Generated by Django 5.2.14 on 2026-06-01 19:18

import uuid
from django.db import migrations, models


def seed_launch_currencies(apps, schema_editor):
    currency_model = apps.get_model("platform_core", "Currency")
    currency_model.objects.update_or_create(
        code="CHF",
        defaults={"name": "Swiss franc", "minor_units": 2, "is_enabled": True},
    )
    currency_model.objects.update_or_create(
        code="EUR",
        defaults={"name": "Euro", "minor_units": 2, "is_enabled": True},
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('minor_units', models.PositiveSmallIntegerField(default=2)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('value_type', models.CharField(default='json', max_length=32)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor_type', models.CharField(max_length=64)),
                ('actor_id', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=128)),
                ('target_type', models.CharField(blank=True, max_length=128)),
                ('target_id', models.CharField(blank=True, max_length=128)),
                ('request_id', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['action', 'occurred_at'], name='platform_co_action_a466ba_idx'), models.Index(fields=['target_type', 'target_id'], name='platform_co_target__1a6883_idx'), models.Index(fields=['actor_type', 'actor_id'], name='platform_co_actor_t_2cffcd_idx')],
            },
        ),
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=128)),
                ('aggregate_type', models.CharField(max_length=128)),
                ('aggregate_id', models.CharField(max_length=128)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('idempotency_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='platform_co_event_t_0cd0b6_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='platform_co_aggrega_fcc9f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('topic', models.CharField(max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('dead_letter', 'Dead letter')], default='pending', max_length=32)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='platform_co_status_c49a71_idx'), models.Index(fields=['topic', 'status'], name='platform_co_topic_6cb535_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettingVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('version', models.PositiveIntegerField()),
                ('value', models.JSONField(blank=True, default=dict)),
                ('value_type', models.CharField(default='json', max_length=32)),
                ('changed_by_type', models.CharField(max_length=64)),
                ('changed_by_id', models.CharField(max_length=128)),
                ('reason', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['key', 'version'],
                'indexes': [models.Index(fields=['key', 'occurred_at'], name='platform_co_key_2d8961_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'version'), name='unique_platform_setting_version')],
            },
        ),
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('scan_status', models.CharField(choices=[('quarantined', 'Quarantined'), ('clean', 'Clean'), ('infected', 'Infected'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='quarantined', max_length=32)),
                ('access_scope', models.CharField(choices=[('owner', 'Owner'), ('internal', 'Internal'), ('public', 'Public')], default='owner', max_length=32)),
                ('owner_type', models.CharField(blank=True, max_length=64)),
                ('owner_id', models.CharField(blank=True, max_length=128)),
                ('created_by_type', models.CharField(max_length=64)),
                ('created_by_id', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['owner_type', 'owner_id'], name='platform_co_owner_t_e92347_idx'), models.Index(fields=['scan_status', 'access_scope'], name='platform_co_scan_st_1a4609_idx')],
            },
        ),
        migrations.RunPython(seed_launch_currencies, migrations.RunPython.noop),
    ]
