# Generated by Django 5.2.16 on 2026-09-09 12:51

import backend.apps.platform_core.models.story_images
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0006_qa_archive_append_only_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=255, upload_to=backend.apps.platform_core.models.story_images.story_image_upload_path)),
                ('content_type', models.CharField(max_length=64)),
                ('byte_size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_by_id', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
