# Generated by Django 5.2.14 on 2026-06-01 21:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycVerificationCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('user', 'User'), ('legal_entity_lender', 'Legal-entity lender'), ('borrower', 'Borrower')], default='user', max_length=64)),
                ('subject_reference', models.CharField(max_length=128)),
                ('provider', models.CharField(default='didit', max_length=32)),
                ('provider_environment', models.CharField(max_length=32)),
                ('workflow_id', models.CharField(blank=True, max_length=128)),
                ('vendor_data', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('manual_review', 'Manual review'), ('high_risk', 'High risk'), ('sanctions_hit', 'Sanctions hit'), ('pep_hit', 'PEP hit'), ('adverse_media_hit', 'Adverse media hit'), ('expired', 'Expired'), ('reverification_required', 'Re-verification required')], default='not_started', max_length=64)),
                ('risk_classification', models.CharField(blank=True, max_length=64)),
                ('detected_flags', models.JSONField(blank=True, default=list)),
                ('provider_session_id', models.CharField(blank=True, max_length=128)),
                ('provider_verification_id', models.CharField(blank=True, max_length=128)),
                ('provider_report_id', models.CharField(blank=True, max_length=128)),
                ('aml_screening_id', models.CharField(blank=True, max_length=128)),
                ('provider_subject_id', models.CharField(blank=True, max_length=128)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('manual_review_required', models.BooleanField(default=False)),
                ('blocking_reason', models.TextField(blank=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kyc_verification_case', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KycProviderSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='didit', max_length=32)),
                ('provider_environment', models.CharField(max_length=32)),
                ('workflow_id', models.CharField(blank=True, max_length=128)),
                ('provider_session_id', models.CharField(max_length=128, unique=True)),
                ('verification_url', models.URLField(max_length=500)),
                ('vendor_data', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('manual_review', 'Manual review'), ('high_risk', 'High risk'), ('sanctions_hit', 'Sanctions hit'), ('pep_hit', 'PEP hit'), ('adverse_media_hit', 'Adverse media hit'), ('expired', 'Expired'), ('reverification_required', 'Re-verification required')], default='pending', max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_sessions', to='kyc_compliance.kycverificationcase')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KycProviderEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='didit', max_length=32)),
                ('provider_environment', models.CharField(max_length=32)),
                ('provider_event_id', models.CharField(max_length=128, unique=True)),
                ('provider_event_type', models.CharField(max_length=128)),
                ('provider_status', models.CharField(blank=True, max_length=128)),
                ('normalized_status', models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('manual_review', 'Manual review'), ('high_risk', 'High risk'), ('sanctions_hit', 'Sanctions hit'), ('pep_hit', 'PEP hit'), ('adverse_media_hit', 'Adverse media hit'), ('expired', 'Expired'), ('reverification_required', 'Re-verification required')], max_length=64)),
                ('provider_session_id', models.CharField(blank=True, max_length=128)),
                ('vendor_data', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField()),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_events', to='kyc_compliance.kycprovidersession')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_events', to='kyc_compliance.kycverificationcase')),
            ],
            options={
                'ordering': ['-processed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='kycverificationcase',
            index=models.Index(fields=['subject_type', 'subject_reference'], name='kyc_complia_subject_02ec52_idx'),
        ),
        migrations.AddIndex(
            model_name='kycverificationcase',
            index=models.Index(fields=['status'], name='kyc_complia_status_75f42d_idx'),
        ),
        migrations.AddIndex(
            model_name='kycverificationcase',
            index=models.Index(fields=['provider_session_id'], name='kyc_complia_provide_6941b3_idx'),
        ),
        migrations.AddIndex(
            model_name='kycprovidersession',
            index=models.Index(fields=['case', 'status', 'expires_at'], name='kyc_complia_case_id_2c959c_idx'),
        ),
        migrations.AddIndex(
            model_name='kycprovidersession',
            index=models.Index(fields=['provider_session_id'], name='kyc_complia_provide_54d9d8_idx'),
        ),
        migrations.AddIndex(
            model_name='kycproviderevent',
            index=models.Index(fields=['case', 'processed_at'], name='kyc_complia_case_id_81daa4_idx'),
        ),
        migrations.AddIndex(
            model_name='kycproviderevent',
            index=models.Index(fields=['provider_session_id'], name='kyc_complia_provide_b0e2ff_idx'),
        ),
        migrations.AddIndex(
            model_name='kycproviderevent',
            index=models.Index(fields=['normalized_status'], name='kyc_complia_normali_911dc7_idx'),
        ),
    ]
