# Generated by Django 5.2.14 on 2026-06-02 08:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_compliance', '0002_append_only_provider_event_guard'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycManualReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_user_id', models.UUIDField()),
                ('actor_account_type', models.CharField(max_length=64)),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('decline', 'Decline'), ('request_reverification', 'Request re-verification'), ('reopen', 'Reopen manual review')], max_length=64)),
                ('reason_code', models.CharField(choices=[('pep_review', 'PEP review'), ('high_risk_review', 'High-risk review'), ('adverse_media_review', 'Adverse-media review'), ('sanctions_review', 'Sanctions review'), ('provider_decline_review', 'Provider decline review'), ('inconclusive_provider_result', 'Inconclusive provider result'), ('document_or_identity_issue', 'Document or identity issue'), ('reverification_required', 'Re-verification required'), ('off_platform_review', 'Off-platform review'), ('admin_correction', 'Admin correction'), ('other', 'Other')], default='other', max_length=64)),
                ('previous_status', models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('manual_review', 'Manual review'), ('high_risk', 'High risk'), ('sanctions_hit', 'Sanctions hit'), ('pep_hit', 'PEP hit'), ('adverse_media_hit', 'Adverse media hit'), ('expired', 'Expired'), ('reverification_required', 'Re-verification required')], max_length=64)),
                ('new_status', models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('manual_review', 'Manual review'), ('high_risk', 'High risk'), ('sanctions_hit', 'Sanctions hit'), ('pep_hit', 'PEP hit'), ('adverse_media_hit', 'Adverse media hit'), ('expired', 'Expired'), ('reverification_required', 'Re-verification required')], max_length=64)),
                ('note', models.TextField(blank=True)),
                ('evidence_summary', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_review_decisions', to='kyc_compliance.kycverificationcase')),
            ],
            options={
                'ordering': ['-decided_at', '-id'],
                'indexes': [models.Index(fields=['case', 'decided_at'], name='kyc_complia_case_id_804d3c_idx'), models.Index(fields=['actor_user_id', 'decided_at'], name='kyc_complia_actor_u_7a3127_idx'), models.Index(fields=['decision'], name='kyc_complia_decisio_54423a_idx'), models.Index(fields=['new_status'], name='kyc_complia_new_sta_369e72_idx')],
            },
        ),
    ]
