# Generated by Django 5.2.16 on 2026-10-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_compliance", "0004_manual_review_decision_append_only_guard"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycprovidersession",
            name="superseded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
