# Generated by Django 5.2.14 on 2026-06-05 19:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_core', '0002_append_only_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDeliveryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=128)),
                ('template_key', models.CharField(max_length=128)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('provider', models.CharField(max_length=64)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('rendered', 'Rendered'), ('sent', 'Sent'), ('failed', 'Failed')], max_length=32)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outbox_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_delivery_records', to='platform_core.outboxmessage')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('email_sent', 'Email sent'), ('email_failed', 'Email failed')], max_length=64)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('outbox_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication_events', to='platform_core.outboxmessage')),
                ('email_delivery_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication_events', to='communications.emaildeliveryrecord')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='emaildeliveryrecord',
            index=models.Index(fields=['topic', 'created_at'], name='communicati_topic_baa6b5_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildeliveryrecord',
            index=models.Index(fields=['recipient_email', 'created_at'], name='communicati_recipie_ee2809_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildeliveryrecord',
            index=models.Index(fields=['status', 'created_at'], name='communicati_status_bedc36_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildeliveryrecord',
            index=models.Index(fields=['provider', 'provider_message_id'], name='communicati_provide_fd4174_idx'),
        ),
        migrations.AddConstraint(
            model_name='emaildeliveryrecord',
            constraint=models.UniqueConstraint(fields=('outbox_message', 'attempt_number'), name='unique_email_delivery_attempt'),
        ),
        migrations.AddIndex(
            model_name='communicationevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='communicati_event_t_286a52_idx'),
        ),
    ]
