# Generated by Django 5.2.16 on 2026-10-09 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models

READ_RECEIPT_TABLE = "communications_notificationreadreceipt"


def install_read_receipt_append_only_guard(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    table = READ_RECEIPT_TABLE
    with schema_editor.connection.cursor() as cursor:
        if vendor == "postgresql":
            cursor.execute(
                f"""
                DROP TRIGGER IF EXISTS {table}_append_only_guard ON {table};
                CREATE TRIGGER {table}_append_only_guard
                BEFORE UPDATE OR DELETE ON {table}
                FOR EACH ROW
                EXECUTE FUNCTION platform_core_prevent_append_only_mutation();
                """
            )
        elif vendor == "sqlite":
            cursor.execute(f"DROP TRIGGER IF EXISTS {table}_append_only_update_guard;")
            cursor.execute(f"DROP TRIGGER IF EXISTS {table}_append_only_delete_guard;")
            cursor.execute(
                f"""
                CREATE TRIGGER {table}_append_only_update_guard
                BEFORE UPDATE ON {table}
                BEGIN
                    SELECT RAISE(ABORT, 'append-only table cannot be updated');
                END;
                """
            )
            cursor.execute(
                f"""
                CREATE TRIGGER {table}_append_only_delete_guard
                BEFORE DELETE ON {table}
                BEGIN
                    SELECT RAISE(ABORT, 'append-only table cannot be deleted');
                END;
                """
            )


def uninstall_read_receipt_append_only_guard(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    table = READ_RECEIPT_TABLE
    with schema_editor.connection.cursor() as cursor:
        if vendor == "postgresql":
            cursor.execute(f"DROP TRIGGER IF EXISTS {table}_append_only_guard ON {table};")
        elif vendor == "sqlite":
            cursor.execute(f"DROP TRIGGER IF EXISTS {table}_append_only_update_guard;")
            cursor.execute(f"DROP TRIGGER IF EXISTS {table}_append_only_delete_guard;")


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_communications_append_only_guards"),
        ("platform_core", "0007_storyimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationReadReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("investor_user_id", models.UUIDField()),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outbox_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_read_receipts",
                        to="platform_core.outboxmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["-read_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["investor_user_id", "read_at"],
                        name="communicati_investo_e5233e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("investor_user_id", "outbox_message"),
                        name="unique_notification_read_receipt",
                    )
                ],
            },
        ),
        migrations.RunPython(
            install_read_receipt_append_only_guard,
            uninstall_read_receipt_append_only_guard,
        ),
    ]
