# Generated by Django 5.2.14 on 2026-06-02 22:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0007_remove_investorbalancelot_ledger_balance_lot_amounts_nonnegative_and_more'),
        ('platform_core', '0002_append_only_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor_user_id', models.UUIDField()),
                ('source_amount_minor', models.BigIntegerField()),
                ('provider', models.CharField(max_length=64)),
                ('provider_quote_id', models.CharField(blank=True, max_length=128)),
                ('rate', models.DecimalField(decimal_places=12, max_digits=24)),
                ('previous_day_average_rate', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('platform_fee_bps', models.PositiveIntegerField()),
                ('gross_target_amount_minor', models.BigIntegerField()),
                ('fee_minor', models.BigIntegerField()),
                ('target_amount_minor', models.BigIntegerField()),
                ('limit_chf_equivalent_minor', models.BigIntegerField()),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('provider_rate_timestamp', models.DateTimeField()),
                ('sanity_check_passed', models.BooleanField(default=True)),
                ('sanity_metadata', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_quotes_as_source', to='platform_core.currency')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_quotes_as_target', to='platform_core.currency')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FxExchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor_user_id', models.UUIDField()),
                ('source_amount_minor', models.BigIntegerField()),
                ('rate', models.DecimalField(decimal_places=12, max_digits=24)),
                ('platform_fee_bps', models.PositiveIntegerField()),
                ('gross_target_amount_minor', models.BigIntegerField()),
                ('fee_minor', models.BigIntegerField()),
                ('target_amount_minor', models.BigIntegerField()),
                ('limit_chf_equivalent_minor', models.BigIntegerField()),
                ('status', models.CharField(choices=[('completed', 'Completed')], default='completed', max_length=32)),
                ('source_lot_allocations', models.JSONField(blank=True, default=list)),
                ('executed_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_exchanges_as_source', to='platform_core.currency')),
                ('source_journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_source_exchanges', to='ledger.ledgerjournalentry')),
                ('target_balance_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_exchanges', to='ledger.investorbalancelot')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_exchanges_as_target', to='platform_core.currency')),
                ('target_journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_target_exchanges', to='ledger.ledgerjournalentry')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges', to='fx.fxquote')),
            ],
            options={
                'ordering': ['-executed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('quote_issued', 'Quote issued'), ('quote_sanity_rejected', 'Quote sanity rejected'), ('exchange_completed', 'Exchange completed')], max_length=64)),
                ('actor_user_id', models.UUIDField()),
                ('actor_account_type', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='fx.fxexchange')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='fx.fxquote')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='fxquote',
            index=models.Index(fields=['investor_user_id', 'issued_at'], name='fx_fxquote_investo_63f9e1_idx'),
        ),
        migrations.AddIndex(
            model_name='fxquote',
            index=models.Index(fields=['source_currency', 'target_currency', 'issued_at'], name='fx_fxquote_source__855b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='fxquote',
            index=models.Index(fields=['expires_at'], name='fx_fxquote_expires_b47ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='fxexchange',
            index=models.Index(fields=['investor_user_id', 'executed_at'], name='fx_fxexchan_investo_88d84d_idx'),
        ),
        migrations.AddIndex(
            model_name='fxexchange',
            index=models.Index(fields=['source_currency', 'target_currency', 'executed_at'], name='fx_fxexchan_source__032552_idx'),
        ),
        migrations.AddIndex(
            model_name='fxexchange',
            index=models.Index(fields=['quote'], name='fx_fxexchan_quote_i_c217ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='fxexchange',
            constraint=models.UniqueConstraint(fields=('quote',), name='unique_fx_exchange_per_quote'),
        ),
        migrations.AddIndex(
            model_name='fxevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='fx_fxevent_event_t_e90744_idx'),
        ),
        migrations.AddIndex(
            model_name='fxevent',
            index=models.Index(fields=['actor_user_id', 'occurred_at'], name='fx_fxevent_actor_u_a25035_idx'),
        ),
    ]
