# Generated by Django 5.2.14 on 2026-06-02 23:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0002_fx_append_only_guards'),
        ('ledger', '0007_remove_investorbalancelot_ledger_balance_lot_amounts_nonnegative_and_more'),
        ('platform_core', '0002_append_only_guards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxevent',
            name='event_type',
            field=models.CharField(choices=[('quote_issued', 'Quote issued'), ('quote_sanity_rejected', 'Quote sanity rejected'), ('exchange_completed', 'Exchange completed'), ('external_settlement_declared', 'External settlement declared')], max_length=64),
        ),
        migrations.CreateModel(
            name='FxExternalSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('expected_sold_amount_minor', models.BigIntegerField()),
                ('expected_bought_amount_minor', models.BigIntegerField()),
                ('expected_fee_minor', models.BigIntegerField()),
                ('sold_amount_minor', models.BigIntegerField()),
                ('bought_amount_minor', models.BigIntegerField()),
                ('sold_currency_residual_minor', models.BigIntegerField()),
                ('bought_currency_residual_minor', models.BigIntegerField()),
                ('actual_rate', models.DecimalField(decimal_places=12, max_digits=24)),
                ('booking_date', models.DateField()),
                ('value_date', models.DateField()),
                ('collection_account_identifier', models.CharField(blank=True, max_length=128)),
                ('bank_reference', models.CharField(blank=True, max_length=160)),
                ('payment_reference', models.CharField(blank=True, max_length=160)),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('declared', 'Declared')], default='declared', max_length=32)),
                ('declared_by_admin_id', models.UUIDField()),
                ('declared_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('bought_bank_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_external_settlements_bought', to='ledger.bankoperation')),
                ('bought_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_external_settlements_as_bought', to='platform_core.currency')),
                ('bought_journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_external_settlements_bought', to='ledger.ledgerjournalentry')),
                ('sold_bank_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_external_settlements_sold', to='ledger.bankoperation')),
                ('sold_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_external_settlements_as_sold', to='platform_core.currency')),
                ('sold_journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_external_settlements_sold', to='ledger.ledgerjournalentry')),
            ],
            options={
                'ordering': ['-declared_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='fxevent',
            name='external_settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='fx.fxexternalsettlement'),
        ),
        migrations.AddIndex(
            model_name='fxexternalsettlement',
            index=models.Index(fields=['sold_currency', 'bought_currency', 'start_date', 'end_date'], name='fx_fxextern_sold_cu_cb28a4_idx'),
        ),
        migrations.AddIndex(
            model_name='fxexternalsettlement',
            index=models.Index(fields=['declared_by_admin_id', 'declared_at'], name='fx_fxextern_declare_a3e7f8_idx'),
        ),
        migrations.AddIndex(
            model_name='fxexternalsettlement',
            index=models.Index(fields=['bank_reference'], name='fx_fxextern_bank_re_b57fc2_idx'),
        ),
        migrations.AddConstraint(
            model_name='fxexternalsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('sold_amount_minor__gt', 0), ('bought_amount_minor__gt', 0), ('expected_sold_amount_minor__gte', 0), ('expected_bought_amount_minor__gte', 0), ('expected_fee_minor__gte', 0)), name='fx_external_settlement_amounts_valid'),
        ),
    ]
