# Generated by Django 5.2.14 on 2026-06-03 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0004_external_settlement_append_only_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxExternalSettlementExchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_amount_minor', models.BigIntegerField()),
                ('gross_target_amount_minor', models.BigIntegerField()),
                ('target_amount_minor', models.BigIntegerField()),
                ('fee_minor', models.BigIntegerField()),
                ('settled_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_links', to='fx.fxexchange')),
                ('external_settlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settled_exchanges', to='fx.fxexternalsettlement')),
            ],
            options={
                'ordering': ['settled_at', 'id'],
                'indexes': [models.Index(fields=['external_settlement', 'settled_at'], name='fx_fxextern_externa_b55e54_idx'), models.Index(fields=['exchange'], name='fx_fxextern_exchang_77cd7c_idx')],
                'constraints': [models.UniqueConstraint(fields=('exchange',), name='unique_external_settlement_per_fx_exchange'), models.CheckConstraint(condition=models.Q(('source_amount_minor__gt', 0), ('gross_target_amount_minor__gt', 0), ('target_amount_minor__gt', 0), ('fee_minor__gte', 0)), name='fx_settlement_exchange_amounts_valid')],
            },
        ),
    ]
