# Generated by Django 5.2.16 on 2026-08-05 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_core', '0004_qa_dev_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartInvestRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('minimum_yield_bps', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_term_months', models.PositiveIntegerField(blank=True, null=True)),
                ('originator_scope', models.CharField(choices=[('all', 'All sources'), ('banxum', 'BANXUM direct lending'), ('specific', 'Specific Loan Originator')], default='all', max_length=16)),
                ('originator_id', models.UUIDField(blank=True, null=True)),
                ('collateral_scope', models.CharField(choices=[('all', 'Any collateral'), ('secured', 'With collateral'), ('unsecured', 'Without collateral'), ('specific', 'Specific collateral type')], default='all', max_length=16)),
                ('collateral_type', models.CharField(blank=True, max_length=64)),
                ('currency_scope', models.CharField(choices=[('all', 'CHF and EUR'), ('CHF', 'CHF'), ('EUR', 'EUR')], default='all', max_length=8)),
                ('risk_rating', models.CharField(blank=True, max_length=32)),
                ('purpose', models.CharField(blank=True, max_length=64)),
                ('loan_kind', models.CharField(choices=[('all', 'New lending and refinancing'), ('new', 'New lending'), ('refinancing', 'Refinancing')], default='all', max_length=16)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='smart_invest_rule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='SmartInvestMatchNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investor_user_id', models.UUIDField()),
                ('loan_id', models.UUIDField()),
                ('product_type', models.CharField(max_length=32)),
                ('rule_revision', models.PositiveIntegerField()),
                ('match_snapshot', models.JSONField(default=dict)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('outbox_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='smart_invest_match_notifications', to='platform_core.outboxmessage')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_notifications', to='smart_invest.smartinvestrule')),
            ],
            options={
                'ordering': ['notified_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SmartInvestRuleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investor_user_id', models.UUIDField()),
                ('actor_user_id', models.UUIDField()),
                ('event_type', models.CharField(choices=[('saved', 'Saved and activated'), ('deactivated', 'Deactivated')], max_length=32)),
                ('revision', models.PositiveIntegerField()),
                ('criteria_snapshot', models.JSONField(default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='smart_invest.smartinvestrule')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='smartinvestrule',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_yield_bps__isnull', True), ('minimum_yield_bps__lte', 100000), _connector='OR'), name='smart_invest_minimum_yield_bps_bounded'),
        ),
        migrations.AddConstraint(
            model_name='smartinvestrule',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_term_months__isnull', True), ('maximum_term_months__gte', 1), _connector='OR'), name='smart_invest_maximum_term_positive'),
        ),
        migrations.AddIndex(
            model_name='smartinvestmatchnotification',
            index=models.Index(fields=['investor_user_id', 'notified_at'], name='smart_inves_investo_0845a8_idx'),
        ),
        migrations.AddIndex(
            model_name='smartinvestmatchnotification',
            index=models.Index(fields=['loan_id', 'notified_at'], name='smart_inves_loan_id_eeeb43_idx'),
        ),
        migrations.AddConstraint(
            model_name='smartinvestmatchnotification',
            constraint=models.UniqueConstraint(fields=('investor_user_id', 'loan_id'), name='unique_smart_invest_match_notification'),
        ),
        migrations.AddIndex(
            model_name='smartinvestruleevent',
            index=models.Index(fields=['investor_user_id', 'occurred_at'], name='smart_inves_investo_f530c9_idx'),
        ),
        migrations.AddIndex(
            model_name='smartinvestruleevent',
            index=models.Index(fields=['rule', 'revision'], name='smart_inves_rule_id_617ae7_idx'),
        ),
    ]
